import type { SeedThread } from "../types";

export const THREADS_BLOODWORK: SeedThread[] = [
  // ==========================================================================
  // PINNED — community-maintained lab list
  // ==========================================================================
  {
    title: "Recommended labs for peptide users (community-maintained)",
    body: "Pinning this so we stop answering 'which labs should I pull' in 40 different threads. This is a living list — reply with additions/corrections and I'll fold them in.\n\nTier 1 — pull before ANY cycle, repeat ~8-12 weeks in:\n- CBC w/ diff\n- CMP (glucose, BUN, creatinine, eGFR, AST, ALT, ALP, bilirubin, albumin, electrolytes)\n- Lipid panel (TC, LDL, HDL, Trigs) — add ApoB if you can afford it\n- HbA1c + fasting insulin (for HOMA-IR)\n- TSH\n- Total testosterone (men)\n- IGF-1 if you're touching anything GH-adjacent\n\nTier 2 — cycle-dependent, add based on what you're running:\n- GH stacks: IGF-1, IGFBP-3, fasting glucose+insulin, HbA1c, prolactin (hexarelin/ghrelin-mimetic users)\n- GLP-1s: ApoB, lipid panel, HbA1c, lipase (baseline), amylase optional\n- BPC/TB-500: LFTs (AST/ALT/ALP), hs-CRP if you're tracking inflammation\n- Long courses of anything: Cystatin C > serum creatinine for kidney tracking\n\nTier 3 — nice-to-have, cheap add-ons:\n- Vit D 25-OH\n- Ferritin + iron panel\n- Homocysteine (especially if on GLP-1 / B12 absorption story)\n- hs-CRP\n- Magnesium RBC (not serum — serum is useless)\n\nDraw conditions that matter:\n- Fasted 10-12h for lipids, glucose, insulin\n- IGF-1: time of day matters less than people claim, but be CONSISTENT draw-to-draw\n- Cortisol: 7-9am draw, fasted\n- Prolactin: not after nipple stimulation (yes really), not immediately post-workout\n\nLab choice: LabCorp and Quest are broadly interchangeable but DON'T mix them within a cycle — reference ranges and even assay methods differ. Pick one and stick.\n\nReply with additions. I'll edit this post as consensus forms.",
    author: "lucidverse",
    daysAgo: 142,
    pinned: true,
    views: 14820,
    reactions: { USEFUL: 198, THANKS: 141, LIKE: 62, AGREE: 44 },
    replies: [
      {
        author: "cbc_cmp",
        body: "Endorsed. One nit: for Tier 1 I'd move ApoB up from 'if you can afford it' to standard. LabCorp charges ~$17 cash through Ulta/Marek if you're not going through insurance. No excuse.",
        daysAgo: 141,
        reactions: { AGREE: 38, USEFUL: 22 },
      },
      {
        author: "apob_reader",
        body: "+1 to ApoB-as-standard. Non-HDL-C is a decent proxy if you literally cannot get ApoB but ApoB is the real answer.",
        daysAgo: 141,
        reactions: { AGREE: 24, USEFUL: 11 },
      },
      {
        author: "igf_curve",
        body: "On IGF-1 timing — the half-life is ~15 hours so acute time-of-day swings are small, but there IS a real seasonal component (higher in summer in most populations). Not huge, but if you compare a winter baseline to a summer retest you'll see ~10-15 ng/mL variance independent of anything you're doing.",
        daysAgo: 140,
        reactions: { USEFUL: 47, THANKS: 19 },
      },
      {
        author: "homocystein_x",
        body: "Please add methylmalonic acid (MMA) as an option alongside homocysteine for B12 status. Homocysteine alone misses ~15% of B12 deficiencies because folate masks it. MMA is more specific.",
        daysAgo: 139,
        reactions: { USEFUL: 29, THANKS: 14 },
      },
      {
        author: "lucidverse",
        body: "Folded in. Updated Tier 3 to say 'Homocysteine + MMA for B-vitamin status'.",
        daysAgo: 139,
        reactions: { THANKS: 18, LIKE: 9 },
      },
      {
        author: "panel_maxer",
        body: "Cystatin C mention deserves to be louder. Creatinine is a muscle-mass confound — if you're gaining LBM on a GH stack your serum creatinine goes up for REASONS THAT HAVE NOTHING TO DO WITH YOUR KIDNEYS. I've watched people panic over a 1.15 mg/dL reading that just reflected 6 lbs of LBM.",
        daysAgo: 138,
        reactions: { USEFUL: 41, AGREE: 22, THANKS: 8 },
      },
      {
        author: "hba1c_watch",
        body: "For HbA1c, remember it integrates ~90 days of glucose so a 6-week retest doesn't capture the full change. Fructosamine is better for short windows (~2-3 weeks).",
        daysAgo: 137,
        reactions: { USEFUL: 34 },
      },
      {
        author: "dr_doubt",
        body: "Test-retest variability PSA: within-person CV for most of these is 4-8%. Don't read a 5% move as a real signal unless you've got multiple datapoints. IGF-1 specifically has CV ~6-9% even on the same analyzer with back-to-back draws.",
        daysAgo: 137,
        reactions: { USEFUL: 52, AGREE: 31, THANKS: 14 },
      },
      {
        author: "crp_cassandra",
        body: "hs-CRP note: a single reading is almost useless. It swings wildly with minor illness, tooth pain, overtraining. Need 2-3 readings spaced a week apart to get a real baseline.",
        daysAgo: 136,
        reactions: { USEFUL: 38, AGREE: 17 },
      },
      {
        author: "cardinal_rule",
        body: "Stickied. Keep the additions coming, we'll refresh every few months.",
        daysAgo: 135,
        reactions: { LIKE: 28, THANKS: 12 },
      },
      {
        author: "the_stats_guy",
        body: "Can we add a note on 'reference range' vs 'optimal range'? Most reference ranges are 95% CI of a reference population that includes a lot of metabolically unhealthy people. Being 'in range' at LDL-C 159 isn't the goal.",
        daysAgo: 134,
        reactions: { USEFUL: 44, AGREE: 26 },
      },
      {
        author: "protocolpilot",
        body: "Second this. Reference range for fasting insulin at LabCorp is 2.6-24.9 mIU/L — a 22 reading is 'normal' and also quietly terrible.",
        daysAgo: 134,
        reactions: { AGREE: 19 },
      },
      {
        author: "dexa_devotee",
        body: "Not strictly a blood lab but DEXA every 6 months belongs on this list for anyone on GH/tesa/GLP-1s. Scale weight lies, body comp shifts don't.",
        daysAgo: 133,
        reactions: { USEFUL: 31, AGREE: 18 },
      },
      {
        author: "glp1_doctor_pt",
        body: "For GLP-1 users — baseline lipase is worth doing once so you have a pre-cycle number if anything goes sideways. Most people never get a baseline and then panic if they pull one mid-cycle.",
        daysAgo: 131,
        reactions: { USEFUL: 27, AGREE: 12 },
      },
      {
        author: "showmethestudy",
        body: "Gently — can we tag which recommendations are evidence-backed vs 'community consensus'? Some of these are solid (ApoB, HbA1c) and some are more vibes-based.",
        daysAgo: 130,
        reactions: { AGREE: 33, USEFUL: 18 },
      },
      {
        author: "lucidverse",
        body: "Fair. I'll add a [E] tag for evidence-backed and [C] for community-consensus in the next edit pass.",
        daysAgo: 130,
        reactions: { THANKS: 22, AGREE: 14 },
      },
      {
        author: "citation_required",
        body: "Appreciated. The 'Cystatin C > creatinine' claim in particular has good evidence behind it, whereas 'fasted AM IGF-1' is more convention than necessity.",
        daysAgo: 129,
        reactions: { USEFUL: 21, AGREE: 12 },
      },
      {
        author: "nullhypothesis",
        body: "Also — 'tier 1' labs run ~$80-120 cash through a discount service. Worth stating explicitly so people don't think this requires insurance.",
        daysAgo: 128,
        reactions: { USEFUL: 29, THANKS: 9 },
      },
      {
        author: "stackbuilder",
        body: "Can we add SHBG to tier 1 for men? It's cheap, and it moves meaningfully on GLP-1s, tesa, and anything that changes insulin sensitivity. Without it, total T is harder to interpret.",
        daysAgo: 126,
        reactions: { USEFUL: 24, AGREE: 16 },
      },
      {
        author: "lucidverse",
        body: "Added SHBG to Tier 1 for men. Thanks.",
        daysAgo: 126,
        reactions: { THANKS: 14, LIKE: 7 },
      },
      {
        author: "notes_taker",
        body: "Saved. This is gold.",
        daysAgo: 124,
        reactions: { AGREE: 8 },
      },
      {
        author: "reads_more_posts",
        body: "Bookmarked. Thanks for maintaining this.",
        daysAgo: 118,
        reactions: { THANKS: 6 },
      },
    ],
  },

  // ==========================================================================
  // POPULAR THREADS (3 more — total 4 with the pinned)
  // ==========================================================================
  {
    title: "Pre/post GH stack labs — IGF-1 jumped from 210 to 340, thoughts?",
    body: "Running CJC-1295 no-DAC 100mcg + Ipamorelin 200mcg, 5x/week, AM empty stomach. 9 weeks in.\n\nLabs (LabCorp, same facility both draws, fasted, ~8am):\n\nBaseline:\n- IGF-1: 214 ng/mL (ref 83-233 for my age)\n- IGFBP-3: 4.1 mg/L\n- Fasting glucose: 88\n- Fasting insulin: 6.2 mIU/L\n- HbA1c: 5.2%\n\nWeek 9:\n- IGF-1: 341 ng/mL (!)\n- IGFBP-3: 5.3 mg/L\n- Fasting glucose: 94\n- Fasting insulin: 8.8 mIU/L\n- HbA1c: 5.4%\n\nThat's a 127 ng/mL jump. Feels like a lot? My assumption was CJC no-DAC + ipa would push IGF-1 maybe 50-80 points. Anyone running similar doses seeing this kind of response, or am I a high responder? 35M, 178lb, lean-ish, lift 4x/wk.\n\nThe insulin creep + a1c tick up is the part I actually want to discuss.",
    author: "igf_curve",
    daysAgo: 38,
    views: 6210,
    reactions: { USEFUL: 78, LIKE: 24, THANKS: 14 },
    replies: [
      {
        author: "protocolpilot",
        body: "That's a big but not unheard-of response for that dose. I've seen a handful of people go from ~200 to 320+ on 100/200 CJC-NoDAC/Ipa 5x/wk. The insulin nudge is also expected — GH axis activation does this, it's why we watch a1c.\n\nWhat time did you dose relative to the draw? If you dosed within 4-6h of the draw you'll get an inflated IGF-1 acute bump.",
        daysAgo: 38,
        reactions: { USEFUL: 41, AGREE: 18 },
      },
      {
        author: "igf_curve",
        body: "Last dose was evening before at ~10pm, draw was ~8am the next morning, so ~10h gap. Should be close to steady-state.",
        daysAgo: 38,
        reactions: { USEFUL: 14 },
      },
      {
        author: "cbc_cmp",
        body: "Steady state is basically the answer then. 341 is a real number. I wouldn't call you a 'high responder' exactly — more like upper-normal responder. IGF-1 response to GH secretagogues follows a wide distribution.\n\nHonestly the more interesting number is your insulin going 6.2 -> 8.8. Still in range but that's a meaningful direction. HOMA-IR went from ~1.35 to ~2.04 — you crossed the line some people draw at 2.0 for 'metabolic attention'.",
        daysAgo: 37,
        reactions: { USEFUL: 52, AGREE: 22 },
      },
      {
        author: "the_stats_guy",
        body: "HOMA-IR calc for others reading: (glucose mg/dL * insulin mIU/L) / 405. So 88*6.2/405 = 1.35 baseline, 94*8.8/405 = 2.04 now. cbc is right, that's a real move.",
        daysAgo: 37,
        reactions: { USEFUL: 38, THANKS: 11 },
      },
      {
        author: "dr_doubt",
        body: "Before the 'OMG insulin resistance' reads — within-person CV for fasting insulin is ~10-15%, sometimes higher. A single 6.2 vs 8.8 pair is ONE datapoint. Would be stronger with 2-3 draws at each end.",
        daysAgo: 37,
        reactions: { AGREE: 34, USEFUL: 19 },
      },
      {
        author: "stackbuilder",
        body: "^ this. Also, the a1c move is real but small. 5.2 -> 5.4 is within the assay's ~3% CV too, though trending the 'wrong' way. I'd want a retest at week 16-20 before getting nervous.",
        daysAgo: 37,
        reactions: { AGREE: 23, USEFUL: 14 },
      },
      {
        author: "hba1c_watch",
        body: "For what it's worth — my IGF-1 response to 100/200 CJC-NoDAC/Ipa was much smaller (178 -> 246). So responder variance is real. Your a1c move mirrors what I saw (5.1 -> 5.3 over 10 weeks). I don't think your data is alarming, just expected direction of travel.",
        daysAgo: 36,
        reactions: { USEFUL: 28, AGREE: 12 },
      },
      {
        author: "igf_curve",
        body: "Appreciate the sanity check. Plan is to hold dose, retest at week 16. If insulin keeps climbing I'll back to 4x/wk.",
        daysAgo: 36,
        reactions: { LIKE: 18, AGREE: 8 },
      },
      {
        author: "kineticdrift",
        body: "Curious — did you change diet/training at all during the 9 weeks? GH stacks tend to make people eat more (appetite from the GHRP side) and that alone can nudge insulin.",
        daysAgo: 35,
        reactions: { USEFUL: 19 },
      },
      {
        author: "igf_curve",
        body: "Yeah, ate ~300 kcal/day more in the first 5 weeks on appetite. Settled back down. So there's a confound.",
        daysAgo: 35,
        reactions: { USEFUL: 11 },
      },
      {
        author: "panel_maxer",
        body: "Pull an ALT too next round if you didn't. GH axis stuff can bump LFTs modestly, nothing scary usually but nice to have in the dataset.",
        daysAgo: 34,
        reactions: { USEFUL: 14 },
      },
      {
        author: "showmethestudy",
        body: "The 127 ng/mL jump is squarely within published CJC-1295/ipamorelin response distributions (most studies show ~80-160 point increases at similar doses, wide variance). You're unremarkable, which here is good news.",
        daysAgo: 33,
        reactions: { USEFUL: 31, AGREE: 14 },
      },
      {
        author: "nad_nightowl",
        body: "Tagging along — what's your sleep looking like? GH pulses are sleep-dependent and people who sleep better on GHRP stacks get bigger IGF-1 pops than people who don't change sleep.",
        daysAgo: 32,
        reactions: { USEFUL: 12 },
      },
      {
        author: "igf_curve",
        body: "Sleep has been noticeably deeper. Whoop deep sleep went from ~72 min avg to ~95 min. So that tracks.",
        daysAgo: 32,
        reactions: { USEFUL: 17 },
      },
      {
        author: "labrat_ish",
        body: "This thread is exactly why I lurk here. Saved.",
        daysAgo: 30,
        reactions: { THANKS: 8 },
      },
      {
        author: "protocolwonk",
        body: "One more thought: IGFBP-3 went 4.1 -> 5.3. The IGF-1 / IGFBP-3 molar ratio is almost unchanged, which is actually reassuring — means the free IGF-1 isn't running away from the binding protein. Some protocols push IGF-1 without moving IGFBP-3 and that's where people get edema/CTS.",
        daysAgo: 29,
        reactions: { USEFUL: 36, AGREE: 17, THANKS: 8 },
      },
      {
        author: "igf_curve",
        body: "That's a great frame, thank you. Will report back at the 16-week retest.",
        daysAgo: 29,
        reactions: { THANKS: 11 },
      },
    ],
  },
  {
    title: "ApoB on semaglutide — drop is real, here's the chart",
    body: "I pulled ApoB every 4 weeks on a 24-week sema course. Starting dose 0.25mg, titrated to 1.0mg over 8 weeks, held 1.0mg for the rest. 41F, 5'6\", baseline 189lb.\n\nApoB (mg/dL) timeline, all same lab (Quest), fasted AM:\n- Week 0:   118\n- Week 4:   112\n- Week 8:   103\n- Week 12:   94\n- Week 16:   87\n- Week 20:   83\n- Week 24:   79\n\nThat's a 33% drop. Weight went 189 -> 161 over the same window.\n\nLDL-C went 141 -> 94. Trigs 158 -> 71. HDL stayed put at 52 -> 54.\n\nI'd been told by my PCP to 'expect some lipid improvement' but this is more than I expected. Anyone else tracking ApoB on sema/tirz and seeing similar curves?\n\nSeparately: how much of this is attributable to the drug vs the weight loss is the question I can't answer from n=1.",
    author: "apob_reader",
    daysAgo: 52,
    views: 5890,
    reactions: { USEFUL: 94, THANKS: 28, LIKE: 31, AGREE: 18 },
    replies: [
      {
        author: "sema_saturday",
        body: "This matches my trajectory almost exactly. 124 -> 82 ApoB on 1.0mg sema, 18 weeks, 34lb down. Trigs smashed too (182 -> 68).\n\nThe weight loss vs drug effect question is hard but there's published data — even weight-stable GLP-1 users get modest ApoB drops (~8-12%). So the 'drug alone' contribution is real but small, most of the move is likely the weight/insulin sensitivity side.",
        daysAgo: 51,
        reactions: { USEFUL: 42, AGREE: 18 },
      },
      {
        author: "tirzepatide_tim",
        body: "Tirz dropped my ApoB 112 -> 73 over 20 weeks, -32lb. Same story basically. The trig drop especially feels disproportionate to the weight loss — I think GLP-1s do something mechanistically to VLDL.",
        daysAgo: 51,
        reactions: { USEFUL: 27, AGREE: 14 },
      },
      {
        author: "the_stats_guy",
        body: "Lovely chart. Quick nit: the week 0 -> 4 drop of 6 mg/dL is smaller than lab CV (ApoB CV is ~4-5%). I'd call the real signal starting at week 8. Doesn't change your story at all, just for methodological cleanliness.",
        daysAgo: 51,
        reactions: { USEFUL: 34, AGREE: 19 },
      },
      {
        author: "apob_reader",
        body: "Good point, noted. The monotonic decline from week 8 is the actual signal.",
        daysAgo: 51,
        reactions: { AGREE: 12 },
      },
      {
        author: "citation_required",
        body: "The SELECT trial secondary endpoints showed ApoB reductions of ~12-15% on sema 2.4mg over 2+ years, weight-adjusted. So your 33% drop is partly the drug but mostly the weight. Both matter, both compound.",
        daysAgo: 50,
        reactions: { USEFUL: 38, THANKS: 11 },
      },
      {
        author: "crp_cassandra",
        body: "Did you pull hs-CRP too? GLP-1s drop CRP meaningfully even weight-adjusted and it would add context here.",
        daysAgo: 50,
        reactions: { USEFUL: 17 },
      },
      {
        author: "apob_reader",
        body: "Yes — hs-CRP 3.4 -> 0.8. Easily the single biggest relative move of anything I tracked.",
        daysAgo: 50,
        reactions: { USEFUL: 29, THANKS: 8 },
      },
      {
        author: "dr_doubt",
        body: "hs-CRP 3.4 -> 0.8 is huge but CRP is so noisy (2-5x test-retest CV when you're low) that I wouldn't lean too hard on it. Still directionally right.",
        daysAgo: 49,
        reactions: { AGREE: 22, USEFUL: 12 },
      },
      {
        author: "glp1_doctor_pt",
        body: "This is the best single-person ApoB chart I've seen for sema. Can I crosspost to the GLP-1 thread with credit?",
        daysAgo: 48,
        reactions: { LIKE: 14, AGREE: 6 },
      },
      {
        author: "apob_reader",
        body: "Go for it.",
        daysAgo: 48,
      },
      {
        author: "plateau_breaker",
        body: "My ApoB didn't move nearly this much on tirz (139 -> 118, -15%) but I also only lost 12lb. Responder variance + weight loss amount seem to correlate. Useful thread.",
        daysAgo: 47,
        reactions: { USEFUL: 18 },
      },
      {
        author: "retatrutide_r",
        body: "Reta here — 18 weeks, -41lb. ApoB 131 -> 71. Even steeper curve than semaglutide imo. n=1 but the triple agonist seems to hit lipids harder.",
        daysAgo: 46,
        reactions: { USEFUL: 26, AGREE: 8 },
      },
      {
        author: "cbc_cmp",
        body: "Great thread. For anyone showing this to a skeptical PCP: Lp(a) won't move (genetic) so don't panic if that one doesn't respond to the GLP-1.",
        daysAgo: 45,
        reactions: { USEFUL: 31, THANKS: 10 },
      },
      {
        author: "apob_reader",
        body: "My Lp(a) was 41 nmol/L at baseline, 43 at week 24. So yeah, no move there. Confirms cbc's point.",
        daysAgo: 45,
        reactions: { USEFUL: 14 },
      },
      {
        author: "fat_loss_log",
        body: "Appreciate the transparency on the numbers. Saved this thread.",
        daysAgo: 42,
        reactions: { THANKS: 6 },
      },
      {
        author: "macrosguru",
        body: "Did your diet composition change? Satiety on sema is wild and most people end up eating lower fat / higher protein without trying. That alone shifts lipids.",
        daysAgo: 40,
        reactions: { USEFUL: 14 },
      },
      {
        author: "apob_reader",
        body: "Fat went from ~33% to ~26% of calories. Protein up, carbs roughly same %. So yes, there's a dietary confound baked in.",
        daysAgo: 40,
        reactions: { USEFUL: 18 },
      },
      {
        author: "lucidverse",
        body: "Fantastic dataset. Pinning to the 'useful lab threads' list.",
        daysAgo: 38,
        reactions: { LIKE: 12, THANKS: 5 },
      },
      {
        author: "silentscroll",
        body: "Thank you for posting this.",
        daysAgo: 32,
        reactions: { THANKS: 4 },
      },
    ],
  },
  {
    title: "hs-CRP baseline and after 8 weeks of BPC — chart inside",
    body: "Did a little self-experiment because I was curious if BPC-157 actually moves inflammatory markers systemically or only locally.\n\nProtocol: BPC-157 250mcg subQ peri-umbilical, 2x/day, 56 days. No other changes — same training, same diet, no injuries.\n\nhs-CRP readings (Quest, all fasted AM, Tuesdays):\n- Day 0:  1.8 mg/L\n- Day 14: 1.4\n- Day 28: 1.1\n- Day 42: 0.9\n- Day 56: 0.7\n- Day 70 (2 wks off): 1.1\n- Day 84 (4 wks off): 1.6\n\nSo a 61% drop over 8 weeks, and a clear rebound 2-4 weeks after stopping. That's a cleaner dose-response than I expected.\n\nCaveats upfront: single person, CRP is famously noisy, no control period. But the monotonic decline + rebound is suggestive.\n\nAnyone done a similar tracking?",
    author: "crp_cassandra",
    daysAgo: 67,
    views: 5140,
    reactions: { USEFUL: 86, LIKE: 24, THANKS: 16, AGREE: 14 },
    replies: [
      {
        author: "dr_doubt",
        body: "Going to be 'that guy' — hs-CRP CV is 30-50% within person depending on assay and baseline level. Your day-0 of 1.8 vs day-56 of 0.7 is inside CV for a single datapoint pair. What saves your analysis is the MONOTONIC trend and the rebound. Those two things together are a lot more convincing than any single number.",
        daysAgo: 67,
        reactions: { AGREE: 46, USEFUL: 28 },
      },
      {
        author: "crp_cassandra",
        body: "Fully agreed. I flagged the noise issue because it's real. If I were doing this again I'd do 2 draws at each timepoint 3-5 days apart to get a tighter signal. Budget said no.",
        daysAgo: 67,
        reactions: { AGREE: 22, THANKS: 8 },
      },
      {
        author: "tb500_train",
        body: "My hs-CRP dropped 2.1 -> 1.0 over a similar BPC/TB combo cycle (8 weeks, 300mcg BPC bid + TB 2mg/wk). Rebound after stopping also. So you're not alone.",
        daysAgo: 66,
        reactions: { USEFUL: 24, AGREE: 11 },
      },
      {
        author: "tendon_theory",
        body: "Interesting. I'd always assumed BPC's anti-inflammatory effect was primarily local (injection site / gut). A systemic hs-CRP drop changes that model.",
        daysAgo: 66,
        reactions: { USEFUL: 19 },
      },
      {
        author: "showmethestudy",
        body: "The existing literature on BPC-157 is almost entirely rodent + in vitro. There's no published human hs-CRP data I'm aware of. So this kind of community tracking is genuinely the best we have.",
        daysAgo: 65,
        reactions: { USEFUL: 37, AGREE: 18, THANKS: 9 },
      },
      {
        author: "cbc_cmp",
        body: "Did you pull IL-6 or ferritin alongside? Both are more stable inflammatory markers than CRP and would strengthen the case.",
        daysAgo: 65,
        reactions: { USEFUL: 21 },
      },
      {
        author: "crp_cassandra",
        body: "I pulled ferritin at day 0 and day 56. 118 -> 94 ng/mL. Directionally consistent with inflammation coming down, but ferritin is also iron status so it's muddy.",
        daysAgo: 65,
        reactions: { USEFUL: 17 },
      },
      {
        author: "panel_maxer",
        body: "The rebound is the single most interesting piece of this dataset. If it were all placebo or regression to mean, you wouldn't get a reliable bounce-back after withdrawal.",
        daysAgo: 64,
        reactions: { USEFUL: 34, AGREE: 19 },
      },
      {
        author: "nullhypothesis",
        body: "Could also just be a natural inflammatory event (minor cold, overtraining, bad sleep week) pushing day 70+ readings up. Would want to see multiple cycles/withdrawals to be confident the rebound is real.",
        daysAgo: 64,
        reactions: { AGREE: 22, USEFUL: 11 },
      },
      {
        author: "crp_cassandra",
        body: "Fair. I logged training load and sleep — neither was anomalous during the rebound window. But you're right that n=1 with one cycle isn't enough to claim rebound as a real effect.",
        daysAgo: 64,
        reactions: { AGREE: 14 },
      },
      {
        author: "igf_curve",
        body: "Really good methodology even with the noise caveats. This is the standard for self-experiments imo.",
        daysAgo: 63,
        reactions: { AGREE: 18, THANKS: 5 },
      },
      {
        author: "reggae_fiend",
        body: "Nice work. Anyone planning to repeat this design with BPC alone vs TB alone vs combo would settle a lot of debates.",
        daysAgo: 61,
        reactions: { AGREE: 12 },
      },
      {
        author: "hexaclinic",
        body: "I've done TB-500 solo over 10 weeks, hs-CRP went 2.4 -> 1.3. So independently the thymosin-beta arm seems to do something similar. Doesn't isolate either but adds a datapoint.",
        daysAgo: 60,
        reactions: { USEFUL: 22, AGREE: 9 },
      },
      {
        author: "citation_required",
        body: "Not to harp but I really do think this is the most informative BPC hs-CRP dataset on the English internet right now, noise and all.",
        daysAgo: 58,
        reactions: { LIKE: 19, AGREE: 10 },
      },
      {
        author: "crp_cassandra",
        body: "Flattered but overstated. I'd love for someone to do this with n=5-10 and a real washout.",
        daysAgo: 58,
        reactions: { LIKE: 11 },
      },
    ],
  },

  // ==========================================================================
  // ACTIVE THREADS (10 — 5-10 replies each)
  // ==========================================================================
  {
    title: "HbA1c ticked up mid-cycle on BPC-157?? (probably nothing, still)",
    body: "8 weeks into BPC-157 (250mcg bid, subQ). Pulled a routine CMP + a1c because I do quarterly labs.\n\n- a1c baseline: 5.1%\n- a1c week 8: 5.4%\n\nThat's inside the assay's test-retest window, I know. But BPC shouldn't do ANYTHING to glucose. I'm not changing diet. Not stressed. Same training.\n\nFasting glucose:\n- Baseline: 84\n- Week 8: 89\n\nAlso within noise. But the combination of both trending up on a peptide that shouldn't touch glucose is what's nagging at me.\n\nIs this just test-retest, or have others seen BPC do something to glucose?",
    author: "hba1c_watch",
    daysAgo: 44,
    views: 2780,
    reactions: { USEFUL: 28, LIKE: 8 },
    replies: [
      {
        author: "dr_doubt",
        body: "a1c assay CV is ~3%, so the SE on a 5.1 reading is ~0.15. A shift to 5.4 is within 2 SD. You've got nothing here, statistically speaking. Combined with a 5-point fasting glucose move (CV ~4-6%) — also within noise.\n\nI'd retest at week 12 before reading anything into it.",
        daysAgo: 44,
        reactions: { USEFUL: 32, AGREE: 17 },
      },
      {
        author: "bpc_baby",
        body: "What lab and draw time? a1c is pretty stable across time-of-day but hemolysis in the tube can confound readings and some labs are worse than others.",
        daysAgo: 44,
        reactions: { USEFUL: 12 },
      },
      {
        author: "hba1c_watch",
        body: "Quest both times, AM fasted. So that should be controlled for.",
        daysAgo: 44,
      },
      {
        author: "the_stats_guy",
        body: "Summer/winter effect on a1c is a thing too (people tend to run a touch higher in winter). What months did you draw?",
        daysAgo: 43,
        reactions: { USEFUL: 14 },
      },
      {
        author: "hba1c_watch",
        body: "Baseline late August, retest mid October. So some seasonal drift possible.",
        daysAgo: 43,
      },
      {
        author: "cbc_cmp",
        body: "Diet journal 100% honest? Holiday-season-adjacent snacking creep is the #1 cause of 'mystery a1c drift' in self-trackers and it's really easy to miss 100-200 kcal/day of carbs sneaking in.",
        daysAgo: 42,
        reactions: { USEFUL: 24, AGREE: 11, FUNNY: 6 },
      },
      {
        author: "hba1c_watch",
        body: "...fair. I wasn't tracking strictly in September. You might have me there.",
        daysAgo: 42,
        reactions: { FUNNY: 18, AGREE: 8 },
      },
      {
        author: "crp_cassandra",
        body: "Also worth noting: BPC is studied for GI stuff and there's some evidence it shifts the microbiome. Microbiome changes -> SCFA changes -> subtle glucose effects. None of this is big enough to move a1c 0.3 points but it's not literally zero mechanism either.",
        daysAgo: 41,
        reactions: { USEFUL: 22 },
      },
      {
        author: "panel_maxer",
        body: "Short answer: noise + probably the snack thing. Keep watching, report back at 12 weeks.",
        daysAgo: 40,
        reactions: { AGREE: 14 },
      },
    ],
  },
  {
    title: "Homocysteine + B vitamins question for GLP-1 users",
    body: "Quick question for the lab crowd. Pulled homocysteine for first time after 6 months on tirz (7.5mg), result was 14.2 umol/L. Lab ref range says <11.4.\n\nMy B12 was 412 pg/mL (in range 200-1100). Folate 9.4 (in range).\n\nEverything else on the CMP/CBC fine. No neuropathy, no fatigue.\n\nReading suggests GLP-1s can subtly interfere with B12 absorption over time. Is that actually a known thing or overblown? And if I supplement, methyl-B12 vs cyano?",
    author: "homocystein_x",
    daysAgo: 29,
    views: 2140,
    reactions: { USEFUL: 24, LIKE: 7 },
    replies: [
      {
        author: "cbc_cmp",
        body: "Serum B12 of 412 is 'in range' but it's in the 'functionally low' zone — most research suggests B12 deficiency symptoms start showing up below 500 and full sufficiency wants >600. Your elevated homocysteine is consistent with mild B12 inadequacy despite the 'normal' label.\n\nGet MMA (methylmalonic acid). That's the sensitive marker. If MMA is elevated you have a functional B12 issue.",
        daysAgo: 29,
        reactions: { USEFUL: 28, AGREE: 14, THANKS: 8 },
      },
      {
        author: "glp1_doctor_pt",
        body: "GLP-1s slow gastric emptying, which CAN reduce intrinsic factor-B12 complex formation over long courses. The effect is small and variable but real. 6 months in is a reasonable window to see it start.",
        daysAgo: 29,
        reactions: { USEFUL: 19, AGREE: 11 },
      },
      {
        author: "homocystein_x",
        body: "Ordering MMA now. What homocysteine value would you consider 'back to normal' after supplementation — under 8? under 10?",
        daysAgo: 28,
      },
      {
        author: "cbc_cmp",
        body: "I aim for <7 personally. 'Ref range says <11.4' but optimal-range folks put it under 8. If you're above 10 despite supplementation look at MTHFR variants.",
        daysAgo: 28,
        reactions: { USEFUL: 22, AGREE: 9 },
      },
      {
        author: "tirzepatide_tim",
        body: "Anecdotally — I was in the same situation (homocysteine 13.8 at 8 months on tirz). Started methyl-B12 1mg sublingual + methylfolate 400mcg. Retested at 4 months, homocysteine was 6.8. So it's fixable.",
        daysAgo: 28,
        reactions: { USEFUL: 26, THANKS: 12 },
      },
      {
        author: "showmethestudy",
        body: "Methyl- vs cyano- B12: for most people cyano is fine (the body converts it). Methyl-B12 is advantageous if you have MTHFR variants or really low B12 and want faster repletion. Evidence is weaker than internet-supplement-bro culture suggests.",
        daysAgo: 27,
        reactions: { USEFUL: 17, AGREE: 11 },
      },
      {
        author: "homocystein_x",
        body: "Helpful, thanks. Going to start methyl-B12 + methylfolate and retest in 8 weeks.",
        daysAgo: 27,
        reactions: { LIKE: 8, THANKS: 4 },
      },
      {
        author: "microdose_glp1",
        body: "Worth noting for others: this is why I suggest adding a B-complex as a default for anyone on GLP-1s beyond 3-4 months. Cheap insurance.",
        daysAgo: 26,
        reactions: { USEFUL: 18, AGREE: 12 },
      },
      {
        author: "sulfur_shrug",
        body: "Also consider TMG/betaine if homocysteine stays stubborn. Separate methylation pathway.",
        daysAgo: 25,
        reactions: { USEFUL: 11 },
      },
    ],
  },
  {
    title: "Cystatin C vs creatinine for tracking kidney on peptides",
    body: "I keep seeing Cystatin C mentioned as better than serum creatinine for kidney tracking during peptide cycles. Can someone walk through when each is better and which cases creatinine is actively misleading?\n\nContext: 6 months into a CJC/Ipa cycle. Gained ~6 lbs LBM per DEXA. Serum creatinine went from 0.94 to 1.08 mg/dL (still in range but trending up). eGFR calculated from that dropped from 98 to 88. My PCP is now quietly suggesting I 'watch the kidneys'.\n\nIs this actually a kidney issue or just the LBM confound?",
    author: "panel_maxer",
    daysAgo: 36,
    views: 3120,
    reactions: { USEFUL: 46, LIKE: 12, THANKS: 8 },
    replies: [
      {
        author: "cbc_cmp",
        body: "Classic LBM confound. Serum creatinine is a muscle-derived metabolite — if you gain 6 lbs of LBM your creatinine goes up with zero change in kidney function. Pull a Cystatin C, which is NOT muscle-mass dependent. If your Cystatin-C-based eGFR is normal, kidneys are fine.\n\nCreatinine of 1.08 at 6 lbs LBM gain is basically textbook for 'no kidney problem, just more muscle'.",
        daysAgo: 36,
        reactions: { USEFUL: 52, AGREE: 24 },
      },
      {
        author: "dr_doubt",
        body: "This is why I tell every GH/tesa user to get Cystatin C BEFORE the cycle. Then you have a non-muscle-confounded baseline to compare against.",
        daysAgo: 36,
        reactions: { AGREE: 28, USEFUL: 14 },
      },
      {
        author: "panel_maxer",
        body: "Ordered Cystatin C. If it's clean I'll send my PCP the paper trail.",
        daysAgo: 36,
        reactions: { LIKE: 14 },
      },
      {
        author: "igf_curve",
        body: "Also — BUN:creatinine ratio is often a better quick-look than creatinine alone. If BUN is proportionate you're probably just muscular. If BUN stays put while creatinine climbs, it's more likely real.",
        daysAgo: 35,
        reactions: { USEFUL: 22, AGREE: 8 },
      },
      {
        author: "the_stats_guy",
        body: "Cystatin C has its own noise (CV ~5-7%) but it's not muscle-confounded and it also responds to acute kidney changes faster than creatinine. Best single marker for your use case.",
        daysAgo: 35,
        reactions: { USEFUL: 18 },
      },
      {
        author: "citation_required",
        body: "KDIGO guidelines explicitly recommend Cystatin C confirmation when eGFR-creatinine is between 60-89 without other markers of kidney disease. Your case is literally what the guideline is for.",
        daysAgo: 34,
        reactions: { USEFUL: 31, THANKS: 11 },
      },
      {
        author: "panel_maxer",
        body: "UPDATE: Cystatin C back. 0.86 mg/L. Cystatin-C-eGFR is 102. So kidneys are actually BETTER than the creatinine-based eGFR suggested. LBM confound confirmed. Sending my PCP the literature.",
        daysAgo: 31,
        reactions: { USEFUL: 48, THANKS: 18, LIKE: 22 },
      },
      {
        author: "cbc_cmp",
        body: "As expected. Glad your PCP is getting educated alongside you.",
        daysAgo: 31,
        reactions: { LIKE: 14, AGREE: 7 },
      },
    ],
  },
  {
    title: "Testosterone didn't budge on tesamorelin — expected?",
    body: "12 weeks of tesamorelin 2mg/day. Pulled labs week 0 and week 12.\n\n- IGF-1: 198 -> 278 ng/mL (nice)\n- Fasting glucose: 88 -> 95 (ok-ish)\n- Visceral fat per DEXA: -14% (great)\n- Total T: 612 -> 621 ng/dL (basically unchanged)\n- Free T: 14.8 -> 15.1 pg/mL (unchanged)\n- SHBG: 34 -> 36 (unchanged)\n\nI'd sort of expected tesa to bump T at least modestly given the body comp improvement. Is that expectation wrong, or did my body just not respond that way?",
    author: "stackbuilder",
    daysAgo: 41,
    views: 2420,
    reactions: { USEFUL: 22, LIKE: 6 },
    replies: [
      {
        author: "protocolpilot",
        body: "Expectation is wrong — tesa is a GHRH analog, its effects are on GH/IGF-1 axis, not HPTA. Some people get a tiny T nudge from body comp changes but the effect is small and inconsistent. Your data looks textbook for a good tesa response: IGF-1 up, visceral fat down, T unchanged.",
        daysAgo: 41,
        reactions: { USEFUL: 28, AGREE: 12 },
      },
      {
        author: "hexaclinic",
        body: "My T also didn't move on tesa. Free T was actually slightly lower at retest (small, probably noise). The fat loss gets attributed to better T in the fitness press but in reality it's the direct lipolytic effect of GH pulses on visceral adipose.",
        daysAgo: 41,
        reactions: { USEFUL: 22, AGREE: 9 },
      },
      {
        author: "dr_doubt",
        body: "Total T CV is ~10-12% within person on a single draw. Your 612 -> 621 is genuinely 'unchanged' — even a 50-point move would be within noise.",
        daysAgo: 40,
        reactions: { USEFUL: 17, AGREE: 11 },
      },
      {
        author: "stackbuilder",
        body: "Makes sense. So anyone thinking tesa is going to shift their T numbers is probably barking up the wrong tree.",
        daysAgo: 40,
        reactions: { AGREE: 8 },
      },
      {
        author: "panel_maxer",
        body: "Right. For T-specific moves you're looking at clomid/enclomiphene, HCG, or actual TRT. Tesa is a body comp / IGF-1 tool, not an HPTA tool.",
        daysAgo: 39,
        reactions: { USEFUL: 14, AGREE: 7 },
      },
      {
        author: "the_architect_p",
        body: "Also — your IGF-1 response (198 -> 278) is a solid respondent profile. That matters more for the 'am I getting value from this' question than whether T moved.",
        daysAgo: 38,
        reactions: { USEFUL: 12 },
      },
      {
        author: "showmethestudy",
        body: "The tesamorelin HIV-lipodystrophy trials explicitly reported no meaningful testosterone changes. So your data is aligned with the published record.",
        daysAgo: 36,
        reactions: { USEFUL: 21, AGREE: 8 },
      },
    ],
  },
  {
    title: "Liver enzymes during a long TB-500 cycle",
    body: "Quick anecdote and looking for confirmation. 16 weeks of TB-500 (2.5mg loading x4 weeks, 2mg/wk maintenance). Pulled LFTs at baseline, week 8, week 16.\n\n- AST: 22 -> 27 -> 26 U/L\n- ALT: 24 -> 32 -> 30 U/L\n- ALP: 74 -> 78 -> 73\n- GGT: 18 -> 21 -> 19\n\nAll in range the whole time but ALT is trending a touch up at the 8-week mark then stable. Training didn't change, no new supplements, no alcohol uptick.\n\nIs this real or noise? Anyone else tracked LFTs through long TB cycles?",
    author: "tb500_train",
    daysAgo: 33,
    views: 1890,
    reactions: { USEFUL: 18, LIKE: 5 },
    replies: [
      {
        author: "cbc_cmp",
        body: "ALT 24 -> 32 is about 33% which sounds big but is inside within-person CV for ALT (~15-25%) plus the small n. Alone I wouldn't read anything into it. Also, ALT is sensitive to RECENT training — if you trained hard in the 72h before the draw it'll be 10-20% higher just from that.",
        daysAgo: 33,
        reactions: { USEFUL: 22, AGREE: 11 },
      },
      {
        author: "tb500_train",
        body: "Trained legs about 48h before the week-8 draw. So that's a confound.",
        daysAgo: 33,
        reactions: { USEFUL: 9 },
      },
      {
        author: "dr_doubt",
        body: "There's your answer. Leg day within 72h will puff ALT and AST via muscle leak (CK too). Not liver. If you want clean LFTs, take 96+ hours off training before the draw.",
        daysAgo: 33,
        reactions: { AGREE: 24, USEFUL: 13 },
      },
      {
        author: "panel_maxer",
        body: "Also pull CK alongside LFTs next time. If CK is elevated, the ALT bump is muscle not liver. Clean way to disambiguate.",
        daysAgo: 32,
        reactions: { USEFUL: 18, THANKS: 6 },
      },
      {
        author: "tendon_theory",
        body: "I've done 2 long TB cycles (12 and 14 weeks) with LFTs pulled, rest-adjusted, and neither showed any real liver signal. Anecdotal consensus seems to be TB is not hepatotoxic at these doses.",
        daysAgo: 31,
        reactions: { USEFUL: 16, AGREE: 7 },
      },
      {
        author: "achilles_love",
        body: "Can confirm — 10 weeks TB, LFTs stone cold flat.",
        daysAgo: 30,
        reactions: { AGREE: 8 },
      },
    ],
  },
  {
    title: "Prolactin bump on hexarelin — anyone else?",
    body: "I know this is a known side effect but curious about the real-world magnitude.\n\nHexarelin 100mcg 2x/day for 4 weeks (yes I know that's a short window, the prolactin is part of why).\n\n- Prolactin baseline: 9.1 ng/mL (ref 4-15)\n- Prolactin week 4: 22.4 ng/mL (!)\n\nAbove the reference range. No symptoms — no galactorrhea, libido fine, no headaches. But 22.4 is a real number.\n\nIs this just hexarelin doing what hexarelin does, or should I be using a cabergoline-style mitigation next time?",
    author: "hexaclinic",
    daysAgo: 46,
    views: 2340,
    reactions: { USEFUL: 24, LIKE: 8 },
    replies: [
      {
        author: "protocolwonk",
        body: "This is consistent with published hexarelin data — it's the 'dirty' GHRP and hits prolactin/cortisol harder than ipa or ghrp-2. 22.4 is elevated but not wildly so. If you're going to run hexarelin more than 4-6 weeks, cabergoline 0.25mg 2x/week is the usual mitigation.\n\nOr just swap to ipa/ghrp-2 if the prolactin bothers you.",
        daysAgo: 46,
        reactions: { USEFUL: 28, AGREE: 14 },
      },
      {
        author: "stackbuilder",
        body: "I switched from hexarelin to ipa specifically because of this. My prolactin on hex was 27 at 6 weeks, symptom-free but annoying. On ipa 300mcg bid my prolactin was 11 at 8 weeks. Night and day.",
        daysAgo: 46,
        reactions: { USEFUL: 22, AGREE: 8 },
      },
      {
        author: "cbc_cmp",
        body: "Draw timing matters a LOT for prolactin — within ~30 min post-workout it can be 2-3x baseline. Stress, sleep issues, nipple stim the night before. Need to standardize draw conditions.",
        daysAgo: 45,
        reactions: { USEFUL: 19, AGREE: 11 },
      },
      {
        author: "hexaclinic",
        body: "Both draws ~8am fasted, no training within 12h. So probably real.",
        daysAgo: 45,
      },
      {
        author: "dr_doubt",
        body: "Prolactin CV is high (15-25%) especially at low baselines. A 9 -> 22 move is outside pure-noise though. I'd call this a real signal from the hexarelin.",
        daysAgo: 44,
        reactions: { USEFUL: 14, AGREE: 6 },
      },
      {
        author: "kineticdrift",
        body: "If you're symptom-free and only running 4-6 weeks hex, honestly I'd just ride it out. Cabergoline has its own issues and adding a dopamine agonist to solve a minor asymptomatic elevation is overkill.",
        daysAgo: 43,
        reactions: { USEFUL: 17, AGREE: 12 },
      },
      {
        author: "hexaclinic",
        body: "Fair. Probably going to just run hex in short 4-week blocks and retest later.",
        daysAgo: 42,
        reactions: { AGREE: 7 },
      },
    ],
  },
  {
    title: "Insulin and glucose on GH secretagogue stack (fasted AM values)",
    body: "Tracking weekly fasting glucose + insulin on a CJC-NoDAC/Ipa/tesa stack (100mcg/200mcg/1mg). 10 weeks in. Same meter (Contour Next), same lab for insulin (Quest), draws Tuesday AM fasted 12h, same restaurant for coffee the day before (kidding).\n\nGlucose (mg/dL, fingerstick mean of 3):\n- Wk 0:  84\n- Wk 2:  86\n- Wk 4:  89\n- Wk 6:  91\n- Wk 8:  93\n- Wk 10: 92\n\nInsulin (mIU/L, lab):\n- Wk 0:  5.8\n- Wk 4:  7.1\n- Wk 8:  8.9\n- Wk 10: 9.4\n\nHOMA-IR: 1.20 -> 1.47 -> 2.04 -> 2.14.\n\nThat's not catastrophic but it's the 'GH stack insulin creep' I keep reading about. How much of this do I eat before cutting a dose?",
    author: "igf_curve",
    daysAgo: 24,
    views: 2680,
    reactions: { USEFUL: 32, LIKE: 9 },
    replies: [
      {
        author: "protocolpilot",
        body: "My heuristic: HOMA-IR < 1.5 = fine, 1.5-2.0 = monitor, 2.0-2.5 = pull back one lever (drop dose, cut days, or swap tesa out), >2.5 = hard stop on stack and reassess. You're at the 'pull back one lever' threshold.\n\nEasiest lever here is probably cutting tesa to 1mg 5x/wk from 1mg daily, or dropping CJC to 4x/wk.",
        daysAgo: 24,
        reactions: { USEFUL: 34, AGREE: 17 },
      },
      {
        author: "stackbuilder",
        body: "Agreed with above. My additional take: add berberine 500mg tid if diet is dialed. Cheap insurance, real effect on fasting insulin (~15-20% drop in most responders).",
        daysAgo: 24,
        reactions: { USEFUL: 21, AGREE: 9 },
      },
      {
        author: "cbc_cmp",
        body: "Also — carb timing. If you're eating most carbs in the evening the fasting insulin takes longer to drop overnight. Shifting carbs earlier in the day can reduce fasting insulin 10-20% independent of drug changes.",
        daysAgo: 23,
        reactions: { USEFUL: 24, AGREE: 11 },
      },
      {
        author: "the_stats_guy",
        body: "Your glucose trend looks close to maxed-out at 92-93. Likely to stabilize. Insulin is the one you want to watch — it's still climbing.",
        daysAgo: 23,
        reactions: { USEFUL: 16, AGREE: 8 },
      },
      {
        author: "nad_nightowl",
        body: "Are you doing AM dosing? Some people see meaningfully less insulin creep shifting their GH secretagogues to post-workout + bedtime only, skipping the AM pulse.",
        daysAgo: 22,
        reactions: { USEFUL: 14 },
      },
      {
        author: "igf_curve",
        body: "AM + PM currently. Going to try bedtime-only for 2 weeks and retest.",
        daysAgo: 22,
        reactions: { LIKE: 9 },
      },
      {
        author: "dr_doubt",
        body: "Don't forget HbA1c is the integrator of record. Weekly fasting glucose + insulin is a great early warning system but a1c at week 12 is the 'is this a real metabolic issue' datapoint.",
        daysAgo: 21,
        reactions: { AGREE: 18, USEFUL: 11 },
      },
      {
        author: "igf_curve",
        body: "a1c baseline 5.1, pulling it at week 12 (next week). Will update.",
        daysAgo: 21,
        reactions: { LIKE: 7 },
      },
    ],
  },
  {
    title: "DEXA scan after 12 weeks of tesa — body comp results",
    body: "Not bloodwork per se but the body comp side of the conversation usually lives here.\n\n12 weeks tesamorelin 2mg/day. Same DEXA machine, same tech, morning fasted both scans.\n\nBaseline:\n- Total mass: 198.4 lb\n- Lean mass: 152.1 lb\n- Fat mass: 42.3 lb (21.3% BF)\n- VAT: 118 cm^2\n\nWeek 12:\n- Total mass: 196.8 lb\n- Lean mass: 155.4 lb\n- Fat mass: 38.1 lb (19.4% BF)\n- VAT: 94 cm^2\n\nLBM +3.3 lb, fat -4.2 lb, VAT -20% (the main thing tesa is approved for).\n\nIGF-1 went 204 -> 296. Did not do anything special with training or diet (maintenance cals, same lift program). This seems like a solid response?",
    author: "dexa_devotee",
    daysAgo: 50,
    views: 3420,
    reactions: { USEFUL: 42, LIKE: 18, THANKS: 11 },
    replies: [
      {
        author: "hexaclinic",
        body: "That's a textbook tesa response for a 12-week cycle. The VAT number is the headline — 118 -> 94 is a 20% drop in visceral fat, which is what tesa is literally FDA-approved to do in HIV lipodystrophy.",
        daysAgo: 50,
        reactions: { USEFUL: 26, AGREE: 12 },
      },
      {
        author: "cbc_cmp",
        body: "3.3 lb LBM gain without training changes, at maintenance cals, in 12 weeks — that's on the high end of what people see. Your IGF-1 response (+90) is solid-respondent territory.",
        daysAgo: 50,
        reactions: { USEFUL: 19 },
      },
      {
        author: "dr_doubt",
        body: "Reminder that DEXA has its own CV — lean mass precision is typically ~1.5-2% within person on repeat scans. So 3.3 lb gain on 152 base is ~2.2%, right at the detection threshold. Your fat loss is larger and more clearly real.\n\nStill a positive scan, just don't frame the LBM number as 'definitely real'.",
        daysAgo: 49,
        reactions: { AGREE: 18, USEFUL: 12 },
      },
      {
        author: "the_stats_guy",
        body: "VAT CV is higher than total fat mass CV too — somewhere around 4-6% on repeat scan. 118 -> 94 is still well outside CV so that part's solid.",
        daysAgo: 49,
        reactions: { USEFUL: 14 },
      },
      {
        author: "dexa_devotee",
        body: "Good caveats. Fat + VAT are the ones I was more confident in. LBM I'll take with appropriate salt.",
        daysAgo: 48,
        reactions: { AGREE: 8 },
      },
      {
        author: "protocolpilot",
        body: "Did you track bloodwork alongside? Fasting glucose, a1c, lipids? Tesa at 2mg can move insulin sensitivity meaningfully and the body comp gain is less interesting if the metabolic cost is high.",
        daysAgo: 47,
        reactions: { USEFUL: 17, AGREE: 6 },
      },
      {
        author: "dexa_devotee",
        body: "Yeah — a1c 5.3 -> 5.4, fasting glucose 88 -> 91, fasting insulin 5.9 -> 7.2. Directional creep, nothing wild.",
        daysAgo: 47,
        reactions: { USEFUL: 11 },
      },
      {
        author: "igf_curve",
        body: "That's the classic tesa tradeoff — great body comp and IGF-1 in exchange for a little insulin creep. As long as you're cycling off it stays manageable.",
        daysAgo: 45,
        reactions: { AGREE: 12 },
      },
    ],
  },
  {
    title: "Fasting insulin and HOMA-IR on CJC/Ipa",
    body: "4 months of CJC-NoDAC 100mcg + Ipa 300mcg, 5x/week. Tracking fasting insulin monthly.\n\n- Month 0: insulin 4.8, glucose 86, HOMA-IR 1.02\n- Month 1: insulin 5.2, glucose 88, HOMA-IR 1.13\n- Month 2: insulin 6.1, glucose 90, HOMA-IR 1.36\n- Month 3: insulin 7.4, glucose 92, HOMA-IR 1.68\n- Month 4: insulin 7.8, glucose 93, HOMA-IR 1.79\n\nLooks like it's plateauing around HOMA-IR 1.8. IGF-1 went 187 -> 269 which I'm happy with.\n\nQuestion: do I ride it out another 2 months (it seems to be stabilizing) or cycle off? No HbA1c yet — pulling it next week.",
    author: "cbc_cmp",
    daysAgo: 21,
    views: 2010,
    reactions: { USEFUL: 24, LIKE: 8 },
    replies: [
      {
        author: "protocolwonk",
        body: "The plateau is real — fasting insulin tends to hit a new equilibrium 3-4 months into a GHRP stack and stabilize unless you're pushing the dose. If HbA1c stays under 5.5 I'd ride it another 2 months.\n\nIf a1c crosses 5.6 I'd cycle off.",
        daysAgo: 21,
        reactions: { USEFUL: 22, AGREE: 11 },
      },
      {
        author: "stackbuilder",
        body: "Same shape on my data last year. Insulin plateaued at ~8, HOMA-IR ~1.85, stayed there for 3 more months. Cycled off for 6 weeks, insulin dropped back to 5.1.\n\nThe plateau is not a slow-motion metabolic breakdown, it's the new homeostasis.",
        daysAgo: 21,
        reactions: { USEFUL: 18, AGREE: 9 },
      },
      {
        author: "hba1c_watch",
        body: "a1c is really the deciding vote. Get that reading and retest again at month 6. If it's stable under 5.5 you're fine.",
        daysAgo: 20,
        reactions: { AGREE: 14, USEFUL: 7 },
      },
      {
        author: "the_stats_guy",
        body: "Nice clean monotonic dataset. Your month-0 to month-4 jump is clearly outside CV (which is ~8-12% for fasting insulin at low baselines). Real signal, not noise.",
        daysAgo: 19,
        reactions: { USEFUL: 13 },
      },
      {
        author: "igf_curve",
        body: "Your IGF-1 response + modest insulin creep is basically a green light. Plenty of people trade a HOMA-IR of 1.0 for 1.8 in exchange for IGF-1 +80. That's a reasonable trade if you're tracking and not just flying blind.",
        daysAgo: 18,
        reactions: { AGREE: 11, USEFUL: 6 },
      },
      {
        author: "cbc_cmp",
        body: "a1c back — 5.2 -> 5.4. Going to ride it another 6 weeks and retest.",
        daysAgo: 14,
        reactions: { LIKE: 12, THANKS: 4 },
      },
      {
        author: "dr_doubt",
        body: "Good call. Sane decision framework throughout this thread, honestly.",
        daysAgo: 13,
        reactions: { AGREE: 9 },
      },
    ],
  },
  {
    title: "TSH moving on cutting cycle — context: down 18 lbs in 10 weeks",
    body: "Not sure if this is a peptide question, a caloric deficit question, or both, so posting here.\n\nOn tirz 5mg/week, 10 weeks in, down 18 lbs. Pulled thyroid labs.\n\nBaseline:\n- TSH: 1.8 mIU/L\n- Free T4: 1.3 ng/dL\n- Free T3: 3.2 pg/mL\n\nWeek 10:\n- TSH: 3.1 mIU/L\n- Free T4: 1.2\n- Free T3: 2.7\n\nTSH almost doubled, Free T3 dropped 16%. Still 'in range' but directionally this is the classic 'cutting phase thyroid suppression' shape.\n\nIs this the GLP-1 or the deficit? And is a TSH of 3.1 something to act on or just ride out?",
    author: "slow_lose",
    daysAgo: 27,
    views: 2210,
    reactions: { USEFUL: 24, LIKE: 6 },
    replies: [
      {
        author: "glp1_doctor_pt",
        body: "That's the deficit, not the GLP-1. Prolonged caloric deficit + significant weight loss reliably nudges TSH up and pulls T3 down. It's the body's adaptive response — 'less fuel coming in, lower thyroid output'. Happens independent of any drug.\n\nTSH 3.1 is nothing to act on. Free T4 is fine. It'll normalize within a few months of maintenance cals.",
        daysAgo: 27,
        reactions: { USEFUL: 28, AGREE: 14 },
      },
      {
        author: "tirzepatide_tim",
        body: "Seconded. My TSH went 1.4 -> 2.9 during my biggest loss phase. Came back to 1.6 after 6 weeks of maintenance.",
        daysAgo: 27,
        reactions: { AGREE: 12, USEFUL: 6 },
      },
      {
        author: "cbc_cmp",
        body: "Free T3 is the meaningful one here and 3.2 -> 2.7 is a real drop (CV ~5-7%). But it's still well inside the reference range. Symptoms (temperature, bowel, energy) more than the number should drive any action.",
        daysAgo: 26,
        reactions: { USEFUL: 18, AGREE: 9 },
      },
      {
        author: "slow_lose",
        body: "I'm a little colder in the mornings than usual but otherwise feel good. Energy fine, mood fine.",
        daysAgo: 26,
      },
      {
        author: "macrosguru",
        body: "Cold feet mid-cut is basically the body saying 'thank you for noticing, please eat'. Normal adaptation. Doesn't mean you need T3 or anything crazy.",
        daysAgo: 25,
        reactions: { FUNNY: 18, AGREE: 9 },
      },
      {
        author: "dr_doubt",
        body: "The 'do I need thyroid meds' bar on lab values alone is TSH >10 or Free T4 below range, generally. You're nowhere near either. Ride it out.",
        daysAgo: 24,
        reactions: { USEFUL: 17, AGREE: 11 },
      },
      {
        author: "slow_lose",
        body: "Appreciated. Going to keep going and retest at maintenance after the cut ends.",
        daysAgo: 23,
        reactions: { LIKE: 7 },
      },
    ],
  },

  // ==========================================================================
  // QUIET THREADS (8 — 2-5 replies each)
  // ==========================================================================
  {
    title: "Which labs should I actually pull before my first cycle?",
    body: "Feeling overwhelmed by the pinned list. First-ever peptide cycle (BPC-157 for a nagging shoulder, nothing wild). Do I really need the full Tier 1 panel, or is there a minimum?",
    author: "bpc_baby",
    daysAgo: 12,
    views: 820,
    reactions: { USEFUL: 14, LIKE: 6 },
    replies: [
      {
        author: "lucidverse",
        body: "Honestly for BPC alone, I'd pull a basic CBC, CMP, and lipid panel. $40-60 at any discount lab. That's enough for a pre-cycle baseline given how little BPC interacts with systemic metabolism.\n\nIf you were doing GH or GLP-1, full Tier 1. BPC specifically is one of the lowest-risk peptides from a systemic-labs perspective.",
        daysAgo: 12,
        reactions: { USEFUL: 19, THANKS: 8 },
      },
      {
        author: "cbc_cmp",
        body: "Agreed. Minimum viable: CBC, CMP, lipid. Add HbA1c if you want a metabolic baseline for future cycles. Total cost cash-pay via Ulta/Marek: under $60.",
        daysAgo: 12,
        reactions: { USEFUL: 14 },
      },
      {
        author: "bpc_baby",
        body: "Okay, that's much more manageable. Thanks.",
        daysAgo: 11,
        reactions: { THANKS: 5 },
      },
      {
        author: "first_vial",
        body: "I did the same minimal 3-panel before my first BPC cycle. More than enough.",
        daysAgo: 10,
        reactions: { AGREE: 6 },
      },
    ],
  },
  {
    title: "Budget labs — what's the minimum viable panel?",
    body: "Cash-pay, no insurance angle here. What's the absolute cheapest sensible panel for someone on GLP-1s?",
    author: "cautious_ox",
    daysAgo: 18,
    views: 1040,
    reactions: { USEFUL: 18 },
    replies: [
      {
        author: "panel_maxer",
        body: "Ulta Lab Tests or Marek Health, cash pay:\n- CBC: ~$18\n- CMP: ~$22\n- Lipid + ApoB: ~$30\n- HbA1c: ~$20\n- Fasting insulin: ~$28\n\nTotal: ~$118. That's your 'minimum viable GLP-1 panel'. Pull once at baseline, once at ~12 weeks, once at 24 weeks. Under $400 for a year of solid tracking.",
        daysAgo: 18,
        reactions: { USEFUL: 28, THANKS: 14 },
      },
      {
        author: "sema_saturday",
        body: "Great breakdown. I'd add Lp(a) as a ONE-TIME pull ($22-ish) since it's genetic. You do it once in your life and you know for good.",
        daysAgo: 18,
        reactions: { USEFUL: 16, AGREE: 7 },
      },
      {
        author: "cautious_ox",
        body: "Perfect, this is exactly what I needed. Thank you.",
        daysAgo: 17,
        reactions: { THANKS: 6 },
      },
      {
        author: "showmethestudy",
        body: "One caveat — 'cheap' labs use the same assays and LabCorp/Quest facilities as the expensive ones. You're not trading accuracy for price, you're trading doctor-consultation-time for price.",
        daysAgo: 16,
        reactions: { USEFUL: 12, AGREE: 5 },
      },
    ],
  },
  {
    title: "IGFBP-3 — do I really need to pull it every time?",
    body: "Running GH secretagogues and pulling IGF-1 quarterly. IGFBP-3 adds ~$25 each time. Is it adding real information or can I skip it?",
    author: "questions_mode",
    daysAgo: 31,
    views: 680,
    reactions: { USEFUL: 11 },
    replies: [
      {
        author: "igf_curve",
        body: "Honestly for most people pulling IGF-1 quarterly, IGFBP-3 is redundant. The IGF-1/IGFBP-3 ratio is mostly informative at cycle start and at any point you see unexpected side effects (edema, CTS, joint pain) to check if free IGF-1 is running ahead of the binding protein.\n\nPull it at cycle start + once at midpoint + if you feel weird. Otherwise skip.",
        daysAgo: 31,
        reactions: { USEFUL: 17, THANKS: 6 },
      },
      {
        author: "protocolpilot",
        body: "Agreed. Baseline + one midpoint check is plenty.",
        daysAgo: 30,
        reactions: { AGREE: 8 },
      },
      {
        author: "questions_mode",
        body: "Thanks, saves $50/year.",
        daysAgo: 30,
        reactions: { THANKS: 4 },
      },
    ],
  },
  {
    title: "Am I reading this cortisol wrong?",
    body: "AM fasted cortisol came back 22.4 mcg/dL. Lab ref 4.3-22.4. So literally at the top of the range.\n\nI'm running ipamorelin 300mcg bid for 10 weeks. No sleep issues, no anxiety spikes. But 22.4 right at the ceiling is a little worrying. Is this the ipa?",
    author: "reading_mode",
    daysAgo: 19,
    views: 920,
    reactions: { LIKE: 5 },
    replies: [
      {
        author: "cbc_cmp",
        body: "Ipamorelin is specifically designed to NOT bump cortisol — that's its whole selling point vs GHRP-6 and hexarelin. A reading at the top of the reference range on ipa is almost certainly NOT the drug.\n\nWhat time exactly was the draw? AM cortisol peaks 6-8am. A 6:30am draw will run 25-40% higher than an 8:30am draw.",
        daysAgo: 19,
        reactions: { USEFUL: 18, AGREE: 9 },
      },
      {
        author: "reading_mode",
        body: "6:45am. So that's probably most of it.",
        daysAgo: 19,
      },
      {
        author: "dr_doubt",
        body: "Yeah. Cortisol CV is also ~10-15% on top of the diurnal variation. A 22.4 at 6:45am is basically 'normal healthy person who woke up on time'.",
        daysAgo: 18,
        reactions: { AGREE: 12, USEFUL: 6 },
      },
      {
        author: "reading_mode",
        body: "Okay, panic averted. Thanks.",
        daysAgo: 18,
        reactions: { THANKS: 4 },
      },
    ],
  },
  {
    title: "Ferritin dropped during a long BPC cycle — coincidence?",
    body: "Pulled a random CBC mid-cycle. Ferritin went 142 -> 87 ng/mL over 10 weeks on BPC-157. Hgb/Hct unchanged. No heavy periods (male), no GI bleeding, not donating blood.\n\nIron panel otherwise fine. Training and diet unchanged.\n\nAnyone else seen ferritin drop on long BPC courses?",
    author: "labrat_ish",
    daysAgo: 22,
    views: 810,
    reactions: { USEFUL: 12, LIKE: 4 },
    replies: [
      {
        author: "panel_maxer",
        body: "Ferritin is an acute-phase reactant — it goes UP with inflammation and DOWN when inflammation resolves. If BPC is reducing your systemic inflammation, ferritin coming down from 142 to 87 might not be 'iron stores depleted', it might be 'inflammation-driven ferritin elevation has resolved'.\n\nPull iron, TIBC, transferrin saturation. If TSAT is fine and iron is fine, you're just seeing normalized ferritin.",
        daysAgo: 22,
        reactions: { USEFUL: 22, AGREE: 10, THANKS: 7 },
      },
      {
        author: "crp_cassandra",
        body: "^ this is exactly right. Also pull hs-CRP. If CRP dropped alongside ferritin, the 'inflammation resolution' hypothesis is basically confirmed.",
        daysAgo: 21,
        reactions: { USEFUL: 14, AGREE: 8 },
      },
      {
        author: "labrat_ish",
        body: "TSAT was 34% (in range), serum iron 98. hs-CRP actually went 2.2 -> 1.1 over the same window. So this is exactly the story you're describing. Whoa.",
        daysAgo: 19,
        reactions: { USEFUL: 18, THANKS: 11 },
      },
      {
        author: "panel_maxer",
        body: "Textbook. Great case study, actually.",
        daysAgo: 19,
        reactions: { LIKE: 9 },
      },
    ],
  },
  {
    title: "SHBG crashed on tirz — is that a problem?",
    body: "Baseline SHBG was 42 nmol/L. After 14 weeks on tirz 10mg/week, -28 lbs, SHBG is 24.\n\nTotal T unchanged (684 -> 702). Free T is higher now of course (lower SHBG + same total). Feel fine.\n\nIs the crashed SHBG bad on its own, or is it just 'better insulin sensitivity -> lower SHBG' which is the expected story?",
    author: "slow_titrate",
    daysAgo: 16,
    views: 740,
    reactions: { USEFUL: 9 },
    replies: [
      {
        author: "cbc_cmp",
        body: "Lower SHBG on improved insulin sensitivity is the expected story. You're seeing the metabolic improvement, not something bad.\n\nThat said, SHBG 24 is on the lower end. If you feel fine, Free T is fine, estradiol in range, no acne/irritability — you're good. The number by itself isn't worth acting on.",
        daysAgo: 16,
        reactions: { USEFUL: 16, AGREE: 7 },
      },
      {
        author: "dr_doubt",
        body: "SHBG CV is ~8-12% within person. 42 -> 24 is clearly outside noise so it's a real shift, but as cbc said, it's a predictable shift in a direction that usually means 'metabolism is healthier'.",
        daysAgo: 16,
        reactions: { USEFUL: 12 },
      },
      {
        author: "slow_titrate",
        body: "Alright. Filing under 'expected, not a problem'.",
        daysAgo: 15,
        reactions: { THANKS: 4 },
      },
    ],
  },
  {
    title: "How often are people actually retesting?",
    body: "Genuine logistics question — how often do you pull labs during a cycle? Every 4 weeks feels expensive, every 12 weeks feels too spaced out.",
    author: "fresh_cycle",
    daysAgo: 35,
    views: 1120,
    reactions: { USEFUL: 14 },
    replies: [
      {
        author: "protocolpilot",
        body: "My personal cadence: baseline + week 8 (cheap panel, basically the metabolic subset) + week 16 (full panel). That's 2 retests per cycle, ~$200 total, and you catch any creep early enough to adjust.",
        daysAgo: 35,
        reactions: { USEFUL: 19, AGREE: 8 },
      },
      {
        author: "cbc_cmp",
        body: "Same general approach. The week 8 'metabolic-only' pull (glucose, insulin, a1c, lipids) is the most cost-effective early warning check.",
        daysAgo: 34,
        reactions: { AGREE: 11 },
      },
      {
        author: "dr_doubt",
        body: "If you're running something novel or high-dose, 4-week retests are worth it for the first cycle to figure out YOUR response curve. Established protocols that you've already characterized — 8 and 16 is fine.",
        daysAgo: 34,
        reactions: { USEFUL: 14, AGREE: 6 },
      },
      {
        author: "fresh_cycle",
        body: "Thanks, that's a reasonable framework.",
        daysAgo: 33,
        reactions: { THANKS: 4 },
      },
    ],
  },
  {
    title: "GGT worth pulling or overkill?",
    body: "I've seen a few people mention GGT alongside ALT/AST. My standard panel doesn't include it and the add-on is ~$15. Worth it for a general peptide user?",
    author: "new2peptides",
    daysAgo: 26,
    views: 590,
    reactions: { LIKE: 4 },
    replies: [
      {
        author: "panel_maxer",
        body: "GGT is cheap informational value. It catches things ALT/AST miss (biliary issues, alcohol-related changes, some medication effects). Not strictly necessary but worth the $15 once a year. In your routine 2-3x/year pulls, I'd include it in one of them.",
        daysAgo: 26,
        reactions: { USEFUL: 13, AGREE: 6 },
      },
      {
        author: "cbc_cmp",
        body: "I include GGT in every LFT panel I run. The extra number has caught something useful maybe 1 in 15 panels. Good insurance for the price.",
        daysAgo: 25,
        reactions: { USEFUL: 9, AGREE: 4 },
      },
      {
        author: "new2peptides",
        body: "Sold. Adding it next time.",
        daysAgo: 25,
        reactions: { THANKS: 3 },
      },
    ],
  },
];
