import type { SeedThread } from "../types";

// ============================================================
// BPC-157 SUB-FORUM — 14 threads
// 2 popular (15-25 replies), 5 active (6-12 replies), 7 quiet (2-5 replies)
// ============================================================

export const THREADS_BPC157: SeedThread[] = [
  // --------- POPULAR ---------
  {
    title: "Local vs systemic BPC-157 — the 'right next to the injury vs belly fat' debate, one more time",
    body: "This comes up every month and the answer is always 'it depends,' which is unsatisfying. Let me put a stake in the ground and argue a position.\n\nBPC-157 is a 15aa fragment of a protein from gastric juice. The animal work that everyone points to is injected IP or IM in rodents — which, scaled to a 180lb human, is effectively systemic. None of the rodent tendon/ligament studies are demonstrating that a pin adjacent to the injury outperforms a pin in the flank.\n\nMy claim: **local is a convenience artifact, not a mechanism story**. If BPC reaches circulation, it reaches the injury. If it doesn't reach circulation (e.g. degrades at the injection site), you're just creating a local depot that slowly releases into systemic anyway.\n\nCounter-argument I've heard: 'the peptide degrades in circulation within minutes so local is the only way to get meaningful tissue concentration.' This is partly true for the half-life claim but ignores that the tissue effects show up even from oral administration in rodents, where bioavailability is terrible. Something about BPC seems to punch above its weight pharmacokinetically.\n\nSo I dose in the belly fat. 500mcg Sub-Q, once daily, done. Rotate sites. Haven't found a case where 'oh you should have pinned it in your shoulder' changed an outcome.\n\nAnyone have a reason to change my mind that isn't 'bro science guy on YouTube said'?",
    author: "hexaclinic",
    daysAgo: 62,
    views: 5840,
    reactions: { LIKE: 14, USEFUL: 13, AGREE: 9, THANKS: 5 },
    replies: [
      { author: "tendon_theory", body: "I've run it both ways on the same injury type (medial epi, twice, two years apart). Local felt faster the second time but I also had better sleep, better diet, and started rehab two weeks sooner. So I agree with you — the N=1 variance drowns the signal.", daysAgo: 61, reactions: { AGREE: 10, USEFUL: 5 } },
      { author: "shoulder_spring", body: "Counterpoint: for a superficial injury like lateral epi or patellar tendon, 'local' and 'systemic' aren't really different because the pin goes Sub-Q over the tissue anyway. For something deep like a labrum or meniscus, 'local' means intra-articular which most people shouldn't be doing at home. So the debate kind of collapses.", daysAgo: 61, reactions: { USEFUL: 8, AGREE: 7 } },
      { author: "rotator_rebuild", body: "@shoulder_spring this is the best take in the thread. 'Local' is a spectrum and for most home-pin injuries it's just Sub-Q over the area. That's not the same as the targeted delivery people imagine.", daysAgo: 60, reactions: { AGREE: 9, LIKE: 3 } },
      { author: "nopain_noreign", body: "I'll defend local. Achilles — five years of on-off tendinopathy. Systemic BPC did nothing over 8 weeks. Sub-Q pin 2 inches proximal to the insertion, daily for 4 weeks — pain dropped from 5/10 to 1/10. Same vial, same dose, different site, different outcome.", daysAgo: 59, reactions: { AGREE: 6, USEFUL: 7, LIKE: 4 } },
      { author: "hexaclinic", body: "@nopain_noreign that's exactly the kind of anecdote I can't dismiss. One question: was anything else different? Footwear, load management, heel-raise protocol?", daysAgo: 59, reactions: { LIKE: 3 } },
      { author: "nopain_noreign", body: "@hexaclinic heavy slow resistance stayed the same across both runs. So not perfectly controlled but the loading was similar. I can't rule it out but it's the cleanest comparison I have.", daysAgo: 58, reactions: { USEFUL: 5 } },
      { author: "showmethestudy", body: "The 'punches above its weight PK-wise' line is doing a lot of work here. The oral rodent data is Sikiric's lab almost exclusively. One lab, one model, one primary investigator. I'd hold that loosely until there's independent replication.", daysAgo: 58, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "dr_doubt", body: "Agree with @showmethestudy. The human injected BPC literature is effectively zero. Everything we do is extrapolation from a single rodent research line, decades old at this point. Doesn't mean wrong, means uncertain.", daysAgo: 57, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "acl_again", body: "Pre-surgery ACL. Planning Sub-Q abdomen because I can't pin near a joint that's about to be cut open. Any reason to switch to local once the incisions heal?", daysAgo: 56, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@acl_again no. The graft site isn't accessible for safe pinning and the rest of the knee you shouldn't be going near. Abdomen is fine.", daysAgo: 56, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "meniscus_mgmt", body: "I split the dose. 250mcg in the flank systemic, 250mcg Sub-Q over the affected knee. Makes me feel better. Placebo, probably, but cheap placebo.", daysAgo: 55, reactions: { FUNNY: 6, LIKE: 3 } },
      { author: "joint_hunter", body: "Question from a newbie reading along — when people say 'over the injury' Sub-Q, how close is close enough? Within a few inches? Same muscle group?", daysAgo: 54, reactions: { LIKE: 2 } },
      { author: "tendon_theory", body: "@joint_hunter within a few inches of the skin over the tissue is what most people mean. Same muscle group is usually fine. You're not doing surgery, just creating a Sub-Q depot near the target.", daysAgo: 54, reactions: { USEFUL: 5, THANKS: 3 } },
      { author: "citation_required", body: "For this thread to actually resolve we'd need a head-to-head at a matched dose on a matched injury. That study doesn't exist and probably won't. We're arguing vibes.", daysAgo: 53, reactions: { AGREE: 7, FUNNY: 3 } },
      { author: "pallet_jack", body: "For what it's worth, deep abdominal muscle tear 3 years ago, pinned in the opposite flank because the target area was too painful to touch. Healed on a faster-than-expected timeline. So systemic worked when local wasn't even an option.", daysAgo: 51, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "bpc_baby", body: "I keep seeing 'flank' — is that just the side of the torso above the hip? Sorry if this is obvious.", daysAgo: 49, reactions: { LIKE: 1 } },
      { author: "hexaclinic", body: "@bpc_baby yes, the soft area between the ribs and the hip, on the side. Pinch a bit of fat, 29g insulin pin, Sub-Q. Fine site.", daysAgo: 49, reactions: { THANKS: 4, USEFUL: 3 } },
      { author: "kineticdrift", body: "Gonna toss in: there's no harm in local for a superficial injury. It costs nothing extra (same volume, different site) and it at least feels like you're aiming. I'd rather have the user engaged with the protocol than abstracted away from it.", daysAgo: 47, reactions: { AGREE: 6, LIKE: 4 } },
      { author: "hexaclinic", body: "@kineticdrift fair. The psychology of local is underrated. If it makes someone stick to the protocol, it's pulling weight regardless of the PK story.", daysAgo: 46, reactions: { AGREE: 8, LIKE: 4, USEFUL: 3 } },
    ],
  },

  {
    title: "First-time BPC-157 — what every newbie actually needs to know (not the YouTube version)",
    body: "Seeing 'starting BPC next week, what should I know?' twice a week. Writing this once so I can link it.\n\n**What BPC-157 actually is:** a synthetic 15 amino acid fragment derived from a protein found in human gastric juice. That's it. It's not a miracle, it's not a hormone, it doesn't build muscle, it doesn't burn fat. The marketing around it is bonkers relative to the actual human evidence.\n\n**What it's used for in the community:** soft tissue healing — tendons, ligaments, gut lining, muscle strains. Rodent data is decent for these applications, human data is essentially anecdote + some oral GI studies.\n\n**Typical dose ranges:** 250mcg to 500mcg Sub-Q, once or twice daily. Some people go higher, most don't find benefit above that range.\n\n**Route:** Sub-Q insulin pin, 29g or 31g, half-inch. You do not need IM. You do not need intra-articular (and frankly most of you should not be doing intra-articular).\n\n**Reconstitution:** bacteriostatic water. A 5mg vial with 2mL of BAC gives you 250mcg per 10 units on an insulin syringe, 500mcg per 20 units. Do the math on your vial before you pin anything. Fridge after reconstitution, use within ~30 days.\n\n**Cycle length:** most people run 4-8 weeks and then stop. There's no established reason to run it indefinitely, and there's also no strong evidence you shouldn't. Default: 6 weeks on, 2-4 weeks off, reassess.\n\n**What you should NOT expect:** an immediate miracle. Tendon healing is a weeks-to-months process regardless of what you pin. If your pain is gone in 3 days, it was never going to be a BPC-scale problem.\n\n**What you should expect:** incremental. If something that was hurting for 6 months is 30% better at week 4, that's a win.\n\nAsk questions below. No dumb ones, we've all been the newbie.",
    author: "cardinal_rule",
    daysAgo: 95,
    pinned: false,
    views: 7230,
    reactions: { LIKE: 18, USEFUL: 22, THANKS: 15, AGREE: 6 },
    replies: [
      { author: "bpc_baby", body: "This should be the first thing new members see. Literally made this account to ask a BPC question and half of them are already answered here.", daysAgo: 94, reactions: { LIKE: 6, THANKS: 4 } },
      { author: "first_vial", body: "The 'do the math on your vial' line — can you actually walk through how someone should do it? I have a 10mg vial and I don't know how much BAC to use.", daysAgo: 94, reactions: { LIKE: 3 } },
      { author: "cardinal_rule", body: "@first_vial sure. 10mg vial + 2mL BAC = 5mg/mL. On a U-100 insulin syringe, 1mL = 100 units. So 100 units = 5mg = 5000mcg. 10 units = 500mcg. 5 units = 250mcg. If you want cleaner numbers use 2.5mL BAC so 10 units = 400mcg, or 5mL BAC so 10 units = 200mcg. Pick the dilution that makes your dose fall on a whole unit number.", daysAgo: 94, reactions: { USEFUL: 11, THANKS: 7 } },
      { author: "syringe_shy", body: "Sub-Q intimidates me more than it probably should. Is there a practical guide somewhere to actually doing the pin?", daysAgo: 93, reactions: { LIKE: 2 } },
      { author: "joint_hunter", body: "@syringe_shy pinch an inch of belly fat, insert 29g insulin pin at 45-90 degrees all the way to the hub, aspirate if you want (some skip for Sub-Q), push slow, pull out, dab with alcohol pad. Whole thing takes 10 seconds once you've done it twice. Harder mentally than physically.", daysAgo: 93, reactions: { USEFUL: 8, THANKS: 5 } },
      { author: "reading_mode", body: "The 'not a miracle' framing is refreshing. Everything on YouTube makes it sound like it regrows limbs.", daysAgo: 92, reactions: { AGREE: 9, FUNNY: 6 } },
      { author: "questions_mode", body: "Is there a reason to pick AM vs PM for the daily dose? Or does it not matter?", daysAgo: 91, reactions: { LIKE: 1 } },
      { author: "cardinal_rule", body: "@questions_mode probably doesn't matter. The peptide doesn't have a circadian story as far as I know. Pick a time you'll actually remember to pin. Consistency > timing.", daysAgo: 91, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "curious_catL", body: "Should I take anything alongside BPC to 'boost' it? Seeing a lot of TB-500 stack recommendations for new users.", daysAgo: 90, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@curious_catL run BPC alone first. If you stack two compounds and you get a result, you don't know which one did it. If you get a side effect, same problem. Add TB-500 on your second cycle if you have a specific reason.", daysAgo: 90, reactions: { AGREE: 11, USEFUL: 7, LIKE: 3 } },
      { author: "new2peptides", body: "Saved, thank you. One question — what does 'reassess' mean at the end of a cycle? How do I know if it worked?", daysAgo: 88, reactions: { LIKE: 2 } },
      { author: "cardinal_rule", body: "@new2peptides baseline before you start. Write down pain (0-10), range of motion, functional test (can you do X movement, how many reps, how much weight). Check the same numbers at end of cycle. If nothing moved, BPC isn't your answer and you should stop spending money on it.", daysAgo: 88, reactions: { USEFUL: 12, THANKS: 6, AGREE: 4 } },
      { author: "vintage_lame", body: "Respect for the 'it's not a hormone' line. I thought it was for a long time and nobody corrected me.", daysAgo: 85, reactions: { FUNNY: 5, LIKE: 3 } },
      { author: "bac_water_noob", body: "Dumb question — does the BAC water have to be BAC specifically? Could I use regular saline?", daysAgo: 83, reactions: { LIKE: 1 } },
      { author: "cardinal_rule", body: "@bac_water_noob BAC water has 0.9% benzyl alcohol which prevents bacterial growth once the vial is pierced. Regular saline doesn't. If you reconstitute with saline you get maybe 24-48 hours before contamination risk is real. Use BAC.", daysAgo: 83, reactions: { USEFUL: 9, THANKS: 4 } },
      { author: "citation_required", body: "Would appreciate a single line in this post stating that human RCT evidence is essentially zero. Newbies are going to read the rest and assume the community consensus is 'this definitely works.'", daysAgo: 80, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "cardinal_rule", body: "@citation_required added to the edit queue. Fair.", daysAgo: 80, reactions: { AGREE: 5, LIKE: 3 } },
      { author: "fresh_cycle", body: "First pin of my life three days ago thanks to this post. It's in me. I'm alive. Thank you.", daysAgo: 12, reactions: { FUNNY: 11, LIKE: 7 } },
    ],
  },

  // --------- ACTIVE (6-12 replies) ---------
  {
    title: "Oral BPC-157 capsules — worth the money or just expensive poop?",
    body: "Saw a vendor pushing 500mcg enteric-coated BPC capsules at basically 4x the price-per-dose of injectable. Their pitch: 'BPC-157 was discovered in gastric juice, oral is the native route.'\n\nThe counter is that the gastric juice protein is a much larger molecule and the 15aa fragment is synthetic. 'Discovered in gastric juice' and 'oral bioavailability is good' are not the same claim.\n\nThat said — the Sikiric oral rodent data does show systemic effects (reduced inflammation distal from the gut). So something is getting through, or signaling through, even from an oral route.\n\nMy specific question: for a non-GI target (shoulder, elbow, tendon) — is there any reason to prefer oral over Sub-Q? Price alone would push me toward injection. But I'm curious if anyone has a real reason.",
    author: "reggae_fiend",
    daysAgo: 41,
    views: 2140,
    reactions: { LIKE: 6, USEFUL: 5, AGREE: 3 },
    replies: [
      { author: "dr_doubt", body: "The honest answer is nobody knows. The oral rodent data is suggestive but it's all one lab, and the dose equivalency to a human oral capsule is not established. I'd use injectable for non-GI targets and reserve oral for gut-specific protocols.", daysAgo: 40, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "hexaclinic", body: "For a shoulder or elbow? No. Sub-Q, cheaper, you know what dose is actually landing. Oral is a novelty priced like a premium product.", daysAgo: 40, reactions: { AGREE: 7, LIKE: 3 } },
      { author: "showmethestudy", body: "Vendors are leaning hard on the 'native route' framing. It's marketing. A fragment of a protein is not a protein. The fragment's oral fate is an open question even in rodents.", daysAgo: 39, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "tendon_theory", body: "I did a 4-week oral run for curiosity. 500mcg capsules, 2x daily. Zero noticeable effect on my elbow. Switched to Sub-Q same dose and got the usual response within 2 weeks. Not a controlled experiment, but informative.", daysAgo: 38, reactions: { USEFUL: 7, AGREE: 3 } },
      { author: "quietstorm", body: "The one case I'd make for oral: needle phobia so bad you won't pin at all. Oral might be better than nothing. That's a short list.", daysAgo: 37, reactions: { AGREE: 5, USEFUL: 3, LIKE: 2 } },
      { author: "protocolwonk", body: "The price delta alone kills it for me. 4x cost for a route of administration with worse characterized bioavailability? Hard pass.", daysAgo: 36, reactions: { AGREE: 6 } },
      { author: "reggae_fiend", body: "Consensus seems to be 'injectable for joints/tendons, maybe oral for gut.' Appreciate the input. Saving the money for a second vial.", daysAgo: 35, reactions: { LIKE: 4, AGREE: 3 } },
      { author: "citation_required", body: "Would be interested in a blind head-to-head but nobody's going to run it. The economics only work for the vendor selling the premium format.", daysAgo: 33, reactions: { AGREE: 4 } },
    ],
  },

  {
    title: "BPC-157 for gut issues — here's the protocol that actually moved the needle for me",
    body: "Chronic mild gastritis plus suspected low-grade IBD-adjacent stuff for about 3 years. GI doc did scopes, nothing dramatic on imaging, just 'eat better, manage stress, here's a PPI.' PPIs half-helped, the side effect profile long-term was not something I wanted.\n\nRan BPC-157 oral for 6 weeks specifically for this. Not Sub-Q. Gut application is the one scenario where the oral route makes theoretical sense — the peptide is hitting the tissue on its way through.\n\n**Protocol:**\n- 500mcg in 2oz water, first thing AM, on empty stomach, wait 20 min before eating\n- 250mcg same route pre-bed\n- 6 weeks on\n- No other changes to diet, no new meds\n\n**Result:**\n- Upper GI burning: was 6-7/10 daily, went to 1-2/10 by week 3\n- Post-meal bloating: 70% reduction subjectively\n- Stool consistency: more consistent Bristol 3-4 vs prior Bristol 2-6 chaos\n- Slept better, probably because the abdominal discomfort wasn't waking me\n\n**At week 10 (4 weeks post-cycle):** symptoms about 30% rebounded. Not back to baseline but not gone.\n\nRunning a second cycle now, same dose. Curious if anyone else has a gut protocol that worked. The Sub-Q people in other threads can sit this one out — this is about oral for GI targeting.",
    author: "theoretic",
    daysAgo: 50,
    views: 2650,
    reactions: { LIKE: 9, USEFUL: 11, THANKS: 6, AGREE: 4 },
    replies: [
      { author: "pallet_jack", body: "Ran a similar protocol for H. pylori-induced gastritis after eradication therapy. 500mcg oral AM, 6 weeks. Helped. I can't attribute it cleanly because the antibiotics were doing the main work, but the symptomatic recovery was faster than my GI predicted.", daysAgo: 49, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "mothra", body: "The detail about dissolving in water vs swallowing capsule matters — oral absorption of a peptide in the upper GI is different depending on format. Did you try capsules first or go straight to dissolved?", daysAgo: 48, reactions: { LIKE: 3 } },
      { author: "theoretic", body: "@mothra straight to dissolved from an injectable vial. I used BAC water reconstituted concentration and just squirted 10 units into 2oz water. The thinking: let it coat the upper GI rather than hit a small intestine dissolution window from a capsule.", daysAgo: 48, reactions: { USEFUL: 6, THANKS: 3 } },
      { author: "stackbuilder", body: "Did you consider pairing with glutamine or zinc carnosine? Both have independent gut barrier support data.", daysAgo: 47, reactions: { LIKE: 2 } },
      { author: "theoretic", body: "@stackbuilder deliberately kept it clean to isolate the BPC signal. If I ran a third cycle I'd probably add zinc carnosine. Glutamine at high dose gave me headaches historically so I leave it out.", daysAgo: 47, reactions: { USEFUL: 4 } },
      { author: "curious_catL", body: "Does this work for acid reflux / GERD or is it a different mechanism? My issue is mostly LES-related, not inflammatory.", daysAgo: 46, reactions: { LIKE: 1 } },
      { author: "theoretic", body: "@curious_catL different mechanism probably. BPC has anti-inflammatory and barrier-support stories, not a sphincter tone story. I'd be surprised if it did much for pure mechanical reflux. Lifestyle + PPI + head-of-bed elevation is the better starting point there.", daysAgo: 46, reactions: { USEFUL: 7, AGREE: 3 } },
      { author: "cautious_ox", body: "Appreciate the honest '30% rebounded' detail. That kind of data is missing from most logs.", daysAgo: 44, reactions: { AGREE: 5, LIKE: 3 } },
      { author: "dr_doubt", body: "Good report. The rebound at week 10 is consistent with BPC acting as a symptomatic modulator rather than fixing an underlying driver. Worth considering what the driver is before you commit to perpetual cycles.", daysAgo: 43, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "theoretic", body: "@dr_doubt fair. I'm working on the driver side in parallel — diet, stress, sleep. BPC is a tool not a solution. Useful for breaking the symptom loop long enough to do the boring work.", daysAgo: 42, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "reading_mode", body: "Saving this one. Dealing with similar stuff and haven't pulled the trigger yet. The oral route makes it feel less daunting.", daysAgo: 38, reactions: { LIKE: 3 } },
    ],
  },

  {
    title: "Dosing frequency — does splitting BPC-157 twice daily actually do anything vs one bigger dose?",
    body: "Serious question I've never seen a clean answer to.\n\n500mcg once daily vs 250mcg twice daily — same total daily dose. The argument for splitting is 'short half-life, keep tissue levels more stable.' The argument against is 'the effects don't seem dose-proportional anyway, and more pins = more hassle.'\n\nWhat are people actually seeing? Is there a perceivable difference on the same compound, same injury, same person?",
    author: "protocolpilot",
    daysAgo: 33,
    views: 1890,
    reactions: { LIKE: 5, USEFUL: 4, AGREE: 2 },
    replies: [
      { author: "stackbuilder", body: "Ran both on medial epi (two different flareups, same elbow, same rehab). Felt the same. I've stopped splitting for convenience unless the total daily dose is >500mcg.", daysAgo: 32, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "cyclecraft", body: "The half-life argument sounds tidy but the half-life of BPC-157 in circulation is maybe 10-30 min depending on which paper you squint at. Splitting twice daily doesn't fix that — you'd need to pin every 2 hours. At which point you're treating the pharmacokinetic story as sacred when the pharmacodynamic story is what matters.", daysAgo: 32, reactions: { USEFUL: 9, AGREE: 7 } },
      { author: "hexaclinic", body: "@cyclecraft this is the right answer. The PK/PD disconnect for BPC is weird. Effects outlast plasma levels by a lot. Splitting doses is probably cargo cult unless you're chasing a specific subjective feel.", daysAgo: 31, reactions: { AGREE: 8, LIKE: 4, USEFUL: 3 } },
      { author: "slow_titrate", body: "I split. Not because I think it's pharmacokinetically optimal, but because I pin morning and evening anyway for a stack, and spreading the dose means I'm not carrying a fat midnight pin.", daysAgo: 30, reactions: { FUNNY: 4, LIKE: 2 } },
      { author: "tendon_theory", body: "Same compound, same total daily, I've never been able to feel a difference between once and twice daily. I'd pick whichever fits your day.", daysAgo: 29, reactions: { AGREE: 4, USEFUL: 2 } },
      { author: "protocolpilot", body: "Leaning once-daily based on this. Appreciate it.", daysAgo: 28, reactions: { LIKE: 3 } },
      { author: "protocolwonk", body: "One case for splitting — if you're at the higher end of dosing (like 750-1000mcg/day) some people report mild injection-site reaction with a single bigger bolus. Splitting helps there. For 500mcg or below, probably irrelevant.", daysAgo: 27, reactions: { USEFUL: 5, AGREE: 3 } },
    ],
  },

  {
    title: "Cycle length debate — 4 weeks, 8 weeks, or 'run it until it heals'?",
    body: "The forum seems split three ways on BPC cycling.\n\n- **4 weeks on / 2 off** — default recommendation in most newbie guides\n- **8 weeks continuous** — for active rehab\n- **Indefinite** — 'it's a peptide fragment of a gastric protein, why would I cycle it'\n\nThe 4-week camp seems to be driven by caution + analogy to other peptides that do need cycling for receptor downregulation reasons (which isn't BPC's mechanism). The 8-week camp is driven by the practical reality that soft tissue healing takes a while. The indefinite camp is rare but exists.\n\nWhat's the actual reasoning for cycling BPC specifically? It's not a secretagogue, not acting on a receptor pool that desensitizes in any way I've seen documented. Is the cycling thing just peptide-world default?",
    author: "cyclecraft",
    daysAgo: 58,
    views: 2980,
    reactions: { LIKE: 7, USEFUL: 6, AGREE: 3 },
    replies: [
      { author: "hexaclinic", body: "My honest take: the cycling guidance is precautionary, not mechanistic. No one has documented a clean reason BPC needs to be cycled. But we also don't have long-duration human safety data, so defaulting to 'run it as long as you need, then stop' is a conservative hedge.", daysAgo: 57, reactions: { AGREE: 10, USEFUL: 7 } },
      { author: "dr_doubt", body: "Seconded. The cycle length debate is an absence-of-evidence debate. We don't know what 52-week continuous BPC does in humans. We probably won't, because no one's funding that trial. The 4-8 week defaults are 'seems like a reasonable amount of exposure.'", daysAgo: 57, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "tendon_theory", body: "I run 6 weeks on, 2-4 off, and I reassess. If the tendon's still improving I'll run another 6. If it plateaued at week 4 I stop at 4. The calendar shouldn't drive it, the response should.", daysAgo: 56, reactions: { AGREE: 9, USEFUL: 6, LIKE: 3 } },
      { author: "quietstorm", body: "Chronic Achilles, 14 weeks continuous, no obvious problems, good result. N=1. Wouldn't recommend it as a default but it's a data point against 'must cycle at 4 weeks.'", daysAgo: 55, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "showmethestudy", body: "'We don't have long-term data' cuts both ways — you could also be accumulating subclinical issues we can't detect. The ALT/AST argument against long BPC runs is thin (the rodent data is actually protective for liver) but I'd still do labs periodically if you're going long.", daysAgo: 54, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "cyclecraft", body: "@showmethestudy yeah, the hepatoprotective rodent angle is the one thing that makes the 'indefinite' crowd feel okay. I'm still not running indefinite. 8 weeks max for me.", daysAgo: 54, reactions: { LIKE: 3 } },
      { author: "stackbuilder", body: "Default rule I use: if you need to run a peptide continuously to keep the effect, the effect probably isn't fixing the root cause. Cycling forces you to find out whether the compound is doing the work or the underlying problem actually got better.", daysAgo: 52, reactions: { AGREE: 12, USEFUL: 6, LIKE: 4 } },
      { author: "protocolpilot", body: "@stackbuilder this is the cleanest argument in the whole thread. Cycling as a diagnostic.", daysAgo: 51, reactions: { AGREE: 7, LIKE: 4 } },
      { author: "cycle_wrangler", body: "6 on, 4 off, as a default, is where I've landed after 3 years of doing this for various things. Long enough to tell if it's working, short enough to avoid the 'running it forever because I'm afraid to stop' trap.", daysAgo: 49, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "nopain_noreign", body: "Agree with 6-8 on, 2-4 off. I think the 4-week guides are just being super cautious for newbies and the real-world range is wider.", daysAgo: 47, reactions: { AGREE: 5 } },
    ],
  },

  {
    title: "BPC-157 and blood thinners — has anyone here actually been on both?",
    body: "Not looking for medical advice, I'll talk to my actual doctor. Looking for experience reports.\n\nOn apixaban (Eliquis) long-term after a DVT. Lifting shoulder flared badly 3 months ago and I've been eyeing BPC. The only thing I've seen referenced is Sikiric's angiogenesis work — the theory being BPC promotes vascular growth/repair, which in a patient on anticoagulation is not obviously bad but is also not obviously fine.\n\nHas anyone here actually run BPC while on a DOAC or warfarin? Any injection-site bruising, any hematology weirdness, any conversation with your prescriber about it?\n\nTo be clear — I understand the answer might be 'don't.' Just trying to hear real experience rather than internet theorizing.",
    author: "late_bloomer_m",
    daysAgo: 45,
    views: 1720,
    reactions: { LIKE: 3, USEFUL: 4 },
    replies: [
      { author: "dr_doubt", body: "Not your doctor. But: the main practical concern with BPC on any anticoagulant is injection-site hematoma from the pin itself, not the peptide. Sub-Q insulin pins leave pinpoint bleeds — on a DOAC those can be a bit more noticeable. Use 31g if you can, compress for a full minute post-pin, rotate sites aggressively.", daysAgo: 44, reactions: { USEFUL: 9, THANKS: 4, AGREE: 3 } },
      { author: "hexaclinic", body: "Ran BPC for 6 weeks while on apixaban post-PE. No issues. My hematologist's position was basically 'I don't know what BPC does, but I don't see a mechanistic reason it would interact with apixaban.' Mild increased bruising at pin sites, nothing clinically meaningful. Your mileage may vary.", daysAgo: 44, reactions: { USEFUL: 8, THANKS: 5, LIKE: 3 } },
      { author: "late_bloomer_m", body: "@hexaclinic this is exactly the experience report I was looking for. Thank you. Did you tell the hematologist upfront or was it a 'by the way' thing?", daysAgo: 43, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@late_bloomer_m upfront. I don't hide anything from prescribers. Worst case they say no and you reconsider. Best case you get a real professional opinion to factor in.", daysAgo: 43, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "showmethestudy", body: "The angiogenesis story for BPC is a mechanism hypothesis, not a documented clinical interaction. I wouldn't assume it's additive with anticoagulation in a meaningful way. But the bruising point from dr_doubt is real — that's the concrete concern.", daysAgo: 42, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "citation_required", body: "This is one of the threads where 'talk to your doctor' is not a copout — the interaction space is genuinely unknown and the consequences of a surprise are serious.", daysAgo: 41, reactions: { AGREE: 8, USEFUL: 3 } },
      { author: "cardinal_rule", body: "Flagging for visibility. Blood thinner threads are exactly where I'd want everyone to default to caution. Real experience reports are welcome, blanket 'yeah just run it' replies are not.", daysAgo: 40, reactions: { AGREE: 9, THANKS: 4 } },
      { author: "late_bloomer_m", body: "Appreciated everyone. Talking to hematology next week. Will report back if they greenlight and I actually run it.", daysAgo: 38, reactions: { LIKE: 5, THANKS: 3 } },
    ],
  },

  {
    title: "Pulley injury (A2, climbing) — 8-week BPC log, return to full crimp",
    body: "Posting this as a structured log because I couldn't find one when I tore my A2.\n\n**Injury:** grade 2 A2 pulley strain, right ring finger, climbing a crimpy boulder. Audible pop, swelling within an hour. Self-diagnosed, didn't image — pulled back to half crimp only, taped.\n\n**Protocol:**\n- BPC-157, 500mcg Sub-Q, once daily, over the palmar base of the affected finger\n- 8 weeks continuous\n- Rehab: H-taping, no crimping, hangboard with open hand only at 50% bodyweight, progressing\n\n**Weekly notes:**\n- W1-2: swelling down ~70%, pain on light pinch dropped from 5/10 to 2/10\n- W3-4: half crimp at low load pain-free, full crimp still tender\n- W5-6: full crimp with open grip bias at 60% bodyweight, no pop, mild stiffness morning of\n- W7-8: full crimp at 80% bodyweight, tape off, no pain\n\n**Post-cycle (current, week 14):** back to climbing V6-V7 which was my pre-injury level. Occasional stiffness morning after hard sessions, nothing I'd call pain.\n\nLocal Sub-Q at the finger base wasn't glamorous — 31g pin, very small bleb, rotated between palmar base and dorsal base each day. Not painful to pin.\n\nBiggest variable I can't control for: the no-crimp rehab was legit and I'd been lazy about finger rehab for years. The 8 weeks of BPC coincided with the first real rehab I've ever done on these fingers. So.",
    author: "knee_ice_me",
    daysAgo: 70,
    views: 2260,
    reactions: { LIKE: 8, USEFUL: 9, THANKS: 4 },
    replies: [
      { author: "tendon_theory", body: "Clean log. The 'I also did real rehab for the first time' caveat is what separates a useful report from a hype post. Thank you for being honest about it.", daysAgo: 69, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "rotator_rebuild", body: "A2 is one of the injuries where the local Sub-Q argument is strongest — the tissue is right there under thin skin, the depot is effectively on the pulley. Good application.", daysAgo: 68, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "joint_hunter", body: "Saving this. Have a chronic mild A4 tweak that's been whispering at me for 6 months. Going to copy the protocol.", daysAgo: 65, reactions: { LIKE: 3 } },
      { author: "back_on_the_mat", body: "How did you handle pinning at the finger base without hitting a tendon sheath? 31g still seems close to stuff you don't want to hit.", daysAgo: 63, reactions: { LIKE: 2 } },
      { author: "knee_ice_me", body: "@back_on_the_mat shallow angle, Sub-Q only, bleb raised just under the skin. 31g half-inch, go in at 10-15 degrees to skin and stop as soon as you're past the dermis. You're making a skin wheal, not going deep.", daysAgo: 63, reactions: { USEFUL: 7, THANKS: 3 } },
      { author: "showmethestudy", body: "For context: 8 weeks is inside the natural healing window for a grade 2 pulley. Your return-to-climb timeline is in the range of good rehab without pharmacological help. Not saying BPC did nothing, saying the delta over standard-of-care is the hard thing to pin down.", daysAgo: 62, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "knee_ice_me", body: "@showmethestudy totally fair. I can't run the counterfactual. If I tear the other side I'll do rehab only and compare, but I hope I don't.", daysAgo: 61, reactions: { AGREE: 5, FUNNY: 3 } },
      { author: "kineticdrift", body: "Finger pulley logs are rare and useful. Would love more structured ones like this — week by week notes, clear load progression, not just 'I'm healed.'", daysAgo: 58, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "weekendwarrior_p", body: "Lurker speaking up — this is the kind of content that keeps me on this site instead of Reddit. Structured, honest, self-aware about variables. Bookmarking.", daysAgo: 55, reactions: { LIKE: 7, THANKS: 3 } },
    ],
  },

  // --------- QUIET (2-5 replies) ---------
  {
    title: "Does BPC-157 actually cross the BBB?",
    body: "Seeing claims in various places that BPC has CNS effects — anxiolytic, neuroprotective, serotonergic modulation. The rodent CNS work does exist. But the blood-brain barrier permeability of a 15aa peptide is, at minimum, a real question.\n\nIs there actual data on BBB crossing or is everyone extrapolating 'it had CNS effects in rats when injected IP, therefore it crossed the BBB'? Those are different claims. A peripheral anti-inflammatory effect could produce CNS changes without the molecule ever entering the brain.\n\nAnyone have a better read on this than I do?",
    author: "semax_mornings",
    daysAgo: 36,
    views: 890,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "dr_doubt", body: "Short answer: the direct BBB crossing evidence is weak. Most of the CNS data can be explained by peripheral vagal/immune/gut-brain axis signaling rather than direct central action. 'Affects the brain' and 'gets into the brain' are different. Most BPC neuro-claims would survive if it never crossed the BBB at all.", daysAgo: 35, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "showmethestudy", body: "Agreed. The community tendency is 'CNS effect observed = molecule must be central.' That's not how vagal afferents work. BPC's anti-inflammatory signaling from the periphery is a plausible mechanism for a lot of the 'mood' reports without any BBB crossing required.", daysAgo: 34, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "pde_brainer", body: "The fact that the 'BPC for anxiety' crowd always stacks it with something is a tell. Isolate the variable, then we can talk about CNS effects.", daysAgo: 33, reactions: { AGREE: 4, FUNNY: 2 } },
      { author: "semax_mornings", body: "So the consensus is 'CNS effects real, BBB crossing probably not the mechanism.' That actually matches my read. Thanks for the sanity check.", daysAgo: 32, reactions: { LIKE: 3, THANKS: 2 } },
    ],
  },

  {
    title: "Storage question — reconstituted BPC sat at room temp for 6 hours. Still good?",
    body: "Lapse. Reconstituted a fresh 5mg vial last night, put it on the counter, forgot to fridge it, remembered this morning. So it was room temp (~22C) for roughly 6 hours in BAC water.\n\nIs this vial compromised? Trash it? Use it? The BAC is supposed to prevent bacterial growth but not peptide degradation. I don't want to trash a $40 vial if it's fine.",
    author: "fresh_cycle",
    daysAgo: 18,
    views: 520,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Fine. BPC is relatively stable. 6 hours at 22C with BAC water is nothing. Peptide potency loss over that window is probably under 5%. Fridge it now, move on.", daysAgo: 18, reactions: { USEFUL: 6, THANKS: 3 } },
      { author: "stackbuilder", body: "Agreed with hexaclinic. Now if it had been 72 hours on a hot windowsill in July, different story. 6 hours overnight is fine.", daysAgo: 18, reactions: { AGREE: 4, LIKE: 2 } },
      { author: "fresh_cycle", body: "Great, appreciated. Pinning today.", daysAgo: 17, reactions: { THANKS: 2 } },
    ],
  },

  {
    title: "Comparing BPC suppliers — what does a legit COA actually look like for this compound?",
    body: "Not asking where to buy. Asking: if a vendor sends me a COA, what am I actually supposed to be reading on it?\n\nI've seen 'COAs' that are basically a logo and a line that says '99% pure.' I've seen ones with HPLC chromatograms, mass spec, purity %, peptide content %, sequence verification. Big range.\n\nFor BPC specifically — what should show up on a real COA and what's the bare minimum?",
    author: "curious_catL",
    daysAgo: 29,
    views: 780,
    reactions: { LIKE: 2, USEFUL: 3 },
    replies: [
      { author: "panel_maxer", body: "Real COA for a peptide should include: HPLC chromatogram (showing purity %), mass spec (confirming molecular weight matches the expected), peptide content % (what fraction of the powder is actually peptide vs salts/counterions/water), and ideally sequence confirmation via MS/MS. 'Purity 99%' with no chromatogram is a logo, not a COA.", daysAgo: 28, reactions: { USEFUL: 9, THANKS: 4, LIKE: 3 } },
      { author: "hexaclinic", body: "Add: date of analysis, batch/lot number, and name of the testing lab. If the 'COA' is from the vendor's own QC it's worth less than one from an independent third party.", daysAgo: 28, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "labrat_ish", body: "Also watch for 'peptide content' being quoted as a range or omitted entirely. 98% HPLC purity with 75% peptide content means a quarter of your vial is not peptide. Both numbers matter.", daysAgo: 27, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "curious_catL", body: "This is a cleaner breakdown than I've found elsewhere. Saved.", daysAgo: 26, reactions: { THANKS: 3, LIKE: 2 } },
    ],
  },

  {
    title: "SLAP tear — is BPC realistically going to do anything or am I kidding myself?",
    body: "Type II SLAP tear confirmed on MRI. Surgical consult next month. In the meantime I'm managing with sling-as-needed, PT twice weekly, nothing overhead.\n\nReading around, BPC for labrum is in the 'maybe, unclear, some people claim yes, most shrug' bucket. Labrum is fibrocartilage, poor blood supply, heals badly even in surgical repair.\n\nIs running BPC pre-surgery (4-6 weeks) going to meaningfully change my post-op trajectory? Or is this a 'will not hurt, probably won't help, feel free to try' situation? Skepticism welcome — I'd rather not spend the money if the answer is 'no.'",
    author: "shoulder_spring",
    daysAgo: 27,
    views: 1030,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "showmethestudy", body: "Honest read: the labrum healing data for BPC is close to nothing. The animal tendon data is better characterized than the animal fibrocartilage data. Pre-surgical BPC is reasonable from a 'prepare the tissue environment' angle, but 'meaningfully change post-op trajectory' is a stronger claim than I'd back.", daysAgo: 26, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "tendon_theory", body: "I'd run it, but I'd frame expectations down. 'Might support overall soft tissue environment and gut/systemic inflammation reduction' is a defensible story. 'Will heal my SLAP' is not.", daysAgo: 26, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "dr_doubt", body: "Pre-surgery BPC is low-risk, low-evidence. If you have the money and you're going to feel better having done something, the downside is modest. If you're picking between BPC pre-op and, say, a better PT program or a dietary intervention, I'd take the dietary one.", daysAgo: 25, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "rotator_rebuild", body: "Post-op is where I'd put more of the BPC — the healing environment of a repaired labrum is where peptide support makes more theoretical sense. Talk to your surgeon about timing.", daysAgo: 24, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "shoulder_spring", body: "Thanks everyone. Going to skip pre-op and reassess post-op with the surgeon's input.", daysAgo: 22, reactions: { LIKE: 3, AGREE: 2 } },
    ],
  },

  {
    title: "Running vs cycling BPC — anyone actually stop for long enough to tell?",
    body: "Observation: most people I talk to who 'cycle' BPC are actually off for 1-2 weeks before restarting because they feel worse or because an old injury whispers. That's not a cycle, that's a dose holiday.\n\nHas anyone been completely off BPC for 2+ months after a long run? What happened? Did the benefits persist, fade slowly, or crash?\n\nI'm asking because I want to know if the cycling guidance is actually giving us any observational signal on long-term vs short-term effects.",
    author: "cycle_wrangler",
    daysAgo: 24,
    views: 680,
    reactions: { LIKE: 2 },
    replies: [
      { author: "nopain_noreign", body: "Achilles, ran 8 weeks, stopped for 4 months. Benefit persisted. Didn't slide back. This was after a full rehab block though, so I attribute the durability to the rehab and the BPC to the window that let me do the rehab.", daysAgo: 23, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "tendon_theory", body: "Medial epi, 6 weeks on, 3 months off. Pain came back at about month 2 off but at a much lower intensity than before the cycle. Re-ran 4 weeks and it dropped again. So partial durability, not full.", daysAgo: 22, reactions: { USEFUL: 4 } },
      { author: "pallet_jack", body: "Gut protocol, 6 weeks on, 8 weeks off. Symptoms crept back over weeks 6-8. Not crashed, just drifting. Did a second cycle and the effect was similar. Looks like maintenance territory for me.", daysAgo: 20, reactions: { USEFUL: 5, AGREE: 2 } },
      { author: "cycle_wrangler", body: "Interesting split. Durable for tendons, drifty for gut. That tracks with 'acute healing is a one-time thing, inflammatory gut is an ongoing process.'", daysAgo: 19, reactions: { AGREE: 4, USEFUL: 3 } },
    ],
  },

  {
    title: "BPC myths I want to officially file under 'no, it doesn't do that'",
    body: "Starter list, feel free to add:\n\n1. BPC-157 grows back cartilage. — No. Rodent data is on tendon/ligament and some bone. Articular cartilage regrowth is not documented.\n2. BPC-157 cures depression. — No. CNS effects in rodents are not 'cures depression' in humans.\n3. BPC-157 makes you gain muscle. — No. It's not anabolic.\n4. BPC-157 works better when you cycle it because your body 'adapts.' — No mechanism for adaptation documented. Cycling is precautionary, not corrective.\n5. BPC-157 can replace rehab. — Lol, no.\n\nWhat else?",
    author: "citation_required",
    daysAgo: 21,
    views: 920,
    reactions: { LIKE: 6, FUNNY: 5, AGREE: 4 },
    replies: [
      { author: "nullhypothesis", body: "6. BPC-157 'heals old injuries from decades ago.' The asymptomatic old injury is asymptomatic for a reason — your body adapted. BPC isn't going to undo 15 years of compensation patterns.", daysAgo: 20, reactions: { AGREE: 7, FUNNY: 3, USEFUL: 3 } },
      { author: "placebo_possible", body: "7. 'You can feel BPC working within 24 hours.' The acute anti-inflammatory vibe is real but the healing claims take weeks. If you feel 'healed' in 24 hours, it wasn't broken enough for BPC to be the variable.", daysAgo: 20, reactions: { AGREE: 5, FUNNY: 4 } },
      { author: "showmethestudy", body: "8. 'BPC-157 has no side effects because it's a natural peptide.' Many natural peptides have side effects. Absence of reported side effects is not evidence of absence. Also it's synthetic, not natural in vial form.", daysAgo: 19, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "citation_required", body: "Excellent additions. This is going in my link locker for newbie questions.", daysAgo: 18, reactions: { LIKE: 4, THANKS: 2 } },
      { author: "dr_doubt", body: "9. 'BPC is safe to combine with anything.' We barely know what it does by itself in humans. Combinations are speculation on top of speculation.", daysAgo: 17, reactions: { AGREE: 6, USEFUL: 3 } },
    ],
  },
];

// ============================================================
// TB-500 SUB-FORUM — 12 threads
// 2 popular (15-25 replies), 4 active (6-12 replies), 6 quiet (2-5 replies)
// ============================================================

export const THREADS_TB500: SeedThread[] = [
  // --------- POPULAR ---------
  {
    title: "The classic TB-500 loading protocol — is 5mg 2x/week for 4 weeks actually the right number?",
    body: "The 'standard' TB-500 loading protocol keeps getting repeated on every board: 5mg twice weekly for 4 weeks loading, then 5mg weekly maintenance. I want to poke at where that number came from, because it's been copy-pasted for a decade with no visible origin.\n\nAs far as I can trace: it comes from Pentarhin/Goldstein-era marketing copy for the full-length Tβ4 in equine applications, scaled down by vibe to a human adult. Not a clinical pharmacology derivation.\n\nConsider:\n- TB-500 in the vials most of us buy is the 17-23 fragment (LKKTETQ), not full-length Tβ4. Same fragment, same assumed active sequence, but the dosing translation to human isn't empirically grounded.\n- 5mg/week is a big number in peptide-world terms. Total monthly exposure at the loading protocol is ~40mg. At $80-150/10mg vial, loading alone is $400+.\n- Nobody seems to have experimented meaningfully with lower loads. Everyone defaults to the number they read first.\n\nQuestion: has anyone run a lower-load protocol (say 2mg 2x/wk for 4 weeks) and gotten the subjective 'ironed out' response the higher dose is famous for? Or does the effect actually scale?",
    author: "tb500_train",
    daysAgo: 54,
    views: 5420,
    reactions: { LIKE: 12, USEFUL: 14, AGREE: 8, THANKS: 5 },
    replies: [
      { author: "hexaclinic", body: "Ran 2.5mg 2x/wk loading once, 5mg 2x/wk loading twice. Subjectively the higher load hit harder in week 2 — the systemic 'body feels decompressed' feeling was more obvious. But at week 8 both cycles landed in a similar place. I'd argue the lower load reaches the same steady state, just slower.", daysAgo: 53, reactions: { USEFUL: 9, AGREE: 5 } },
      { author: "tendon_theory", body: "This is one of the cargo-cult dose stories in peptide-world. Nobody knows why 5mg. It just is.", daysAgo: 53, reactions: { AGREE: 11, FUNNY: 4 } },
      { author: "rotator_rebuild", body: "The fragment-vs-full-length distinction is underappreciated. Most community TB-500 is LKKTETQ (or close variants), not Tβ4. Dosing these as if they're the same compound is a stretch.", daysAgo: 52, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "showmethestudy", body: "Goldstein/Pentarhin origins check out. The clinical human trials on actual Tβ4 (not the fragment) used doses in the single-digit mg range weekly, sometimes higher depending on indication. That got rounded to '5mg 2x/wk' for peptide forums and has been quoted ever since.", daysAgo: 52, reactions: { USEFUL: 9, AGREE: 6 } },
      { author: "tb500_train", body: "@showmethestudy appreciated — that's the cleanest trace I've seen for where the 5mg comes from. Confirms my suspicion it's marketing-adjacent, not pharmacology-derived.", daysAgo: 51, reactions: { LIKE: 5, THANKS: 3 } },
      { author: "stackbuilder", body: "I've gone as low as 1.5mg 2x/wk loading. Still got the 'systemic iron' feel by week 3. Convinced the threshold for effect is well below 5mg for most people. The higher dose is just faster onset.", daysAgo: 51, reactions: { AGREE: 6, USEFUL: 5 } },
      { author: "dr_doubt", body: "Skeptical of the 'iron' feel as a reliable dose indicator. It's highly subjective, placebo-sensitive, and conflated with other lifestyle variables. If you're using that as your dosing north star you're going to overshoot.", daysAgo: 50, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "tb500_train", body: "@dr_doubt fair point. The 'iron' feel is the most common community metric for TB-500 onset but it's maybe the worst metric we have. Subjective, vibes-based, unfalsifiable.", daysAgo: 50, reactions: { AGREE: 6 } },
      { author: "cyclecraft", body: "Cost-wise, dropping from 5mg to 2.5mg 2x/wk halves your spend on the most expensive peptide most people run. If the effect scales (even partially) it's a real money conversation.", daysAgo: 49, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "tendon_theory", body: "The one argument for the higher load: faster reach to perceived therapeutic effect. If you're 3 weeks out from a season or a competition and you need the 'ironed' feel to hit fast, 5mg 2x/wk gets you there in 10-14 days vs 3-4 weeks at 2mg.", daysAgo: 48, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "post_surgery_rr", body: "Post-op shoulder, ran 2mg 2x/wk for loading, 2mg weekly maintenance. Perceived effect was clear by week 3. Didn't chase higher. Two vials lasted the whole cycle. Conclusion: lower works.", daysAgo: 47, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "frontloader", body: "I always frontloaded at 10mg first pin then dropped to 5mg 2x/wk. No basis beyond 'it's a peptide with a slow onset, hit it hard early.' Reading this thread I'm reconsidering.", daysAgo: 45, reactions: { LIKE: 3, AGREE: 2 } },
      { author: "slow_titrate", body: "@frontloader 10mg bolus is also where I've seen most of the injection-site weirdness people complain about. Titrating up from 2mg is probably gentler both on the wallet and on the injection sites.", daysAgo: 44, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "achilles_love", body: "I've done four TB cycles, all at 2.5mg 2x/wk loading, 2.5mg weekly maintenance. Chronic Achilles, steady improvement each cycle. Lower loads work if you have the patience.", daysAgo: 43, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "citation_required", body: "If anyone wants to actually run a comparison on themselves: low-load cycle with symptom diary, break, high-load cycle same injury, symptom diary. Two cycles is a weak study but it's better than 'feel' reports. Someone do it and post.", daysAgo: 41, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "tb500_train", body: "@citation_required I might be the one to run it. Next cycle is a recurring calf strain. I'll do 2mg 2x/wk load and report.", daysAgo: 40, reactions: { LIKE: 4, THANKS: 2 } },
      { author: "reading_mode", body: "This is exactly the kind of protocol debate I joined this site for. Saving.", daysAgo: 37, reactions: { LIKE: 3 } },
      { author: "nullhypothesis", body: "The lesson under this whole debate: if you're running a peptide at a dose because 'that's the number,' you're not running an experiment, you're running a ritual.", daysAgo: 35, reactions: { AGREE: 9, USEFUL: 4, LIKE: 3 } },
    ],
  },

  {
    title: "TB-500 + BPC-157 — is the synergy real or is it just running two things and giving both credit?",
    body: "Everyone stacks them. Everyone swears they synergize. But the mechanistic stories are: BPC — local tissue repair, vascular granulation, gut barrier; TB — actin sequestration, cell migration, angiogenesis. Overlapping stories in the 'tissue repair' bucket but not obviously complementary in a way that predicts more-than-additive effects.\n\nPosition: the perceived synergy is a confound. You're running two compounds, you feel better, the body attributes to both. In reality one of them is doing most of the work for your specific injury, and the other is along for the ride at real cost.\n\nIs there a specific injury profile where the stack is clearly better than either alone? Or are we all just burning vials in parallel?",
    author: "protocolpilot",
    daysAgo: 40,
    views: 4320,
    reactions: { LIKE: 10, USEFUL: 8, AGREE: 6, THANKS: 3 },
    replies: [
      { author: "tendon_theory", body: "Honestly? I can't separate them either. Ran BPC alone in 2022, BPC+TB in 2023, similar injuries both years, recovery curves looked close. The stack felt more 'systemic' but the objective markers weren't obviously different.", daysAgo: 39, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "rotator_rebuild", body: "For partial thickness rotator cuff specifically — my take is TB does more work than BPC for the big systemic 'iron' feel, BPC does more for the specific pin-site-adjacent tendon. Running both isn't redundant for my profile, it's additive on different axes.", daysAgo: 39, reactions: { USEFUL: 7, AGREE: 5, LIKE: 3 } },
      { author: "hexaclinic", body: "The synergy claim would be testable if anyone ran TB alone for a rehab cycle. Almost no one does because BPC is cheap and safe and nobody wants to leave it out. Which is how you get stuck with permanent confounding.", daysAgo: 38, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "tb500_train", body: "I've done TB alone twice. For tendinopathy it did less than I expected on its own. Felt better systemically but the specific tendon didn't improve as fast as BPC-only runs. Stack for me is where it lands.", daysAgo: 38, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "showmethestudy", body: "The mechanism overlap — angiogenesis, cell migration, tissue repair — arguably predicts synergy because they're hitting the same process via different handles. But 'predicts synergy' and 'observable synergy in a single human rehab cycle' are lightyears apart.", daysAgo: 37, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "acl_again", body: "Pre-op I ran only BPC. Post-op I'm running the stack. I'll never be able to say what TB added. But I'm not willing to hold it out for the sake of experimental purity while I have a real surgery to recover from.", daysAgo: 37, reactions: { AGREE: 5, LIKE: 3 } },
      { author: "tb500_train", body: "@acl_again this is the honest framing. Recovery-under-real-injury isn't a lab setting, you stack what the community consensus supports and accept you'll never fully parse the contributions.", daysAgo: 36, reactions: { AGREE: 6 } },
      { author: "stackbuilder", body: "My rule: if the injury is localized + tendinous, BPC alone. If there's systemic inflammation/multiple sites/chronic/global stiffness component, add TB. Doesn't make the synergy scientifically clean but it gives me a decision framework.", daysAgo: 35, reactions: { USEFUL: 8, AGREE: 6 } },
      { author: "citation_required", body: "'Running two compounds, feeling better, giving both credit' is literally the definition of a confounded experiment. We're not going to resolve this on a forum. What we can do is get better at logging — so at least we know what we ran and what changed.", daysAgo: 34, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "dr_doubt", body: "Related point — the cost of the stack is meaningful. If BPC alone gets you 80% of the way, adding TB at a $100-400/cycle premium is an expensive 20%. Worth quantifying whether you'd pay that if you knew it was 20%.", daysAgo: 33, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "meniscus_mgmt", body: "Meniscus repair here. I ran TB alone first cycle (6 weeks), added BPC second cycle (6 weeks). The addition of BPC changed the joint-specific pain response notably. TB alone didn't touch it. So for my profile BPC was doing the local work and TB was backdrop.", daysAgo: 32, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "protocolpilot", body: "Great thread. Consensus read: 'synergy' is probably overclaimed, division of labor is a better model (BPC local, TB systemic), and both have an injury profile where they do most of the work. Cost/value depends on which one your specific problem maps to.", daysAgo: 31, reactions: { AGREE: 8, THANKS: 4, LIKE: 3 } },
      { author: "quietstorm", body: "Bookmarking. Best thread I've read on this stack in 6 months.", daysAgo: 29, reactions: { LIKE: 5, THANKS: 2 } },
      { author: "bpc_baby", body: "For newbies reading this — is the right first move BPC alone, and add TB if BPC alone isn't cutting it?", daysAgo: 27, reactions: { LIKE: 2 } },
      { author: "cardinal_rule", body: "@bpc_baby for most cases, yes. BPC alone first, assess at 4-6 weeks, add TB if you're chasing a systemic effect or hitting a plateau. Don't start with the full stack if you don't need it — you won't know what's doing what.", daysAgo: 27, reactions: { AGREE: 9, USEFUL: 6, THANKS: 4 } },
    ],
  },

  // --------- ACTIVE (6-12 replies) ---------
  {
    title: "Flu-like side effect on TB-500 — is this a real thing or am I just sick?",
    body: "Second pin of my first TB cycle, 5mg Sub-Q in the flank. About 8 hours later — chills, low-grade ache, tiredness, mild headache. No fever I could measure but the subjective 'I'm coming down with something' thing was unmistakable.\n\nLasted maybe 18 hours, then gone. Next pin 3 days later, same reaction but milder. By pin 5 it was absent.\n\nSearching the forum I see a handful of people mention this and then it gets shrugged off. Is this a documented thing for TB-500 specifically? Endotoxin contamination? Immune reaction to the fragment? Placebo?",
    author: "tb500_train",
    daysAgo: 46,
    views: 1680,
    reactions: { LIKE: 4, USEFUL: 3 },
    replies: [
      { author: "hexaclinic", body: "Real thing. Happens to a minority of users, especially on the loading doses. Most reports describe exactly what you describe — first 1-3 pins have a mild flu-feel, tolerance develops, gone by week 2. Mechanism is almost certainly a transient immune/cytokine response to the peptide itself or a trace impurity.", daysAgo: 45, reactions: { USEFUL: 10, AGREE: 5, THANKS: 4 } },
      { author: "rotator_rebuild", body: "Got this exact pattern on my first TB cycle. Freaked me out the first time. By the 4th pin it was a 'oh, this again' shrug. Tolerized out completely.", daysAgo: 45, reactions: { AGREE: 6, LIKE: 3 } },
      { author: "showmethestudy", body: "Could be endotoxin in the batch. High-purity TB from a reputable source typically has fewer reports. Low-end vendors seem to produce it more often. If you haven't vetted the vendor's COA for endotoxin levels, that's a place to look.", daysAgo: 44, reactions: { USEFUL: 8, AGREE: 4 } },
      { author: "tb500_train", body: "@showmethestudy I asked the vendor, they sent HPLC but no endotoxin result. Noted as a dig-deeper item for the next vial.", daysAgo: 44, reactions: { LIKE: 3 } },
      { author: "dr_doubt", body: "If it escalated or persisted I'd pause. Transient, tolerizing, mild — consistent with the community report pattern. But it's worth knowing your own body well enough to catch the difference between 'tolerizing' and 'something's wrong.' Keep notes.", daysAgo: 43, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "stackbuilder", body: "Dose-splitting can blunt it. 2.5mg x2 over a day instead of 5mg single pin on the same day. Less cytokine spike, milder effect.", daysAgo: 43, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "tb500_train", body: "Appreciated everyone. Symptoms gone by pin 5 as predicted. Continuing the cycle.", daysAgo: 40, reactions: { LIKE: 4, THANKS: 2 } },
      { author: "tendon_theory", body: "Worth a pinned note for newbies: 'if you get mild flu-feel on first 1-3 pins of TB, it's commonly reported and usually resolves. If it escalates or doesn't go away by pin 4, stop and reassess.'", daysAgo: 38, reactions: { AGREE: 8, USEFUL: 4, LIKE: 3 } },
    ],
  },

  {
    title: "TB-500 and the hair growth / dark hair return claims — what's the signal-to-noise here?",
    body: "Reading various boards and the 'TB-500 darkened my gray hair' anecdotes are all over. The mechanistic story: Tβ4 has been studied in hair follicle cycling and melanocyte biology, and there are some rodent papers on follicle stem cells + Tβ4.\n\nBut the human community reports are wildly inconsistent. Some people claim dark hair return, some claim faster hair growth, most notice nothing, a few claim shedding. I've been through like 200 anecdotes this week and the only unifying thread is that people who want an anti-aging angle report one, and people running it for tendons don't mention hair at all.\n\nWhat's going on here? Signal, placebo, or a third thing I'm missing?",
    author: "telomere_t",
    daysAgo: 38,
    views: 2890,
    reactions: { LIKE: 6, USEFUL: 4 },
    replies: [
      { author: "showmethestudy", body: "The Tβ4 + follicle story is a real research line but it's mostly wound healing adjacent — hair follicle neogenesis in the context of skin injury. Extending that to 'systemic TB-500 restores gray hair pigment in adult humans' is a large leap that nobody has actually tested.", daysAgo: 37, reactions: { AGREE: 8, USEFUL: 6 } },
      { author: "hexaclinic", body: "I'm a data point: 3 years of TB-500 cycles for rehab, no perceivable change in my hair. Gray at the temples has marched along on schedule. The 'dark hair return' reports feel to me like attentional bias — once you're looking for it you find wisps.", daysAgo: 37, reactions: { AGREE: 7, FUNNY: 3, LIKE: 3 } },
      { author: "nullhypothesis", body: "This is the purest placebo-adjacent effect in the peptide world. The 'dark hair return' claim is self-reported, subjective, confounded with seasonal light exposure, haircut frequency, and 'I took a new photo today and my hair looks different.' Without before/after strand-scale photography the claim is unsalvageable.", daysAgo: 36, reactions: { AGREE: 9, FUNNY: 5, USEFUL: 4 } },
      { author: "epi_cycler", body: "Ran TB for rehab. Wife asked if I colored my beard. I didn't. That's one data point toward 'maybe something.' Also possibly the bathroom lighting changed. I don't know.", daysAgo: 35, reactions: { FUNNY: 8, LIKE: 4 } },
      { author: "telomere_t", body: "@epi_cycler this is the kind of anecdote that makes the claim impossible to kill. Plausible mechanism + one person's wife noticing = forum legend.", daysAgo: 35, reactions: { FUNNY: 6, AGREE: 4 } },
      { author: "dr_doubt", body: "Would take the hair claims seriously the moment someone posts standardized before/after photography under matched lighting at 4 week intervals. Until then: filed under 'interesting if true, not banking on it.'", daysAgo: 34, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "tendon_theory", body: "For what it's worth, I've run 7 TB cycles, no hair effect. People who run TB for rehab and don't think about hair don't report hair changes. People who run TB hoping for hair changes report them. Worth thinking about.", daysAgo: 33, reactions: { AGREE: 9, USEFUL: 5, LIKE: 3 } },
      { author: "placebo_possible", body: "Expectancy effects in peptide self-experimentation are massive. The 'dark hair' claim is where they're most visible because the marker is slow, subtle, and self-assessed.", daysAgo: 32, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "telomere_t", body: "Thanks everyone. My read: genuinely plausible mechanism in a narrow research context, basically unvalidated in humans, community reports are confounded by expectancy. Going to stop counting it as a reason to cycle TB.", daysAgo: 30, reactions: { LIKE: 5, AGREE: 4 } },
    ],
  },

  {
    title: "Does TB-500 actually do much for tendons when it's running alone?",
    body: "Genuine question coming out of 3 cycles. My honest impression of TB-500 solo — without BPC in the stack — is that the 'systemic ironed out' feeling is real, but the tendon-specific healing is underwhelming.\n\nI've got chronic patellar tendinopathy (5+ years). BPC-only cycles produce measurable improvements on that tendon within 4-6 weeks. TB-500-only cycles produce a nice global 'I feel more limber' vibe but the tendon doesn't improve on the same timeline.\n\nIs this a common pattern? Is TB actually more of a systemic anti-inflammatory/cell-migration peptide whose direct effect on tendon repair is weaker than the community assumes?",
    author: "achilles_love",
    daysAgo: 35,
    views: 1920,
    reactions: { LIKE: 5, USEFUL: 4 },
    replies: [
      { author: "tendon_theory", body: "Matches my pattern exactly. TB solo for tendons is underwhelming on my body. The 'systemic' claim is real, the 'targets tendons specifically' claim feels weak. BPC is the tendon workhorse in my experience.", daysAgo: 34, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "rotator_rebuild", body: "Partial counter — for muscle-tendon junction injuries, TB seems to do more than for pure tendon body. The cell-migration story fits better with the junction healing than with the mid-tendon fibrosis work.", daysAgo: 34, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "hexaclinic", body: "My theory: TB-500's primary effect is on soft tissue globally — vascular, inflammatory, systemic recovery feel. BPC's primary effect is on specific collagenous/fibroblast repair. Tendon body = BPC's turf. Muscle + fascia + systemic = TB's turf. The stack covers both.", daysAgo: 33, reactions: { USEFUL: 10, AGREE: 7, LIKE: 4 } },
      { author: "showmethestudy", body: "@hexaclinic this framing is better than any I've read in the actual literature. The human data is thin enough that a clean functional division like yours is speculative — but it matches a lot of community reports.", daysAgo: 33, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "post_surgery_rr", body: "Rotator cuff post-op. TB alone wasn't cutting the pain at 6 weeks. Added BPC Sub-Q over the shoulder and the needle moved within 10 days. Supports the 'TB systemic, BPC local' frame.", daysAgo: 31, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "achilles_love", body: "Consensus: TB alone is underrated systemically, overrated locally for tendons. Glad my read wasn't crazy.", daysAgo: 30, reactions: { LIKE: 4, AGREE: 3 } },
      { author: "citation_required", body: "Worth flagging for newbies: the marketing copy on TB-500 usually lists tendons/ligaments first. Community experience suggests TB is more of a systemic recovery agent than a localized tendon repair agent. Read accordingly.", daysAgo: 29, reactions: { AGREE: 8, USEFUL: 5 } },
    ],
  },

  {
    title: "Cost math on a TB-500 cycle — is this really worth $300-500 a round?",
    body: "Real numbers check for anyone on the fence.\n\n**Loading phase (4 weeks, 5mg 2x/wk):** 40mg total. At $80-150 per 10mg vial, that's $320-600 on loading alone.\n**Maintenance (8 weeks, 5mg/wk):** 40mg total. Another $320-600.\n**Full cycle (12 weeks):** $640-1200.\n\nCompare:\n- BPC-157, 6 weeks, 500mcg/day = 21mg total. At $30-60 per 5mg vial, roughly $125-250 a cycle.\n- CJC-1295/Ipa, 8 weeks, 200mcg 3x/day = ~33mg each. Vials typically $40-80 per 5mg. Roughly $260-530 a cycle.\n\nTB is clearly the most expensive peptide most of us run. The per-mg price hasn't come down meaningfully in years because it's a 17-23 fragment that's expensive to synthesize cleanly.\n\nQuestion: for what range of injuries/goals is a TB-500 cycle actually pulling its weight vs alternatives? For me the answer is: post-surgical, post-major-injury, maybe chronic systemic recovery. Not maintenance. Not 'general vibes.' Not 'I work out hard sometimes.'",
    author: "cyclecraft",
    daysAgo: 31,
    views: 1610,
    reactions: { LIKE: 7, USEFUL: 6, AGREE: 4 },
    replies: [
      { author: "stackbuilder", body: "Numbers check out. My rule: TB goes in the stack when I have a real surgical or multi-site event. BPC goes in for anything local. GH secretagogue for general recovery and sleep. TB isn't in my default rotation, it's an event-specific tool.", daysAgo: 30, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "hexaclinic", body: "Same. I don't run TB for anything short of a real rehab need. The cost-to-expected-benefit math on 'maybe feels better' doesn't pencil.", daysAgo: 30, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "frontloader", body: "The lower-load experiments in the other thread are the biggest cost lever. If 2mg 2x/wk works (and reports suggest it does for many people) you can cut cycle cost by more than half. That's where I'd start.", daysAgo: 29, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "tb500_train", body: "Also — TB maintenance is where a lot of people throw money without evidence it's doing much. The loading phase is where the community reports the clearest perceived effects. Maintenance might be optional.", daysAgo: 28, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "slow_titrate", body: "Reality check for the 'run it forever' TB people: this is a $2400/year habit at full dose, minimum. Most of us are not getting $2400/year of durable benefit out of it. Cycle hard, stop when the acute injury resolves.", daysAgo: 27, reactions: { AGREE: 8, FUNNY: 3 } },
      { author: "dr_doubt", body: "Strong framing. TB as an event-specific tool, not a lifestyle peptide. The lifestyle peptides (GH sec, maybe BPC) have better cost economics. TB doesn't pencil unless you have a specific problem worth $500 to maybe fix.", daysAgo: 26, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "cyclecraft", body: "Appreciated. Seems like the community converges on: TB for acute/post-op rehab, not for maintenance, and lower loads probably work. Good.", daysAgo: 25, reactions: { LIKE: 4, THANKS: 2 } },
      { author: "reads_more_posts", body: "Lurker here. These cost threads are the most useful on the site. Saves me money I don't have to spend.", daysAgo: 23, reactions: { LIKE: 6, THANKS: 3 } },
    ],
  },

  // --------- QUIET (2-5 replies) ---------
  {
    title: "Injection frequency on TB — weekly or split 2x weekly at the same weekly dose?",
    body: "Simple question. If I'm running 5mg/wk maintenance, is there a reason to split to 2.5mg twice weekly vs pin the full 5mg once?\n\nHalf-life of TB-500 is quoted anywhere from hours to days depending on the source. The systemic effect feels persistent across the week regardless. Is there actual evidence that splitting matters at maintenance dose?",
    author: "taper_time",
    daysAgo: 22,
    views: 640,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "At maintenance, I don't split. One pin per week is the whole point of maintenance — reduce the burden. If you're still splitting at maintenance you haven't really left loading.", daysAgo: 21, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "tb500_train", body: "Agreed with hexaclinic. Loading is where the splitting might matter (to reduce acute injection-site reaction, flu-feel, cost-front-loading). Maintenance is one pin, move on.", daysAgo: 21, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "taper_time", body: "Good, one pin it is. Thanks.", daysAgo: 20, reactions: { LIKE: 2 } },
    ],
  },

  {
    title: "Full-length Tβ4 vs the fragment (LKKTETQ) — which is in the vial I'm buying?",
    body: "Bit of a noob-ish question but I can't find a clear answer. When I buy 'TB-500' from a peptide vendor, am I getting:\n\n- Full-length Thymosin beta-4 (~43 amino acids, the native peptide)\n- The 17-23 fragment (LKKTETQ, 7 amino acids, the synthetic 'active site' people call TB-500)\n- Something else\n\nVendor copy is usually vague. Some COAs I've seen specify the fragment. Others just say 'TB-500' with no sequence listed. Should I be insisting on the full-length, or is the fragment the standard community product?",
    author: "new2peptides",
    daysAgo: 25,
    views: 710,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "labrat_ish", body: "You're almost certainly getting the fragment. 'TB-500' in community parlance has been the 17-23 fragment (LKKTETQ-style) for a decade. Full-length Tβ4 exists (marketed as Thymosin beta-4) and is way more expensive — different product, different price point. If the vendor is charging fragment prices you're getting a fragment.", daysAgo: 24, reactions: { USEFUL: 8, THANKS: 4 } },
      { author: "hexaclinic", body: "Ask for a sequence on the COA. If they can't give you one, walk. 'TB-500' is a trade name, not a sequence specification. A real COA lists what's in the vial.", daysAgo: 24, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "showmethestudy", body: "Most of the community data, such as it is, is on the fragment. So if you want your experience to map to the forum reports, fragment is what you want. Full-length Tβ4 is a more ambitious purchase with a different literature behind it.", daysAgo: 23, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "new2peptides", body: "Clarifying, thanks. Going to ask the vendor for the sequence line on the COA before reordering.", daysAgo: 22, reactions: { THANKS: 3, LIKE: 2 } },
    ],
  },

  {
    title: "Heart/cardiomegaly concern with long-term TB-500 — anyone actually seen imaging?",
    body: "Low-grade worry nagging at me. Tβ4 shows up in cardiac biology research — post-MI tissue repair, endothelial migration, etc. The 'more tissue repair' story is the selling point for injury recovery. But tissue remodeling in the heart is not always what you want.\n\nHas anyone who's run TB-500 long-term actually gotten an echo or MRI and looked at cardiac dimensions? Or is this one of those 'theoretical concern that's never been investigated' items we all just handwave?",
    author: "apob_reader",
    daysAgo: 20,
    views: 580,
    reactions: { LIKE: 2, USEFUL: 2 },
    replies: [
      { author: "dr_doubt", body: "I've done echos during and after TB cycles (for an unrelated reason — pre-existing cardiology follow-up). Nothing measurably different. N=1, not a study. But the cardiomegaly concern is largely theoretical in humans at the fragment doses and durations the community runs.", daysAgo: 19, reactions: { USEFUL: 7, THANKS: 3 } },
      { author: "hexaclinic", body: "The cardiac remodeling story comes from post-MI animal models where full-length Tβ4 is infused at high doses in injured hearts. That's not the scenario a healthy adult pinning 5mg/wk fragment is in. Not zero concern, but also not the straight-line concern it's sometimes framed as.", daysAgo: 19, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "showmethestudy", body: "The honest answer: no long-term human cardiac imaging data exist for recreational TB-500 users. The concern is real at a mechanistic level but the evidence base is essentially zero in either direction. If you've got an independent reason to image, image. If not, the risk is not well-characterized.", daysAgo: 18, reactions: { AGREE: 6, USEFUL: 5 } },
      { author: "apob_reader", body: "Useful. Going to put 'basic echo' on my next physical checklist regardless. Cheap baseline.", daysAgo: 17, reactions: { AGREE: 3, LIKE: 2 } },
    ],
  },

  {
    title: "Chronic tendinopathy that hasn't responded to anything — TB alone or stack?",
    body: "5 years of left patellar tendinopathy. Tried everything short of PRP and surgery: rehab (multiple cycles, eccentric protocols done properly), PT for months, dry needling, shockwave, BPC cycles (3 of them). All gave partial relief that didn't stick.\n\nConsidering a full TB-500 cycle alone to see if the systemic angle unlocks something BPC hasn't. Or I should stack with BPC again despite diminishing returns?\n\nPartial response to BPC — not nothing, not a fix. Curious if people with similar 'BPC didn't finish the job' cases found TB did anything additional.",
    author: "tendon_theory",
    daysAgo: 16,
    views: 780,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "rotator_rebuild", body: "Chronic rotator. BPC-only got me 60% of the way. Adding TB didn't finish the job — PRP did. Not selling PRP, just reporting what moved a tendon that had resisted 3 years of everything else. TB helped the global feel but didn't fix the specific tendon.", daysAgo: 15, reactions: { USEFUL: 7, AGREE: 3 } },
      { author: "hexaclinic", body: "Chronic tendinopathy that's had 5 years of peptide and rehab is mechanically different from an acute tendinopathy. The collagen architecture has actually changed — it's disorganized and fibrotic. Peptides are better at acute repair than at reorganizing old scar-like tissue. Worth considering whether you're chasing the wrong tool.", daysAgo: 15, reactions: { USEFUL: 8, AGREE: 6 } },
      { author: "achilles_love", body: "Chronic Achilles, similar profile. TB addition on top of BPC gave me maybe 10% extra. Not worth the money for that alone. Heavy slow resistance loading for 12 weeks did more than the peptides at that stage.", daysAgo: 14, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "tendon_theory", body: "Noted. Probably pivoting to PRP consult + keeping rehab brutal. Peptides have given what they can for this one.", daysAgo: 13, reactions: { AGREE: 4, LIKE: 3 } },
      { author: "dr_doubt", body: "Good call. When a tissue has been chronically abnormal for years, the 'repair' toolkit is limited. Doesn't mean nothing works — it means the things that work are structural (load, PRP, sometimes surgery), not primarily pharmacological.", daysAgo: 12, reactions: { AGREE: 6, USEFUL: 4 } },
    ],
  },

  {
    title: "Supplier quality for TB-500 specifically — why does this one seem to vary more than BPC?",
    body: "Observation from 3 years of buying both. BPC seems to be pretty consistent across reputable vendors — response feels similar across different suppliers I've tried.\n\nTB-500 is much more variable. Two different vendors, same stated dose, and the subjective effect differs. Batch to batch within the same vendor also seems less consistent than BPC.\n\nIs this a synthesis difficulty thing? The fragment is shorter and in theory should be easier to synthesize cleanly. Or is it quality control at the lower end of the market? Curious if others see this pattern.",
    author: "protocolwonk",
    daysAgo: 13,
    views: 490,
    reactions: { LIKE: 2 },
    replies: [
      { author: "labrat_ish", body: "Fragment is easier to synthesize, but purification is where the variance lives. BPC is a stable, relatively forgiving purification. TB fragment has more variable cut-side issues and can have more impurities. Cheap synthesis + marginal purification = batch-to-batch chaos.", daysAgo: 12, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "hexaclinic", body: "Agreed. The variance you're seeing is real and it's a synthesis/purification story, not a 'the peptide itself is finicky' story. Stick with the one vendor whose TB has worked for you and don't bargain shop on this one.", daysAgo: 12, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "stackbuilder", body: "Also: TB is the peptide most affected by ambient temperature during shipping in my experience. Summer-shipped vials that sat on a porch for 8 hours at 35C feel weaker than the same vendor's winter batch. Shelf stability in powder is fine but heat in transit is real.", daysAgo: 11, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "protocolwonk", body: "The transit heat angle I hadn't considered. Going to start requesting cold packs on summer shipments.", daysAgo: 10, reactions: { THANKS: 2, LIKE: 2 } },
    ],
  },

  {
    title: "TB-500 pin site irritation — is this a vendor issue or am I pinning wrong?",
    body: "Third pin of a TB cycle. Small red lump at the pin site, slightly warm, a bit itchy. Doesn't look infected — no spreading, no pus, no fever. But the same sites have been lumpy for 2-3 days after each pin.\n\nBPC on the same schedule, same needles, same BAC water — never had this. TB-specific.\n\nDilution, vendor, or pin technique? Trying to narrow down.",
    author: "loading_phase",
    daysAgo: 10,
    views: 420,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Most likely the dilution. TB-500 is a higher-concentration pin by volume than BPC at typical reconstitution. If you reconstituted a 5mg vial with 1mL BAC, you're pinning dense peptide solution. Redo with 2mL BAC, pin 2x the volume for the same dose. Usually fixes the site reaction.", daysAgo: 9, reactions: { USEFUL: 9, THANKS: 4 } },
      { author: "tb500_train", body: "Seconded. The 1mL reconstitution on TB is a common cause of site lumps. Dilute more, pin more volume, problem usually disappears.", daysAgo: 9, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "stackbuilder", body: "Also — TB does produce a mild local inflammatory response for some people independent of dilution. If re-diluting doesn't fix it within a pin or two, consider rotating to a different site region (flank vs abdomen) or slowing your push speed. Faster push = more local irritation.", daysAgo: 8, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "loading_phase", body: "Re-dilution fixed it. 2mL BAC on the next vial, no lumps. Thanks.", daysAgo: 6, reactions: { THANKS: 4, LIKE: 3 } },
    ],
  },
];
