import type { SeedThread } from "../types";

// ============================================================
// GHK-Cu — 10 threads (1 popular, 3 active, 6 quiet)
// ============================================================
export const THREADS_GHKCU: SeedThread[] = [
  // -------------------- POPULAR --------------------
  {
    title: "Topical vs injected GHK-Cu — I keep seeing people argue this and the evidence isn't symmetrical",
    body: "Every few weeks someone posts 'why inject GHK-Cu when you can just slather it on' or the mirror image 'topical is a waste, only sub-q works.' Both are oversimplifying and I want to actually lay it out.\n\nGHK-Cu (glycyl-histidyl-lysine + Cu2+) is one of the most studied peptides we have because it's been in cosmetic dermatology literature since the 80s. The majority of the published work is topical. Penetration is real — the peptide is small (340 Da for the tripeptide, ~420 with copper), and there's good evidence it reaches the dermis at cosmetic concentrations (0.05–2% serums, roughly). You get collagen upregulation, decorin, fibroblast activity, some antioxidant effect via copper.\n\nInjected GHK-Cu is a different animal. Systemic administration gives you circulating copper-binding peptide, which does show up in wound-healing and anti-inflammatory models, but the human clinical data is basically non-existent. Everything you read about 'injected GHK-Cu for skin' is extrapolation.\n\nMy honest take:\n- For skin + hair + scars: topical is the evidence-based choice. Don't inject for cosmetic reasons.\n- For systemic healing / anti-inflammatory hypothesis: maybe injection has a role, but you're in n=1 territory.\n- Sub-q injections near a scar or injury site is the one case where injection for local effect has a theoretical argument, and some people swear by it. I'm skeptical but not dismissive.\n\nWhat do people actually use and why?",
    author: "hexaclinic",
    daysAgo: 72,
    views: 3940,
    reactions: { LIKE: 14, USEFUL: 18, AGREE: 11, THANKS: 6 },
    replies: [
      { author: "theoretic", body: "Good framing. I'd add that topical GHK-Cu has the unusual property of being one of the few peptides where the topical literature outweighs the injection literature. That's the opposite of almost everything else we discuss here.", daysAgo: 72, reactions: { AGREE: 10, USEFUL: 6 } },
      { author: "dr_doubt", body: "The injected-for-systemic-healing crowd is building on rodent wound models and in vitro fibroblast work. It's not nothing but it's nowhere near 'this works in humans at this dose.' The topical literature at least has controlled split-face trials in real people.", daysAgo: 71, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "showmethestudy", body: "Pickart's own papers are the entry point. Read those before you form a strong opinion in either direction. Half the 'injected GHK-Cu does X' claims I see on Reddit don't appear anywhere in the actual literature.", daysAgo: 71, reactions: { USEFUL: 8, AGREE: 6 } },
      { author: "post_surgery_rr", body: "I've done both. Topical daily on face, sub-q near my shoulder surgery site twice a week for 8 weeks. The topical I can see in the mirror. The sub-q I can't honestly separate from the rehab timeline. Won't do the sub-q again.", daysAgo: 70, reactions: { USEFUL: 7, LIKE: 4 } },
      { author: "reggae_fiend", body: "People inject it because injecting feels like doing something real. Rubbing a serum on your face feels like your mom's skincare routine. It's an aesthetic-of-effort problem, not a pharmacology problem.", daysAgo: 70, reactions: { FUNNY: 11, AGREE: 7 } },
      { author: "petal_push", body: "So if I'm just trying to get smoother skin, topical 2% serum is fine? No need to mess with needles?", daysAgo: 69, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@petal_push correct. 1–2% GHK-Cu serum, once or twice daily, clean skin, not layered with anything that'll strip the copper (vit C same application is the classic mistake). Give it 8–12 weeks before you judge.", daysAgo: 69, reactions: { USEFUL: 9, THANKS: 4 } },
      { author: "tb500_train", body: "I inject GHK-Cu with my TB500/BPC stack when I'm coming back from joint stuff. I can't prove it does anything on its own in that mix. But it doesn't seem to hurt either. File it under 'cheap and probably fine.'", daysAgo: 68, reactions: { LIKE: 3, USEFUL: 3 } },
      { author: "citation_required", body: "The fact that the cosmetic literature is stronger than the injection literature should make everyone a little uncomfortable, because cosmetic studies are notoriously weak. That bar should be higher, not lower.", daysAgo: 67, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "mothra", body: "Old head perspective — this peptide has been sold in skincare since before most of this forum was born. If injection were the superior route, the cosmetic industry (which has infinite incentive to differentiate) would have moved there. They didn't. Follow the money.", daysAgo: 66, reactions: { AGREE: 11, USEFUL: 6, LIKE: 4 } },
      { author: "shoulder_spring", body: "Counterpoint to mothra — cosmetic industry optimizes for shelf life and FDA-friendly claims, not efficacy. Not a strong argument from incentives.", daysAgo: 65, reactions: { AGREE: 4 } },
      { author: "hexaclinic", body: "@shoulder_spring fair, but the combined weight of cosmetic-industry investment AND independent dermatology research both landing on topical is a stronger signal than either alone.", daysAgo: 65, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "the_architect_p", body: "My framework: topical for skin/scalp/scar aesthetics, no needles needed. Sub-q is experimental and should be treated as such — log it, have a stop rule, don't expect published-level results.", daysAgo: 64, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "curious_catL", body: "Saving this whole thread. Was about to buy lyophilized GHK-Cu to inject for my face and I think I dodged a bullet.", daysAgo: 62, reactions: { LIKE: 5, THANKS: 3 } },
      { author: "reads_more_posts", body: "Good thread. Rare case where the 'just use the topical' answer is the actually evidence-based one.", daysAgo: 58, reactions: { AGREE: 5 } },
      { author: "wanderlite", body: "Dumb question but does the copper matter or can you just use plain GHK? I see both sold.", daysAgo: 55, reactions: {} },
      { author: "hexaclinic", body: "@wanderlite the copper matters a lot. GHK without Cu2+ is a different compound functionally. The copper ion is what drives a lot of the fibroblast and antioxidant effects. Don't buy 'GHK' — buy 'GHK-Cu.'", daysAgo: 55, reactions: { USEFUL: 8, THANKS: 4 } },
      { author: "nullhypothesis", body: "The strongest version of the injected-GHK-Cu case is 'local injection adjacent to a wound site might beat topical penetration at depth.' That's it. Everything else is just wanting to inject something.", daysAgo: 52, reactions: { AGREE: 9, USEFUL: 5 } },
    ],
  },

  // -------------------- ACTIVE --------------------
  {
    title: "Homemade topical GHK-Cu — someone check my concentration math",
    body: "Making my own 2% serum and I keep getting tangled up on ppm vs mg/mL vs percent. Want to double check before I waste a vial.\n\nStarting material: 50mg lyophilized GHK-Cu vial. I want to make 30mL of 2% serum.\n\n2% by mass in a water-based vehicle ≈ 20mg/mL ≈ 20,000 ppm. So 30mL * 20mg/mL = 600mg needed. That's way more than one 50mg vial. Which means one vial at 30mL is closer to 1.67mg/mL = 0.167%.\n\nQuestions:\n1. Is 'percent' in cosmetic chem w/v (mass per volume) or w/w (mass per mass)? I've been assuming w/v.\n2. For a legitimate 2% serum I'd need 600mg per 30mL bottle, which is a lot of peptide. The commercial stuff can't actually be 2% GHK-Cu at their price points — am I misreading labels?\n3. What's a realistic DIY concentration that's worth the trouble? I'm seeing 0.05–0.2% in published topical studies, so maybe I'm overshooting.\n\nVehicle plan: preserved hydrosol base with a little glycerin, pH buffered to ~5.5. Skipping anything that'll reduce the copper.",
    author: "panel_maxer",
    daysAgo: 40,
    views: 1820,
    reactions: { USEFUL: 9, LIKE: 4, AGREE: 3 },
    replies: [
      { author: "hexaclinic", body: "Your math is right. Cosmetic percent is almost always w/w, but for dilute aqueous serums w/v and w/w are within rounding error. The real issue is what you identified — commercial '2% GHK-Cu' serums almost certainly aren't. Read the INCI list: if GHK-Cu isn't in the top 5 ingredients, it's not 2% of anything.", daysAgo: 40, reactions: { USEFUL: 11, AGREE: 7 } },
      { author: "theoretic", body: "The published topical literature is mostly in the 0.05–0.2% range. You don't need 2% and there's decent evidence returns are flat or declining above ~0.5%. One 50mg vial in 30mL gives you 0.17%, which is right in the sweet spot.", daysAgo: 40, reactions: { USEFUL: 9, AGREE: 5 } },
      { author: "cardinal_rule", body: "Good post — this is the kind of 'check my work' we want more of. Tagging for any cosmetic chem folks lurking.", daysAgo: 39, reactions: { LIKE: 4 } },
      { author: "protocolwonk", body: "For DIY I run 0.1% and it's been fine on my skin for 6 months. One 100mg vial makes 100mL at that strength which lasts forever. 2% is marketing math, not working math.", daysAgo: 39, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "petal_push", body: "If 0.1–0.2% is the real working range, the commercial serums charging $90 for 30mL of '2%' are either lying or using way less peptide than labeled. Is there any independent testing?", daysAgo: 38, reactions: { LIKE: 2 } },
      { author: "dr_doubt", body: "@petal_push short answer: no. Cosmetic actives are notoriously under-verified. Assume the label is aspirational.", daysAgo: 38, reactions: { FUNNY: 5, AGREE: 4 } },
      { author: "bac_water_noob", body: "pH 5.5 buffered how? Citric? That'll chelate the copper off the peptide.", daysAgo: 37, reactions: { USEFUL: 5 } },
      { author: "panel_maxer", body: "@bac_water_noob good catch — I was going to use citric. What's a better option?", daysAgo: 37, reactions: {} },
      { author: "hexaclinic", body: "Lactic acid works, or a phosphate buffer. Avoid anything with strong chelation properties (citric, EDTA, ascorbic). The copper is the whole point.", daysAgo: 37, reactions: { USEFUL: 8, THANKS: 3 } },
      { author: "stackbuilder", body: "Saving this thread. Been meaning to DIY and the chelation issue is exactly the kind of thing I would have missed.", daysAgo: 35, reactions: { LIKE: 3 } },
      { author: "notes_taker", body: "Bookmarked. Thanks for showing the work.", daysAgo: 32, reactions: { LIKE: 2 } },
      { author: "kineticdrift", body: "Worth stating out loud: 'percent' in bodybuilding peptide talk and 'percent' in cosmetic chem mean different things. Posting this math helps new people not assume the higher number is the effective one.", daysAgo: 30, reactions: { AGREE: 6, USEFUL: 4 } },
    ],
  },
  {
    title: "Hair loss stack — GHK-Cu + AHK-Cu + zinc thymulin. Anyone actually doing all three?",
    body: "I've been on topical minoxidil + finasteride for two years and it's holding the line but not regrowing much. Looking at adding the copper peptide trio you see on r/tressless:\n\n- GHK-Cu — fibroblast / follicle stem cell signaling\n- AHK-Cu — dermal papilla stimulation, sometimes marketed as 'stronger for hair than GHK'\n- Zinc thymulin — separate mechanism, seems to slow miniaturization in some data\n\nQuestions:\n1. Is the AHK-Cu claim real or is it just GHK-Cu's cousin with better marketing?\n2. Anyone running all three topically? Do you mix into one serum or rotate?\n3. Timing with min/fin — same application, or separate?\n4. 6+ month results appreciated. I'm tired of 'week 3 looking promising!' posts.",
    author: "goal_driven",
    daysAgo: 55,
    views: 2210,
    reactions: { LIKE: 6, USEFUL: 4 },
    replies: [
      { author: "reggae_fiend", body: "Been running GHK-Cu + zinc thymulin for a year. Skipped AHK-Cu because I've never seen convincing comparison data — it's structurally similar and almost all the 'AHK is better for hair' claims trace back to one supplier's white paper. I'd pick GHK-Cu.", daysAgo: 55, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "theoretic", body: "AHK-Cu has some in-vitro dermal papilla work but the human topical evidence is much thinner than GHK-Cu. Run GHK-Cu and zinc thymulin, drop AHK unless you have money to burn.", daysAgo: 54, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "frontloader", body: "I layer min (5% + tret 0.025% combined) in the morning, GHK-Cu 0.2% at night. Zinc thymulin goes on nights I skip tret. 8 months in, hairline hasn't moved and I'm getting vellus on the temples. Can't isolate which is doing what.", daysAgo: 54, reactions: { USEFUL: 8, LIKE: 3 } },
      { author: "hexaclinic", body: "Important: don't apply copper peptides at the same time as minoxidil. The minoxidil vehicle (prop glycol, ethanol) wrecks the copper complex. Space them by 4+ hours or apply on opposite schedules.", daysAgo: 53, reactions: { USEFUL: 10, AGREE: 6, THANKS: 4 } },
      { author: "goal_driven", body: "@hexaclinic this is the kind of detail I needed. Thank you.", daysAgo: 53, reactions: { THANKS: 3 } },
      { author: "cyclecraft", body: "Stay on the min/fin. The copper peptides are at best additive, not replacements. Anyone telling you otherwise is selling something.", daysAgo: 52, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "wanderlite", body: "Is the zinc thymulin the stuff that has to be freshly compounded each time? I keep reading it's unstable.", daysAgo: 50, reactions: {} },
      { author: "panel_maxer", body: "@wanderlite yes, it's notoriously unstable in solution. Either you buy single-use vials or you reconstitute small batches and use within a couple weeks refrigerated. That's the real barrier to running it.", daysAgo: 50, reactions: { USEFUL: 6, THANKS: 2 } },
      { author: "silentscroll", body: "Reading. 3 years on fin, considering copper peptides. Useful thread.", daysAgo: 48, reactions: { LIKE: 2 } },
      { author: "showmethestudy", body: "The original Pickart hair work on GHK-Cu is worth reading before you commit. Small trials, reasonable effect size, much less hype than the modern social media version.", daysAgo: 45, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "petal_push", body: "Can women run this stack? Asking because most hair loss threads default to male pattern.", daysAgo: 42, reactions: { LIKE: 2 } },
      { author: "reggae_fiend", body: "@petal_push GHK-Cu and zinc thymulin are fine for women topically. Finasteride is where the conversation changes. The copper peptides don't have the same hormone pathway concerns.", daysAgo: 42, reactions: { USEFUL: 6, THANKS: 3 } },
    ],
  },
  {
    title: "GHK-Cu + tretinoin — can I layer these or does the retinoid kill the copper?",
    body: "Running tret 0.05% nightly for years. Want to add GHK-Cu to the routine. Everything I read says 'don't combine with acidic actives' but tret isn't really acidic — it's a retinoid in a pH-neutralish vehicle usually.\n\nWhat's the actual interaction? Is it:\n(a) No problem, layer directly\n(b) Wait 20 minutes between\n(c) Alternate nights\n(d) Morning vs night\n\nCurrent routine: cleanser, tret, wait, moisturizer. Want to slot GHK-Cu serum somewhere in there without wasting the peptide.",
    author: "curious_catL",
    daysAgo: 30,
    views: 1340,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "hexaclinic", body: "The main copper-peptide-killer is low pH (vit C, AHA, BHA) because it protonates the histidine and drops the peptide's copper-binding affinity. Tret at the formulation pH (~5–6) is mostly fine. I do tret, wait 20 minutes, GHK-Cu, moisturizer. No interaction I've noticed.", daysAgo: 30, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "petal_push", body: "I alternate — tret Monday Wednesday Friday, GHK-Cu the other nights. Easier than timing them. Skin has been great for 6 months.", daysAgo: 29, reactions: { USEFUL: 4, LIKE: 2 } },
      { author: "theoretic", body: "The anxiety about 'degrading' GHK-Cu with adjacent products is overblown. If your routine isn't full of citric acid and ascorbic acid, you're fine. Tret is not the enemy here.", daysAgo: 29, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "reggae_fiend", body: "Morning GHK-Cu, evening tret is the simplest split and the one I'd start with. Lets you see if either is causing irritation in isolation.", daysAgo: 28, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "curious_catL", body: "Going with morning GHK, evening tret. Thanks all.", daysAgo: 27, reactions: { THANKS: 3 } },
      { author: "dr_doubt", body: "General principle that applies here: when combining two actives with independent mechanisms, the default should be temporal separation (AM/PM split) rather than layering. Easier to isolate irritation, easier to stop one.", daysAgo: 26, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "thread_saver", body: "Saved. Been wondering this exact question.", daysAgo: 22, reactions: { LIKE: 2 } },
      { author: "cautious_ox", body: "Does the GHK-Cu still work if I'm using an azelaic acid in the morning? That's low pH.", daysAgo: 18, reactions: {} },
      { author: "hexaclinic", body: "@cautious_ox azelaic is pH 4–5 which is borderline. I'd either apply it separately with a real gap (30+ min) or switch GHK-Cu to the opposite time of day.", daysAgo: 18, reactions: { USEFUL: 4 } },
    ],
  },

  // -------------------- QUIET --------------------
  {
    title: "Fine lines around eyes — is GHK-Cu actually doing anything or is this placebo",
    body: "4 months in on 0.1% GHK-Cu serum under eyes. I *think* the fine lines look softer but I'm honestly not sure if that's the peptide, the moisturizer I also started, or me staring at myself in better lighting. No before photos because I'm a fool.\n\nWhat's realistic for this peptide at this concentration? Am I expecting too much in 4 months, or is this where most people plateau?",
    author: "petal_push",
    daysAgo: 85,
    views: 680,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Realistic expectation: modest improvement in skin thickness and hydration over 8–16 weeks, visible fine line softening in some people, nothing dramatic. If you were expecting retinoid-level results you're on the wrong compound.", daysAgo: 85, reactions: { USEFUL: 6 } },
      { author: "theoretic", body: "4 months is fine. You're not going to get more result at 12 months than you got at 6. If you're seeing anything at all, that's the effect.", daysAgo: 84, reactions: { AGREE: 3 } },
      { author: "petal_push", body: "Okay, so 'modest improvement' is where I am. Good to calibrate expectations.", daysAgo: 83, reactions: { THANKS: 2 } },
      { author: "reggae_fiend", body: "GHK-Cu is a supporting actor, not a lead. It earns its place in a routine that also has retinoid and sunscreen, not as a standalone anti-aging tool.", daysAgo: 80, reactions: { AGREE: 4, USEFUL: 2 } },
    ],
  },
  {
    title: "Post-surgery scar reduction — 3 months of topical GHK-Cu results",
    body: "Had a shoulder scope in January. Started 0.2% GHK-Cu serum on the portal scars once they closed (week 3 post-op). Applied 2x/day for 12 weeks.\n\nResults: the scars are flatter and less red than I expected based on a previous surgery I had with no peptide. Whether that's the GHK-Cu or just 'young-ish body heals well' I can't say. No controls, obviously. But I'll do it again next time.\n\nNot injecting near the scar, just topical. The sub-q-for-scars crowd can fight me in the other thread.",
    author: "post_surgery_rr",
    daysAgo: 65,
    views: 890,
    reactions: { LIKE: 5, USEFUL: 3 },
    replies: [
      { author: "shoulder_spring", body: "Did the same after my rotator surgery. Portal scars barely visible at 6 months. Can't prove it was the peptide, but the cost was low and it didn't mess anything up.", daysAgo: 64, reactions: { LIKE: 3, USEFUL: 2 } },
      { author: "acl_again", body: "Saving for my next surgery. Going in for revision ACL in June.", daysAgo: 62, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "The post-surgical scar literature on GHK-Cu is one of the better-supported topical use cases. Not n=∞ but it's real. Start as soon as the incision is closed and re-epithelialized.", daysAgo: 60, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "tendon_theory", body: "Adds to the 'cheap and probably does something' column. I'll keep a vial around for next injury.", daysAgo: 55, reactions: { LIKE: 2 } },
    ],
  },
  {
    title: "'Blue skin' from GHK-Cu — is this a real risk or Reddit lore",
    body: "Keep seeing comments like 'be careful or you'll turn blue from the copper.' Is that a real thing from topical GHK-Cu, or are people confusing it with the argyria-style stories from oral colloidal silver / high-dose IV copper?\n\nI assume topical doses of GHK-Cu are orders of magnitude too low to cause systemic copper accumulation but I want to be sure before I commit to daily use.",
    author: "first_vial",
    daysAgo: 95,
    views: 720,
    reactions: { LIKE: 3 },
    replies: [
      { author: "theoretic", body: "Myth. Topical GHK-Cu at cosmetic concentrations delivers micrograms of copper at most. You'd need sustained high-dose IV copper or serious oral over-supplementation to get systemic copper toxicity. Not a real risk here.", daysAgo: 95, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "dr_doubt", body: "Argyria (blue skin from silver deposition) is a real condition and gets confused with 'copper will turn you blue.' Different metal, different mechanism, and even the copper version requires doses you can't hit topically.", daysAgo: 94, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "hexaclinic", body: "You can temporarily stain skin blue-green if you apply a very concentrated GHK-Cu solution and it oxidizes on the skin. That washes off. Not the same thing as metal deposition.", daysAgo: 93, reactions: { USEFUL: 6, THANKS: 2 } },
      { author: "first_vial", body: "Good to know. Proceeding with 0.1% serum daily.", daysAgo: 92, reactions: { THANKS: 2 } },
    ],
  },
  {
    title: "Cosmetic-grade vs research-grade GHK-Cu — does it matter for topical use?",
    body: "Cosmetic suppliers sell GHK-Cu premixed in a vehicle at 0.05–2%. Research suppliers sell it lyophilized as a raw powder for way cheaper per mg. I want the cheap route but I'm not sure if:\n\n1. The research-grade powder is actually the same molecule at the same purity\n2. Reconstituting it myself in a home kitchen introduces contamination risk for something going on my face\n3. I'm missing something obvious\n\nAnyone buying lyo and DIY-ing their serum from research suppliers?",
    author: "bac_water_noob",
    daysAgo: 50,
    views: 610,
    reactions: { LIKE: 2 },
    replies: [
      { author: "panel_maxer", body: "I do. Caveats: buy from a supplier that publishes a CoA with HPLC purity, reconstitute in a clean environment (isopropyl wipe everything, gloves, use preserved base), make small batches. The molecule is the molecule — purity is the only variable.", daysAgo: 50, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "hexaclinic", body: "Cosmetic-grade premixed also has the advantage of validated preservatives and stability testing. For face use specifically, 'research-grade in your kitchen' is fine for 2 weeks refrigerated, not fine for 6 months on a bathroom shelf.", daysAgo: 49, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "bac_water_noob", body: "Makes sense. Small batches it is.", daysAgo: 48, reactions: { THANKS: 2 } },
      { author: "mothra", body: "The cost differential is real — you can make a year of 0.1% serum from a single 100mg research vial for under $30. Just treat it like a compounding exercise and don't be gross.", daysAgo: 45, reactions: { LIKE: 3, USEFUL: 2 } },
    ],
  },
  {
    title: "Oral GHK-Cu capsules — waste of money?",
    body: "Saw a supplement brand selling oral GHK-Cu capsules with big 'anti-aging' claims. My understanding is tripeptides get destroyed in the stomach and this is basically charging $60 for expensive copper. Am I wrong?",
    author: "questions_mode",
    daysAgo: 110,
    views: 540,
    reactions: {},
    replies: [
      { author: "theoretic", body: "You're right. Oral tripeptides are almost entirely hydrolyzed in the gut. Any copper that survives is just copper. You can get that from beef liver for $2.", daysAgo: 110, reactions: { AGREE: 6, FUNNY: 4, USEFUL: 3 } },
      { author: "dr_doubt", body: "Waste of money. The oral peptide supplement category is 95% people charging a premium for 'peptide' on the label when what's surviving to circulation is amino acids or nothing.", daysAgo: 109, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "nullhypothesis", body: "If it could be taken orally it'd be a drug, not a $60 bottle of capsules with a website that won't tell you what the active dose is.", daysAgo: 108, reactions: { AGREE: 4, FUNNY: 3 } },
    ],
  },
  {
    title: "GHK-Cu into the microneedling channels — is this a real synergy",
    body: "Dermatologists sometimes apply GHK-Cu serum after microneedling to push it into the channels. In theory this delivers the peptide to the dermis way more effectively than passive topical.\n\nAnyone doing this at home with a dermaroller or dermastamp? How often is reasonable, and is there a concentration that's too high when you're effectively bypassing the barrier?",
    author: "late_bloomer_m",
    daysAgo: 120,
    views: 480,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Real synergy, with caveats. Microneedling creates ~0.5–1.5mm channels, and applying GHK-Cu immediately after gives you far better dermal delivery than passive diffusion. But: use a sterile serum only. DIY formulations with questionable preservation go from 'topical, probably fine' to 'bloodstream, definitely not fine' when you've just punctured your face.", daysAgo: 120, reactions: { USEFUL: 8, AGREE: 4 } },
      { author: "petal_push", body: "I do it every 4 weeks with a 0.5mm roller and a cosmetic-grade preserved serum. Skin tolerates it. Don't go deeper at home.", daysAgo: 118, reactions: { USEFUL: 4, LIKE: 2 } },
      { author: "reggae_fiend", body: "0.5mm max at home. Any deeper needs a provider. And don't use a DIY reconstituted serum with microneedling — this is the one case where you want the commercial stuff for sterility.", daysAgo: 115, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "dr_doubt", body: "Frequency: 4–6 weeks apart. Less often than you think. The skin needs to complete its remodeling cycle.", daysAgo: 112, reactions: { USEFUL: 4, AGREE: 3 } },
    ],
  },
];

// ============================================================
// Other Compounds — 14 threads (2 popular, 4 active, 8 quiet)
// ============================================================
export const THREADS_OTHER: SeedThread[] = [
  // -------------------- POPULAR --------------------
  {
    title: "DSIP for sleep — who's actually gotten something out of this",
    body: "Delta sleep-inducing peptide (DSIP) has been on the fringe of the sleep compound conversation for decades. The human literature is mostly old Russian and European work, and modern trials are basically non-existent. But every few months a new thread asks 'does DSIP work for sleep?' and the answers are all over the map.\n\nMy honest experience after 6 weeks at 100mcg sub-q 30 minutes before bed:\n- Deep sleep (measured by Oura, which is imperfect) up modestly from baseline — maybe 10–15 min average\n- Subjective sleep quality: better the nights I took it, but not dramatically\n- No morning grogginess, no dependency, no weird dreams\n- Stopped for 2 weeks: sleep regressed to baseline\n- Restarted: benefit returned\n\nFor me, file it under 'real but modest.' It's not ambien. It's not even really 'sedating.' It's more like it makes the sleep you're already having a little deeper.\n\nWho else has run this long enough to have an opinion? Specifically interested in people who tracked it with something objective (sleep study, Oura, Whoop) rather than pure vibes.",
    author: "restwise",
    daysAgo: 80,
    views: 3640,
    reactions: { LIKE: 12, USEFUL: 15, AGREE: 9, THANKS: 5 },
    replies: [
      { author: "dreamline", body: "Ran DSIP 100mcg nightly for 12 weeks with an Oura. Effect is real but small. Deep sleep +8 min on average, REM basically unchanged, total sleep +15 min. Subjective quality was the bigger win — I just felt more rested. Placebo possible but the washouts were persuasive.", daysAgo: 80, reactions: { USEFUL: 10, AGREE: 6 } },
      { author: "hexaclinic", body: "DSIP is one of those compounds where if you came in expecting a benzo you'll be disappointed, and if you came in expecting nothing you'll be mildly surprised. It's subtle.", daysAgo: 79, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "nad_nightowl", body: "I stack DSIP with low-dose melatonin (300mcg) and magnesium glycinate. The combo works better than any component alone. DSIP on its own was just okay for me.", daysAgo: 79, reactions: { USEFUL: 7, LIKE: 3 } },
      { author: "placebo_possible", body: "'Real but modest' is the honest answer for 90% of peptides. DSIP is no different. The 'I slept like a baby!' posts usually come from people on week 1 who haven't controlled for novelty.", daysAgo: 78, reactions: { AGREE: 11, USEFUL: 5 } },
      { author: "humanin_hope", body: "12 weeks, 150mcg. Deep sleep up, HRV up 4-5ms. Discontinued due to cost, sleep regressed by about the same amount. I'd run it again if it were cheaper.", daysAgo: 77, reactions: { USEFUL: 6, LIKE: 3 } },
      { author: "theoretic", body: "The mechanism isn't well-understood which makes dose and timing kind of guesswork. Most people converge on 100–200mcg 30–60 min pre-sleep, sub-q. I wouldn't go higher — there's no indication more is better.", daysAgo: 77, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "bpc_baby", body: "Does DSIP fix actual insomnia or just improve already-okay sleep? I fall asleep fine but I wake at 3am like clockwork.", daysAgo: 75, reactions: { LIKE: 2 } },
      { author: "restwise", body: "@bpc_baby in my experience it doesn't solve early-morning awakening. It deepens the sleep you have but doesn't lengthen it meaningfully. For 3am wakes I'd look at cortisol, alcohol, and blood sugar first.", daysAgo: 75, reactions: { USEFUL: 8, THANKS: 3 } },
      { author: "dr_doubt", body: "The age of the literature is a yellow flag, not a red one. A lot of good old Russian and German pharmacology never got replicated in modern Western trials because of funding priorities, not because the original work was wrong. Can't tell for sure which of the 'lost peptides' are real vs forgotten for good reason.", daysAgo: 74, reactions: { AGREE: 8, USEFUL: 6 } },
      { author: "epi_cycler", body: "DSIP fits into my longevity stack as a 'low cost, small benefit, low risk' adjunct. Not a headliner. I run it 5/2 with weekends off, 100mcg.", daysAgo: 72, reactions: { USEFUL: 5, LIKE: 2 } },
      { author: "citation_required", body: "What would convince me: a modern n=30+ crossover trial with polysomnography endpoints. We don't have that. Everything is self-reported or wearable-based. Which doesn't mean it's fake, just means we're still guessing on magnitude.", daysAgo: 70, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "showmethestudy", body: "Agree with citation_required. DSIP is in the category of 'plausibly effective, under-studied, probably safe at community doses, probably not a game-changer.' Which describes half the compounds on this forum.", daysAgo: 69, reactions: { AGREE: 9, USEFUL: 5, FUNNY: 3 } },
      { author: "slow_typer_s", body: "I tried it for a month and got nothing. But my sleep was already 90th percentile. Possible ceiling effect.", daysAgo: 66, reactions: { LIKE: 3, USEFUL: 2 } },
      { author: "reclusive_rn", body: "Running DSIP for jetlag resets (monthly international travel). For that use case specifically it's been the best tool I've tried, beats melatonin for me. YMMV.", daysAgo: 64, reactions: { USEFUL: 6, LIKE: 3 } },
      { author: "stackbuilder", body: "The jetlag use case @reclusive_rn mentions is interesting and I haven't seen it discussed. Might be the strongest argument for keeping DSIP on hand.", daysAgo: 62, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "wanderlite", body: "Noob question — is DSIP sub-q only or can it be oral / nasal?", daysAgo: 58, reactions: {} },
      { author: "restwise", body: "@wanderlite sub-q is what's been studied. Nasal has been explored in some experimental protocols but bioavailability data is sparse. Oral won't work — gets digested.", daysAgo: 58, reactions: { USEFUL: 5, THANKS: 2 } },
      { author: "just_observing", body: "Great thread. This is what I come here for.", daysAgo: 54, reactions: { LIKE: 4 } },
    ],
  },
  {
    title: "PT-141 dosing thread — let's compile what actually works vs 'just take 2mg and hope'",
    body: "PT-141 (bremelanotide) is a melanocortin agonist that hits MC3/MC4 receptors and does something for sexual arousal that Viagra and Cialis don't. But the dose window is narrow, the side effect profile is real, and the 'just take 2mg sub-q' advice you see everywhere is overdosing a lot of people.\n\nMy experience across ~15 doses:\n- 0.5mg: nothing noticeable\n- 1mg: desired effect, no side effects, sweet spot for me\n- 1.5mg: desired effect + mild flushing and nausea for 2 hours\n- 2mg: full-blown nausea, facial flushing, felt like I had low-grade flu for 4 hours, sexual effect not meaningfully stronger than 1mg\n\nThe FDA-approved injectable (Vyleesi) is 1.75mg which is close to my 'too much' line.\n\nInterested in:\n1. Where does YOUR dose window land, and does it vary by sex / body weight?\n2. Timing — the 2hr pre-action window is real, right?\n3. Anyone used nasal PT-141 instead of sub-q? Bioavailability guesses?\n4. Stacking with PDE5 inhibitors — synergy or redundant?\n5. Blood pressure — I've seen bumps of +10/5 at 1.5mg that take hours to come down. Anyone else monitoring?",
    author: "protocolpilot",
    daysAgo: 55,
    views: 2890,
    reactions: { LIKE: 8, USEFUL: 12, AGREE: 6 },
    replies: [
      { author: "hexaclinic", body: "Your dose curve matches what I hear from most men. 0.75–1.25mg is the working window for the majority. The 2mg advice online is a relic of older sourcing where potency was unreliable. With decent-purity product, 1mg is plenty.", daysAgo: 55, reactions: { USEFUL: 10, AGREE: 7 } },
      { author: "recomp_rex", body: "Female partner and I both use it. Her effective dose is about 40% lower than mine (0.6mg vs 1mg) and the side effect profile kicks in at correspondingly lower doses. Not sure if it's body weight or sex but it's consistent.", daysAgo: 54, reactions: { USEFUL: 8, LIKE: 4 } },
      { author: "slow_titrate", body: "Start at 0.5mg. Literally always. Even if 'everyone online says 1.75.' You cannot undo the nausea once it's on you, and going up by 0.25mg per session is trivial.", daysAgo: 54, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "theoretic", body: "Timing: the 2hr pre-use window is real for sub-q. Nasal is faster (~30–45 min) with lower peak plasma. Bioavailability for nasal is roughly 20–25% of sub-q based on the published PK work, so nasal doses need to be higher to hit the same effect window.", daysAgo: 53, reactions: { USEFUL: 9, AGREE: 4 } },
      { author: "protocolpilot", body: "@theoretic thanks — that's the cleanest nasal summary I've seen.", daysAgo: 53, reactions: { THANKS: 3 } },
      { author: "dr_doubt", body: "BP monitoring is underrated. Melanocortin agonism transiently raises BP. If you have baseline hypertension or you're on anything that stacks with it (stimulants, sympathomimetics), the risk profile changes. Not a deal-breaker but worth knowing.", daysAgo: 52, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "mothra", body: "PDE5 inhibitor + PT-141 combo: not redundant, they hit different parts of the arousal pathway (central vs peripheral). Can be complementary. Can also stack cardiovascular load. Start one at a time, find dose, then combine cautiously.", daysAgo: 52, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "nopain_noreign", body: "I use it for the PDE5-refractory cases. Men who don't respond to Cialis often do respond to PT-141 because the issue is central not peripheral. Matters for diagnosis as much as treatment.", daysAgo: 51, reactions: { USEFUL: 9, AGREE: 4, LIKE: 3 } },
      { author: "frontloader", body: "Flushing is the most reliable side effect. If you don't flush you're probably under-dosed or the product isn't good.", daysAgo: 50, reactions: { AGREE: 5, USEFUL: 3 } },
      { author: "syringe_shy", body: "Is the flushing dangerous or just uncomfortable?", daysAgo: 48, reactions: {} },
      { author: "hexaclinic", body: "@syringe_shy uncomfortable. Not dangerous at standard doses in a healthy person. If you have rosacea it's going to be ugly for a couple hours.", daysAgo: 48, reactions: { USEFUL: 5, FUNNY: 3 } },
      { author: "reggae_fiend", body: "Don't mix with alcohol. The nausea vector is a lot worse and the BP response becomes unpredictable. Learned the hard way.", daysAgo: 46, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "protocolwonk", body: "Nasal has been fine for me at 2–3mg sprayed (which matches the ~25% bioavailability math for my 1mg sub-q equivalent). Faster onset, less nausea, slightly weaker peak effect.", daysAgo: 44, reactions: { USEFUL: 5, LIKE: 2 } },
      { author: "cyclecraft", body: "Don't use it daily. Tachyphylaxis is real with melanocortin agonists. 1–2x/week max, take long gaps. Treat it like an event drug not a daily.", daysAgo: 42, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "citation_required", body: "Vyleesi label dose is 1.75mg and the label specifically notes the nausea rate. That's FDA-tested, and still a third of women on-label report nausea. Community 'start at 2mg' advice is ignoring the label of the only approved version.", daysAgo: 40, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "stackbuilder", body: "Best thread on this compound I've seen here. Pinning in my personal notes.", daysAgo: 38, reactions: { LIKE: 3, THANKS: 2 } },
      { author: "thread_saver", body: "Saved.", daysAgo: 35, reactions: { LIKE: 2 } },
    ],
  },

  // -------------------- ACTIVE --------------------
  {
    title: "AOD-9604 — cool name, does it do literally anything?",
    body: "AOD-9604 is marketed as 'the fat-burning fragment of growth hormone.' The origin story is that it's the C-terminal fragment of hGH (176-191) that supposedly retains the lipolytic effect without the growth effects. It failed its weight-loss Phase 2 trials about 15 years ago and the drug development essentially died.\n\nYet it's still sold everywhere in the peptide space, usually at 300mcg daily, with people claiming body recomp effects. My read is that it doesn't do much in humans at reasonable doses, and the Phase 2 failure is a pretty loud signal that this isn't a real fat-loss tool.\n\nHas anyone actually measured body comp changes on AOD-9604 with DEXA or at least a decent scale and waist tape? Or is this 100% vibes?",
    author: "fat_loss_log",
    daysAgo: 45,
    views: 1780,
    reactions: { LIKE: 4, USEFUL: 4 },
    replies: [
      { author: "theoretic", body: "The Phase 2 failure is the whole story. If a compound couldn't beat placebo in a funded trial with proper endpoints, the bar for 'it's actually working in my kitchen at 300mcg' is very high. I don't think AOD does anything meaningful for fat loss.", daysAgo: 45, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "dr_doubt", body: "AOD-9604 is the peptide space's 'failed drug that found a second life because people didn't get the memo.' Nothing wrong with experimenting but calibrate expectations to 'probably placebo.'", daysAgo: 45, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "dexa_devotee", body: "I DEXA-scanned before and after a 12-week AOD run (300mcg AM fasted). Body fat change: -0.3%, within measurement noise. Lean mass unchanged. I'd call that no effect.", daysAgo: 44, reactions: { USEFUL: 10, AGREE: 5 } },
      { author: "tirzepatide_tim", body: "The people selling AOD now are the same ones who couldn't sell you a GLP-1 because the margin isn't there. Follow the margin.", daysAgo: 44, reactions: { FUNNY: 6, AGREE: 5 } },
      { author: "plateau_breaker", body: "I ran it alongside a cut and thought it did something. Now I'm pretty sure I was just in a deficit. Removed it from my stack and the deficit kept working.", daysAgo: 42, reactions: { USEFUL: 5, FUNNY: 3, AGREE: 3 } },
      { author: "fat_loss_log", body: "This is what I needed. Saving the money.", daysAgo: 41, reactions: { THANKS: 3 } },
      { author: "showmethestudy", body: "Every once in a while someone tries to revive AOD with 'but it's cAMP-mediated lipolysis!' The mechanism claim was always fine. The in vivo result was always weak.", daysAgo: 40, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "slow_lose", body: "GLP-1s made this compound irrelevant even if it worked. Risk-adjusted return of AOD vs a microdose tirz for fat loss isn't close.", daysAgo: 38, reactions: { AGREE: 7 } },
      { author: "pallet_jack", body: "I'll be the contrarian. Ran 500mcg AM for 8 weeks, appetite was noticeably blunter and I dropped 3lb that I didn't expect. n=1, no bloods, take it for what it's worth.", daysAgo: 35, reactions: { LIKE: 2, USEFUL: 2 } },
      { author: "theoretic", body: "@pallet_jack appreciate the honest counterpoint. Appetite suppression isn't in the canonical AOD mechanism claim though — that's usually a GLP-1-like effect. Possible it's acting through a different pathway at higher dose, or possible it's a placebo + natural variance.", daysAgo: 35, reactions: { USEFUL: 5, AGREE: 3 } },
    ],
  },
  {
    title: "IGF-1 LR3 — who's actually running this and at what dose",
    body: "IGF-1 LR3 is one of those compounds you see mentioned as a 'serious' peptide but almost no one talks honest doses and effects. Half the posts are either 'I'm running 100mcg daily' (unhinged) or 'it did nothing at 20mcg ED' (probably underdosed).\n\nFor those who've actually run this:\n- Dose range you settled on?\n- Daily vs EOD vs post-workout only?\n- Hypoglycemia — how often, how bad, did you adjust diet?\n- Bloodwork changes — IGF-1 serum actually moves on LR3 or does it stay site-local?\n- Any nodule / nerve / organ concerns long-term?\n- What did you notice that made you think it was actually working (recovery? growth? sleep?)\n\nNot looking for sourcing. Looking for honest n=1 on the compound.",
    author: "cyclecraft",
    daysAgo: 35,
    views: 1620,
    reactions: { LIKE: 5, USEFUL: 3 },
    replies: [
      { author: "hexaclinic", body: "Running it at all? I'd push back gently. The risk profile on LR3 — particularly the theoretical proliferative risk with extended use — is a different conversation than BPC or GHK-Cu. Not saying don't, saying do it with eyes open and a short cycle.", daysAgo: 35, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "igf_curve", body: "30mcg post-workout only, 4-5x/week, 8 week cycle. Serum IGF-1 bumped ~20% which surprised me (LR3 isn't supposed to move serum much but at the upper dose range it does). Strength went up, recovery was faster. Off for 12 weeks between cycles.", daysAgo: 34, reactions: { USEFUL: 9, LIKE: 4 } },
      { author: "theoretic", body: "Split into bilateral injection sites to avoid the 'giant muscle on one side' effect people don't take seriously. LR3 is systemic enough that this matters less than with regular IGF-1 but site-local growth is still a thing at higher doses.", daysAgo: 34, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "frontloader", body: "Hypo risk is real. I eat 30g fast carb within 5 min of the injection. Never had a bad episode but I've felt the pre-hypo warning twice — tunnel vision, sweat. Take it seriously.", daysAgo: 33, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "dr_doubt", body: "The long-term proliferative concern isn't theoretical if you have any family history of IGF-sensitive cancers. Colorectal and prostate specifically. If you have that history, this isn't the compound for you.", daysAgo: 32, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "cyclecraft", body: "Good data points. My plan was 20mcg post-workout, 4 days/week, 6 week cycle with full washout. Sounds like that's conservative enough given the replies here.", daysAgo: 32, reactions: { THANKS: 3 } },
      { author: "protocolwonk", body: "LR3 vs DES-IGF: DES has a shorter half-life and tends to stay more site-local. If you want the localized effect, DES. If you want the systemic boost, LR3. They're different tools.", daysAgo: 30, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "reggae_fiend", body: "The strength bump is real on LR3 for me. The mass bump was less dramatic than the marketing suggests. Short cycles, big gaps. Anyone running this year-round is playing a different game.", daysAgo: 28, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "cbc_cmp", body: "Pull fasting glucose + insulin + HbA1c before and after cycle. Insulin sensitivity can shift meaningfully and it's worth seeing.", daysAgo: 25, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "nullhypothesis", body: "The honest bar for running this: do you have hypertrophy goals that standard MPS stacks + training can't hit? If no, this isn't for you. Proliferative peptides shouldn't be the first tool out of the box.", daysAgo: 22, reactions: { AGREE: 7, USEFUL: 4 } },
    ],
  },
  {
    title: "Selank vs Semax for anxiety — I've tried both, here's how they're actually different",
    body: "Tried both Russian nasal peptides for generalized anxiety over the last year. People online tend to lump them together as 'nootropic anxiolytics' but they're very different in practice.\n\n**Semax** (ACTH fragment, 4-7 or 4-10 versions): more cognitive. Sharper focus, better working memory, mild mood lift. For anxiety specifically it's indirect — I felt 'capable' which reduced anxiety, rather than feeling 'calm.' Stimulating-ish. Not great late in the day.\n\n**Selank** (TP-7 fragment): more directly anxiolytic. Less cognitive boost, more 'the edge comes off.' Subtle, no sedation, no dullness. Can take it later in the day without sleep issues.\n\nMy current use: Selank 2-3 sprays per nostril on high-anxiety days, Semax on days I need cognitive performance. Not daily. Both seem to lose effect if used too often — I think receptor habituation is real here.\n\nInterested in people with different experiences, especially if you've found them swappable or if one did nothing for you.",
    author: "selank_silence",
    daysAgo: 28,
    views: 1480,
    reactions: { LIKE: 6, USEFUL: 7, AGREE: 4 },
    replies: [
      { author: "semax_mornings", body: "Exactly matches my experience. Semax is a 'I can do this' feeling. Selank is 'I don't need to do this right now.' Different problems, different tools.", daysAgo: 28, reactions: { AGREE: 8, USEFUL: 4, FUNNY: 3 } },
      { author: "pde_brainer", body: "Semax hits dopamine/BDNF pathways pretty hard for a short peptide. The 'capable' feeling you describe is probably dopaminergic. Selank is more GABAergic/serotonergic, hence the anxiolytic tilt.", daysAgo: 27, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "noots_noop", body: "Ran Semax daily for 6 weeks and it absolutely stopped working by week 3. Intermittent use is not optional — it's required. Same thing happened with Selank at 3 weeks.", daysAgo: 27, reactions: { USEFUL: 6, AGREE: 5 } },
      { author: "cerebrolysin_cb", body: "The 'Russian peptide' family is underrated in general. Selank especially — it's the one I'd keep in a drawer for situational anxiety over any benzo. No dependence profile, no cognitive dulling.", daysAgo: 26, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "selank_silence", body: "@noots_noop yes, I should have said — mine is cycled aggressively. 5 days on, 9 days off roughly. Continuous dosing kills it.", daysAgo: 26, reactions: { AGREE: 3, THANKS: 2 } },
      { author: "dihexa_doubter", body: "Storage matters more than people admit. Selank and Semax both degrade fast in solution at room temp. If you reconstitute a vial and leave it on the counter for 3 weeks, by week 3 it's 50% dead. Refrigerate or don't bother.", daysAgo: 25, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "dr_doubt", body: "Useful distinction. I'll add: if you have GAD and you're looking for a daily tool, neither of these is that. They're situational. If you need daily anxiolysis, have the conversation with a clinician.", daysAgo: 24, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "late_bloomer_m", body: "Selank killed my anxiety before a public presentation and I didn't feel drugged. That was the moment I got the point of it.", daysAgo: 22, reactions: { LIKE: 3, USEFUL: 2 } },
      { author: "petal_push", body: "Nasal administration — any tricks? I feel like half my dose drips out.", daysAgo: 20, reactions: {} },
      { author: "semax_mornings", body: "@petal_push slow sprays, one nostril at a time, head slightly tilted back but not fully horizontal, breathe in through the nose as you spray. Don't sniff hard — you'll send it down the throat. Two sprays per nostril, wait 2 minutes, second round if needed.", daysAgo: 20, reactions: { USEFUL: 7, THANKS: 4 } },
    ],
  },
  {
    title: "Epithalon protocol variations — 10 days on / months off vs the longer runs",
    body: "Canonical epithalon protocol is 10 consecutive days of 5–10mg sub-q, 1-2x per year. This traces back to the Khavinson work out of St. Petersburg. But I see variations now:\n\n- 10mg daily for 20 days\n- 5mg every other day for 30 days\n- 2.5mg daily continuous for months\n- 'Pulsed' — 5 days on, 5 days off, repeated 4 times\n\nIs there any rational basis for the variations or are people just freelancing? The original protocol has a rationale (matching the observed telomerase induction window from the rodent work). Extending it longer with no dosing evidence is just hoping.\n\nMy plan is the canonical 10 days @ 10mg, once this year, with telomere length testing before and 6 months after. Anyone run similar and have actual data?",
    author: "epi_cycler",
    daysAgo: 60,
    views: 1210,
    reactions: { LIKE: 3, USEFUL: 3 },
    replies: [
      { author: "telomere_t", body: "I did the canonical 10-day protocol with TeloYears testing pre and 6 months post. My 'telomere age' dropped 3 years which is within the test's noise band. I can't claim the protocol worked, I can claim it didn't obviously fail. The test itself is the bigger confound.", daysAgo: 60, reactions: { USEFUL: 7, LIKE: 3 } },
      { author: "theoretic", body: "The longer protocols are freelancing. The Khavinson work specifically identified the pulse-and-pause cycle as part of the mechanism — telomerase doesn't want to be on continuously. Extending past 20 days might actively reduce the effect.", daysAgo: 59, reactions: { USEFUL: 8, AGREE: 4 } },
      { author: "nad_nightowl", body: "Running annual 10-day pulses for 3 years now. No measured telomere data but subjective sleep and recovery have been good. Not attributing either to epithalon specifically.", daysAgo: 58, reactions: { USEFUL: 4, LIKE: 2 } },
      { author: "humanin_hope", body: "Telomere length testing (FlowFISH, qPCR variants) has large intra-individual variability. Without repeat draws a single before/after comparison is nearly useless. You need 3 baseline draws over a year to even establish your noise floor.", daysAgo: 57, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "epi_cycler", body: "@humanin_hope good point — that kills my one-shot data plan. Might skip the testing.", daysAgo: 57, reactions: { THANKS: 2 } },
      { author: "dr_doubt", body: "Epithalon is one of the compounds where 'it's very safe, probably doesn't do much in humans at our doses' is the honest answer. The rodent work is elegant. The human extrapolation is a leap.", daysAgo: 55, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "stack_nerd", body: "Dosing route question — some people do 5mg AM and PM split vs one big dose. Any reason to prefer one?", daysAgo: 52, reactions: {} },
      { author: "theoretic", body: "@stack_nerd half-life is short (~2-3 hours) so split dosing gives you more consistent tissue exposure. If it matters at all, AM/PM is better than one dose. If it doesn't matter, neither matters.", daysAgo: 52, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "showmethestudy", body: "If you're going to run an anti-aging peptide with the evidence level of epithalon, run the canonical protocol. Don't improvise — it makes your n=1 uninterpretable even to yourself.", daysAgo: 48, reactions: { AGREE: 6, USEFUL: 3 } },
    ],
  },

  // -------------------- QUIET --------------------
  {
    title: "Dihexa — is anyone actually running this safely",
    body: "Dihexa keeps coming up in nootropic circles as '7 orders of magnitude more potent than BDNF for synaptic formation.' That's the kind of claim that should make anyone pause. It's also never been in a human trial and the preclinical work is almost all from one lab.\n\nI'm not planning to take it. I'm asking because I want to understand what 'running it safely' even means for a compound with no human data. Is it literally just 'low dose, hope for the best'?",
    author: "dihexa_doubter",
    daysAgo: 115,
    views: 690,
    reactions: { LIKE: 3 },
    replies: [
      { author: "dr_doubt", body: "'Running it safely' with no human data means 'running it at your own risk with a blind spot for anything that goes wrong.' That's not safety, that's acknowledging you're in the experimental dark.", daysAgo: 115, reactions: { AGREE: 8, USEFUL: 5 } },
      { author: "cardinal_rule", body: "Mod reminder: we've had conversations about dihexa that crossed into encouraging unsupervised experimentation. Keep discussion to mechanism and risk framing, not 'here's how to dose it.'", daysAgo: 114, reactions: { AGREE: 6, THANKS: 3 } },
      { author: "theoretic", body: "The one-lab problem is the big flag. It's not that the work is bad, it's that nobody's replicated. For a compound this potent this would be Nobel territory if the claims held up independently. They haven't been tested independently.", daysAgo: 113, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "nullhypothesis", body: "Skip it. Genuinely. The signal-to-risk ratio is terrible.", daysAgo: 110, reactions: { AGREE: 9 } },
    ],
  },
  {
    title: "Kisspeptin-10 for HPTA restart after a long cycle — anyone run this?",
    body: "Kisspeptin-10 is upstream of GnRH in the HPTA axis. The theoretical appeal for post-cycle recovery is that it kicks the whole cascade off at the top rather than from the pituitary downward (like clomid/enclomiphene at the hypothalamus level but via a different receptor).\n\nHas anyone used kisspeptin-10 as part of a PCT or HPTA restart protocol, and did it do anything clomid / HCG / enclomiphene weren't already doing?",
    author: "cycle_wrangler",
    daysAgo: 70,
    views: 510,
    reactions: { LIKE: 2 },
    replies: [
      { author: "theoretic", body: "Short half-life is the main practical issue — kisspeptin-10 is pulsatile and the existing endogenous release is pulsatile too. You're trying to mimic something your body would do if it weren't suppressed. Protocols I've seen are sub-q bolus but I'm skeptical that matches endogenous physiology.", daysAgo: 70, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "hexaclinic", body: "Interesting idea, no robust PCT evidence. Enclomiphene does the job in 90% of cases. Kisspeptin-10 is a tool looking for a problem when the existing toolkit works.", daysAgo: 69, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "panel_maxer", body: "LH response to kisspeptin-10 is real and measurable in the published work. But that's different from 'accelerates HPTA recovery after suppression.' Different endpoint.", daysAgo: 66, reactions: { USEFUL: 4, AGREE: 2 } },
    ],
  },
  {
    title: "Follistatin / FS-344 — is anyone really using this for hypertrophy?",
    body: "Follistatin gene therapy (AAV-FS344) has been floated in research for muscular dystrophy. The peptide analogs sold in the gray market are different things and the 'follistatin 344' vials out there are almost certainly not the gene therapy.\n\nAnyone actually running peptide follistatin and seeing anything? My guess is the answer is 'no, it's a branding exercise' but I'm open to being corrected.",
    author: "frontloader",
    daysAgo: 90,
    views: 440,
    reactions: { LIKE: 2 },
    replies: [
      { author: "dr_doubt", body: "The gene therapy is not the peptide. The peptide bioavailability is poor even if purity is good. 'FS-344' sold as a peptide is closer to a marketing SKU than a real research tool.", daysAgo: 90, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "theoretic", body: "Myostatin inhibition via peptide follistatin in humans: no good evidence. Real myostatin inhibitors that have shown muscle gain are all biologics in clinical trials, not this.", daysAgo: 88, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "recomp_rex", body: "Ran a full cycle of gray-market 'follistatin' and noticed nothing beyond the training gains I'd expect anyway. Waste of money for me.", daysAgo: 82, reactions: { USEFUL: 3, FUNNY: 2 } },
    ],
  },
  {
    title: "Cerebrolysin — the cost is insane. Is it worth it?",
    body: "Cerebrolysin is a porcine-brain-derived neuropeptide preparation used in Europe for stroke, TBI, and dementia. In those indications the evidence is... okay. Not great, not nothing. Effect sizes are modest.\n\nThe community uses it for nootropic purposes at IM doses for 10-20 day cycles. A single cycle costs hundreds of dollars.\n\nAnyone run full cycles and think it was worth the money compared to, say, running semax on/off for six months for the same cost?",
    author: "cerebrolysin_cb",
    daysAgo: 105,
    views: 420,
    reactions: { LIKE: 2 },
    replies: [
      { author: "noots_noop", body: "Did one 20-day cycle. Mild subjective lift during, nothing persistent after. For the cost I'd rather have six months of semax intermittent.", daysAgo: 105, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "theoretic", body: "The clinical use case is post-stroke/TBI. For someone with actual neural injury, the risk-reward is different. For a healthy brain chasing nootropic effects, it's probably overkill and under-powered for what it costs.", daysAgo: 103, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "pde_brainer", body: "Agree with noots_noop. The cycle feels meaningful in the moment, washes out fast after. Not sustainable economically and the sustained benefit hasn't shown up for me.", daysAgo: 100, reactions: { USEFUL: 3 } },
      { author: "dr_doubt", body: "If you have a TBI history, talk to a neurologist about it, not the forum. Outside that indication it's an expensive lottery ticket.", daysAgo: 96, reactions: { AGREE: 5, USEFUL: 3 } },
    ],
  },
  {
    title: "MOTS-c dose debates — 10mg weekly vs 5mg 2x week vs daily microdose",
    body: "MOTS-c is a mitochondrial-derived peptide with metabolic and exercise-mimetic claims. Protocols vary wildly:\n\n- 10mg once a week (the 'pulse' school)\n- 5mg twice a week (the 'split' school)\n- 1–2mg daily (the 'microdose' school)\n\nHalf-life is modest (~5 hours from what I can find) which argues against once-weekly, but the downstream metabolic effects might be longer-acting than serum presence suggests.\n\nAnyone with measurable metabolic changes on one of these and not the others?",
    author: "motsc_ops",
    daysAgo: 75,
    views: 490,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hba1c_watch", body: "Ran 5mg 2x weekly for 12 weeks. HbA1c moved from 5.4 to 5.2, fasting insulin from 8 to 6. Can't isolate from my training changes in the same period. Possibly real, possibly noise.", daysAgo: 75, reactions: { USEFUL: 5, LIKE: 2 } },
      { author: "theoretic", body: "The mitochondrial biogenesis pathway is more about chronic signaling than peak concentration. Daily microdose has a theoretical argument but the cost is higher. I think split twice-weekly is the pragmatic compromise.", daysAgo: 74, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "epi_cycler", body: "Pulse (10mg weekly) worked fine for me subjectively. The short half-life argument assumes effects track serum concentration, which for pathway-activating peptides isn't always true.", daysAgo: 70, reactions: { USEFUL: 3, AGREE: 2 } },
      { author: "nad_nightowl", body: "Stacking MOTS-c with NAD+ precursors is trendy. I don't see a good mechanistic argument for synergy beyond 'both are mitochondrial.' Haven't tested directly.", daysAgo: 65, reactions: { LIKE: 2 } },
    ],
  },
  {
    title: "KPV — alpha-MSH fragment for gut inflammation, any experiences?",
    body: "KPV is a three amino acid fragment of alpha-MSH (lys-pro-val) with anti-inflammatory properties in gut models. Some IBD sufferers are using it oral (enteric coated) or rectal to target local gut inflammation. Unusual in that it's one of the few peptides where oral is plausibly the right route.\n\nAnyone using this for IBS/IBD symptoms? Dose, route, results? Not medical advice stuff — just community experience.",
    author: "joint_hunter",
    daysAgo: 85,
    views: 370,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "KPV is one of the more interesting 'unexplored use case' peptides. The gut anti-inflammatory data is real in preclinical models. For oral route, it's one of the few where the tripeptide is stable enough to have a shot at reaching the colon intact, especially if enteric coated.", daysAgo: 85, reactions: { USEFUL: 4, AGREE: 2 } },
      { author: "bpc_baby", body: "I ran KPV 500mcg oral daily for 6 weeks for mild IBS. Symptoms improved. Hard to separate from dietary changes I made at the same time. Not a controlled trial on myself.", daysAgo: 82, reactions: { USEFUL: 3, LIKE: 2 } },
      { author: "theoretic", body: "Rectal administration for localized colonic effect makes the most mechanistic sense for distal gut. Not glamorous but probably the most direct delivery.", daysAgo: 78, reactions: { USEFUL: 3, AGREE: 2 } },
    ],
  },
  {
    title: "Thymosin Alpha-1 for chronic immune issues — worth the cost?",
    body: "Thymosin Alpha-1 (TA-1, Zadaxin) is an immune modulator used in Asia and parts of Europe for hepatitis and as an adjunct for immunocompromised patients. It's expensive and obscure in the US but some people use it for chronic immune dysfunction — recurrent viral reactivation, long-COVID symptoms, etc.\n\nAnyone run TA-1 long enough to have an opinion, and did bloodwork (CD4/CD8 ratios, CBC diff, inflammatory markers) actually move?",
    author: "crp_cassandra",
    daysAgo: 95,
    views: 410,
    reactions: { LIKE: 2, USEFUL: 1 },
    replies: [
      { author: "hexaclinic", body: "TA-1 is one of the few immunomodulators where the clinical evidence is respectable — it's on the essential medicines list in multiple countries. For chronic viral reactivation specifically the case is reasonable. Dose is typically 1.6mg sub-q twice weekly.", daysAgo: 95, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "panel_maxer", body: "CD4/CD8 ratio moved in a positive direction for me (was inverted, moved toward normal) over 16 weeks at 1.6mg 2x/week. Stopped chasing chronic illness labels and focused on functional metrics. Cost is real.", daysAgo: 92, reactions: { USEFUL: 6, LIKE: 3 } },
      { author: "dr_doubt", body: "If you have actual documented immune dysfunction (low NK activity, chronic EBV reactivation, etc) TA-1 has an evidence-backed argument. For 'I feel tired sometimes' it's overkill.", daysAgo: 88, reactions: { AGREE: 5, USEFUL: 3 } },
    ],
  },
  {
    title: "5-Amino-1MQ — NNMT inhibitor, anyone running this for recomp?",
    body: "5-Amino-1MQ is a small molecule NNMT (nicotinamide N-methyltransferase) inhibitor that's been pitched as an adipocyte-targeting 'increase-NAD-available-for-everything-else' tool. Unlike most things on this forum it's not a peptide — it's a pyridine analog.\n\nMechanism is plausible but the hype-to-evidence ratio feels extreme. Has anyone run this for 3+ months at clinically referenced doses and measured anything (body comp, NAD, methylation markers)?",
    author: "homocystein_x",
    daysAgo: 125,
    views: 430,
    reactions: { LIKE: 2, USEFUL: 1 },
    replies: [
      { author: "theoretic", body: "Preclinical data in adipocyte models is genuinely interesting — selective NNMT inhibition in fat tissue is a novel mechanism. Human data is basically zero. What's being sold is extrapolated from mouse work.", daysAgo: 125, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "nad_nightowl", body: "Ran 150mg daily for 10 weeks alongside a clean cut. Dropped fat, but I can't attribute it to 5A1MQ over the deficit. My methylation markers (SAM/SAH) didn't meaningfully move.", daysAgo: 122, reactions: { USEFUL: 4, LIKE: 2 } },
      { author: "dexa_devotee", body: "If you're going to run it, DEXA before and after, measure waist weekly. Otherwise you'll convince yourself it worked when the deficit was doing the work.", daysAgo: 118, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "nullhypothesis", body: "Small molecule, oral, mouse data only, sold as a supplement — that's the profile of three dozen failed compounds. Not saying this one's fake, saying the genre has a bad track record.", daysAgo: 112, reactions: { AGREE: 5, USEFUL: 3 } },
    ],
  },
];
