import type { SeedThread } from "../types";

// ============================================================
// RETATRUTIDE — 10 threads
// ============================================================
export const THREADS_RETATRUTIDE: SeedThread[] = [
  // ---------- POPULAR (2) ----------
  {
    title: "Reta vs tirze — 16 weeks in, the efficacy jump is not subtle",
    body: "Ran tirze 2.5 → 10mg over 20 weeks last year. Lost 28lb, plateaued hard at 10mg, couldn't push further without brutal GI. Swapped to retatrutide 8 weeks ago after a 3-week washout.\n\nStats: 38M, started reta at 206lb (had regained 6 of the 28). Currently 187lb. That's 19lb in 8 weeks — more than tirze gave me in the back half combined.\n\nTitration: 2mg w1-2, 4mg w3-4, 6mg w5-6, 8mg w7-8. Next week going to 10mg.\n\nSubjective: appetite suppression is 'I forget to eat' territory, not 'I eat less.' That's different from tirze, which felt like 'food stops being interesting.' Reta is a step past that. Also — and this is the part nobody prepared me for — the thermogenic feel is real. I sweat more. Resting HR up ~6bpm. Running warmer in general.\n\nGI was rougher than tirze on the jump to 6 but settled. On 8mg right now I feel basically normal.\n\nCuriosity check — anyone else feeling the GCG component as an actual subjective thing, or am I pattern-matching?",
    author: "retatrutide_r",
    daysAgo: 42,
    pinned: false,
    locked: false,
    views: 7240,
    reactions: { LIKE: 19, USEFUL: 15, THANKS: 8, AGREE: 11 },
    replies: [
      { author: "tirzepatide_tim", body: "The 'forget to eat' vs 'food stops being interesting' distinction is real. I ran tirze for 14 months and that's exactly how I'd describe it. Interested to hear the plateau experience at higher reta doses, because that's where I expect the divergence to show.", daysAgo: 42, reactions: { AGREE: 9, USEFUL: 4 } },
      { author: "plateau_breaker", body: "You said HR up 6bpm — resting or average? And did you track BP? The GCG arm should be doing some cardiovascular stuff and that's the part I watch.", daysAgo: 42, reactions: { LIKE: 4 } },
      { author: "retatrutide_r", body: "@plateau_breaker resting from Oura, averaged over baseline month vs current. BP went from 118/74 to 122/78. Not alarmed yet but watching. I'll draw a full CMP + lipids at week 12 to see what else moved.", daysAgo: 41, reactions: { USEFUL: 7, LIKE: 3 } },
      { author: "hexaclinic", body: "The thermogenic report tracks with GCG receptor activation — glucagon increases resting energy expenditure in every study that measured it. Not pattern matching. You're feeling the mechanism.", daysAgo: 41, reactions: { AGREE: 11, USEFUL: 9 } },
      { author: "sema_saturday", body: "This is the first report I've read where someone actually did the tirze-then-reta comparison with numbers rather than 'reta hits harder bro.' Saving.", daysAgo: 41, reactions: { LIKE: 6, THANKS: 3 } },
      { author: "showmethestudy", body: "Want to temper this — the phase 2 trial showed ~24% weight loss at 48 weeks on 12mg. That's ceiling data, not 8-week extrapolation. You may be ahead of schedule because your body already adapted to incretin receptor activation from a year on tirze. Different starting point.", daysAgo: 41, reactions: { AGREE: 12, USEFUL: 7 } },
      { author: "retatrutide_r", body: "@showmethestudy fair and I don't think I'll hold this pace. My expectation is the next 8 weeks are 8-10lb, not 19. Going in eyes open.", daysAgo: 40, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "macrosguru", body: "Protein intake during this? The thing I worry about on reta particularly is lean mass preservation when appetite is suppressed hard enough that you forget to eat.", daysAgo: 40, reactions: { LIKE: 3 } },
      { author: "retatrutide_r", body: "@macrosguru 180g protein minimum. I meal-replace with whey + casein blend when solid food isn't happening. It's the non-negotiable of this protocol for me.", daysAgo: 40, reactions: { USEFUL: 8, AGREE: 4 } },
      { author: "microdose_glp1", body: "Interesting that the GI settled on 8 but was rough on the 6 jump. My theory — and I've seen this on sema and tirze — is the GI is worst at the *first exposure to that dose* and your body adapts at each step. So the 6mg jump was your body meeting the new ceiling, and 8 is just incremental.", daysAgo: 39, reactions: { USEFUL: 6, AGREE: 5 } },
      { author: "cyclecraft", body: "Would you titrate the same way for someone who hasn't done tirze first? I suspect a GLP-naive person needs to crawl 2 → 4 slower.", daysAgo: 39, reactions: { LIKE: 3 } },
      { author: "retatrutide_r", body: "@cyclecraft yes. For GLP-naive I'd say 4 weeks at 2mg, 4 at 4mg, then evaluate. The 2-week jumps are because I already had the machinery tuned from tirze. Naive people will puke.", daysAgo: 39, reactions: { USEFUL: 9, AGREE: 6 } },
      { author: "glp1_doctor_pt", body: "The cardiovascular point is the one the board hasn't caught up on yet. Reta's GCG arm is novel territory — the trials haven't fully characterized long-term BP/HR trajectories in non-diabetic weight loss populations. Draw bloods. Track HR trend. Don't fly blind.", daysAgo: 38, reactions: { AGREE: 10, USEFUL: 7 } },
      { author: "slow_lose", body: "19lb in 8 weeks is bananas honestly. Even for someone with tirze tolerance baked in. I did 9lb in 8 weeks on sema at comparable starting weight.", daysAgo: 37, reactions: { LIKE: 4 } },
      { author: "fat_loss_log", body: "Following. Subscribed. Drop the week 12 bloodwork post please.", daysAgo: 35, reactions: { LIKE: 5 } },
      { author: "nullhypothesis", body: "One report, one subject, no control for diet changes during switch, heavy prior incretin exposure. Useful n=1 but do not generalize efficacy from this.", daysAgo: 33, reactions: { AGREE: 8, USEFUL: 4 } },
      { author: "dexa_devotee", body: "DEXA at 0/8/16? If not now, please start. This is the exact data the community needs and you're in a good position to capture it.", daysAgo: 31, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "retatrutide_r", body: "@dexa_devotee booked one for week 12. Didn't get a week 0 unfortunately but have a DEXA from 11 months ago as a rough reference.", daysAgo: 30, reactions: { USEFUL: 5 } },
    ],
  },
  {
    title: "Phase 3 timeline speculation — when does reta actually hit market",
    body: "Lilly's SURPASS-style trials for reta (TRIUMPH program) have readouts rolling through 2025-2026. Primary obesity endpoint trial (TRIUMPH-4) was supposed to wrap this spring.\n\nBased on the tirze timeline (phase 3 primary completion → FDA approval was ~18 months), naive math says reta approval window is late 2026 to mid 2027 for obesity indication. Diabetes indication likely trails by 6-12 months.\n\nCurious what the lab/regulatory people here think. Lilly has capacity pressure from Zepbound still being supply-constrained — does that slow the reta launch even after approval?",
    author: "the_stats_guy",
    daysAgo: 55,
    pinned: false,
    locked: false,
    views: 5880,
    reactions: { LIKE: 13, USEFUL: 11, AGREE: 7 },
    replies: [
      { author: "glp1_doctor_pt", body: "Lilly's been building capacity aggressively in NC and IN. My read is they're planning for reta to launch *without* tirze being out of the supply hole — they're solving both in parallel. Whether it works is another question.", daysAgo: 54, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "citation_required", body: "TRIUMPH-4 primary completion is listed as April 2025 on CT.gov last I checked. Data analysis plus NDA submission is usually 6-9 months post-completion. So NDA late 2025/early 2026, approval decision mid-to-late 2026 is plausible. Not late 2026 through mid 2027.", daysAgo: 54, reactions: { USEFUL: 10, AGREE: 6 } },
      { author: "the_stats_guy", body: "@citation_required good catch, I was conservative. If NDA late 25 and priority review, mid-26 approval is realistic. I was baking in too much slack.", daysAgo: 54, reactions: { AGREE: 4 } },
      { author: "retatrutide_r", body: "Meanwhile the research chem channel has had reta available for 18 months already. Real question isn't 'when does it approve' but 'when does payer coverage happen.' Approval means nothing if it's $1500/mo cash.", daysAgo: 53, reactions: { AGREE: 9, LIKE: 4 } },
      { author: "tirzepatide_tim", body: "Zepbound pricing history says it'll be $1000-1200/mo list, maybe $550 with Lilly's direct program, and payer coverage takes 12-24 months after approval to meaningfully broaden. Plan accordingly.", daysAgo: 53, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "showmethestudy", body: "Worth noting — reta for obesity only (TRIUMPH-4) may hit first, diabetes indication second. The compounding pharmacy loophole that's alive for tirze right now will not be available for reta on launch because FDA closed that door in 2024.", daysAgo: 52, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "microdose_glp1", body: "So practically speaking, if someone's on research chem reta right now, the economics of switching to pharma reta after approval are bad unless you have good insurance coverage. Planning for multi-year research chem continuity is the realistic move.", daysAgo: 51, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "cagrisema", body: "Don't forget Novo has cagrisema readouts in the same window. If cagrisema data is competitive, reta's pricing power is weaker on launch. Payers play them against each other.", daysAgo: 50, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "hexaclinic", body: "Lilly cares less about consumer pricing than you'd think — obesity indication for reta is a 10-year franchise play. They'll price for long-term payer contracts not short-term cash pay. Retail cash pay will be brutal for the first 2 years.", daysAgo: 48, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "plateau_breaker", body: "Question for the regulatory people — is there precedent for FDA requiring additional cardiovascular outcome trials (like what sema needed) before reta gets a broader label? GCG component is novel and I'd expect CV caution.", daysAgo: 46, reactions: { LIKE: 3 } },
      { author: "citation_required", body: "@plateau_breaker FDA signaled they want CV outcomes data for the GCG arm specifically. That's TRIUMPH-OUTCOMES which isn't reading until 2028 earliest. Initial approval will likely have language limiting high-risk CV populations.", daysAgo: 45, reactions: { USEFUL: 9, AGREE: 5 } },
      { author: "dr_doubt", body: "All speculation downstream of this: if you're waiting for pharma reta before using it, you're waiting 2-4 years for reasonable access. Make your decisions with that in mind rather than assuming 'next year it'll be normal.'", daysAgo: 43, reactions: { AGREE: 10, USEFUL: 4 } },
      { author: "the_stats_guy", body: "This thread is a better timeline picture than most industry reports I've read. Saving.", daysAgo: 41, reactions: { THANKS: 5 } },
      { author: "reads_more_posts", body: "Just wanted to say threads like this are why I'm here. Thanks all.", daysAgo: 38, reactions: { LIKE: 6, THANKS: 3 } },
      { author: "fat_loss_log", body: "If approval lands mid-26 I'll probably bridge with research chem until my insurance picks it up. Realistic 2028 before I'm paying pharma prices with coverage.", daysAgo: 35, reactions: { AGREE: 4 } },
    ],
  },

  // ---------- ACTIVE (3) ----------
  {
    title: "Titration debate — 2/4/8/12 vs slow crawl",
    body: "Seeing a split in the reta community on titration aggression. The 'Lilly schedule' from trial data is basically 2mg for 4 weeks, 4mg for 4, 8mg for 4, then 12mg. That's the safe lane.\n\nBut the research chem crowd is all over the map. Some doing 2/4/8/12 on 2-week intervals. Some doing 0.5mg microdose crawl. Some frontloading 4mg week one because 'tirze taught my body.'\n\nWhat's the data-driven approach? My bias is the Lilly schedule exists because it minimizes dropouts from GI. Aggressive titration doesn't give more weight loss, it just gives more vomiting. But interested in counterpoints.",
    author: "slow_titrate",
    daysAgo: 29,
    views: 2840,
    reactions: { LIKE: 8, USEFUL: 7, AGREE: 5 },
    replies: [
      { author: "retatrutide_r", body: "Did 2-week intervals because I was coming off tirze 10mg. For a naive person I'd never recommend it. The GI on my first 6mg week was still worse than anything I had on tirze.", daysAgo: 29, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "frontloader", body: "Frontloading GLP-1s is genuinely a bad idea in a way that frontloading a lot of other peptides isn't. Receptor saturation kinetics mean you get the same max effect at 4mg as 8mg on week 1 — you just get it with more side effects. No upside.", daysAgo: 28, reactions: { AGREE: 8, USEFUL: 6 } },
      { author: "microdose_glp1", body: "The 0.5mg microdose crawl has a specific use case — people prone to nausea or with heart rate sensitivity. It's not faster but it filters out the people who'd DNF on 2mg. For the average person, 2mg start is fine.", daysAgo: 28, reactions: { USEFUL: 5 } },
      { author: "slow_titrate", body: "@microdose_glp1 that's basically my read too. Lilly chose 2mg start because it balances efficacy signal against dropout rate at population scale. Individual variation means some people want 1mg start, but 'start at 2, crawl from there' is sane default.", daysAgo: 27, reactions: { AGREE: 4 } },
      { author: "plateau_breaker", body: "What nobody's saying — the real question isn't how fast to titrate, it's when to stop. 8mg is where most people's weight loss rate peaks. Pushing to 12 is a roll of the dice for maybe another 5% loss at real cost in side effects.", daysAgo: 27, reactions: { USEFUL: 7, AGREE: 6 } },
      { author: "tirzepatide_tim", body: "@plateau_breaker this matches my tirze experience inverted — the jump from 10 to 15 was marginal for me. 12mg reta might be the same. Dose-response is sublinear past a point.", daysAgo: 26, reactions: { AGREE: 5 } },
      { author: "showmethestudy", body: "TRIUMPH-2 data showed a clear dose-response curve but with flattening between 8 and 12mg. If you're responding well at 8, the marginal utility of going higher is small.", daysAgo: 25, reactions: { AGREE: 6, USEFUL: 5 } },
      { author: "first_vial", body: "Planning my first ever reta cycle. Sounds like 2mg x 4 weeks, evaluate, then 4 for 4 is the reasonable newbie path?", daysAgo: 23, reactions: { LIKE: 2 } },
      { author: "slow_titrate", body: "@first_vial yes. Add: don't push the next titration step unless GI is fully baseline. If you're still queasy at week 3 of 2mg, spend another 2 weeks there. Titration is earned, not scheduled.", daysAgo: 22, reactions: { USEFUL: 8, AGREE: 5 } },
    ],
  },
  {
    title: "Side effects at 10mg — HR, nausea, and what's normal vs what's a flag",
    body: "Week 11, been on 10mg for 2 weeks. Logging what I'm feeling so others can calibrate.\n\n- Resting HR: baseline 58, currently 67. Up 9bpm from baseline, up 4 from the 8mg plateau.\n- Nausea: 2/10 background, 5/10 for ~6 hours after injection (inject Sunday AM).\n- Sulfur burps: manageable, mostly gone by day 3 post-injection.\n- Sleep: mildly worse. Oura deep down 10% vs baseline month.\n- BP: 124/80, up from 116/72 baseline.\n- Mood: flat. Not depressed, just... muted.\n\nWhat's in the 'known issue' column vs what should I actually pay attention to? The HR and BP creep are what I'm least sure about.",
    author: "fat_loss_log",
    daysAgo: 18,
    views: 2200,
    reactions: { LIKE: 6, USEFUL: 7 },
    replies: [
      { author: "glp1_doctor_pt", body: "HR up 9 and BP up 8/8 is the GCG arm doing what it does. Not alarming in isolation, but if the trend continues past week 14 or you hit 130/85 sustained, back off to 8mg. The CV stuff creeps and then isn't reversible in the same timeframe.", daysAgo: 18, reactions: { USEFUL: 10, AGREE: 6 } },
      { author: "hexaclinic", body: "Mood flattening on incretin class is underdiscussed. Hedonic response tanks for some people, probably dopaminergic downregulation secondary to reduced food reward. Usually partially rebounds 2-3 weeks after stopping or dropping dose.", daysAgo: 17, reactions: { AGREE: 7, USEFUL: 6 } },
      { author: "retatrutide_r", body: "Match all of this except I'm not getting the flat mood. Curious if it's baseline-dependent — I was running kind of hypomanic pre-reta so a damped mood feels like normal to me.", daysAgo: 17, reactions: { LIKE: 3 } },
      { author: "plateau_breaker", body: "Log your HR trend weekly going forward. The inflection point is what matters, not the absolute. If HR is still climbing at week 14, that's different from plateauing at 67.", daysAgo: 16, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "dr_doubt", body: "The 'muted' mood report is the subtle side effect that makes people quit reta after they've already lost a lot of weight. Name it so you can track it. If at week 20 you're 40lb down and still feel emotionally dim, weight loss is not making you happier.", daysAgo: 15, reactions: { AGREE: 9, USEFUL: 6, LIKE: 3 } },
      { author: "fat_loss_log", body: "@dr_doubt this is a real reframe. I've been treating the weight loss as the only metric. Adding a weekly subjective wellness score to my log starting today.", daysAgo: 15, reactions: { THANKS: 6, AGREE: 3 } },
      { author: "slow_titrate", body: "Sleep decline matches what I'd expect — GCG arm runs you warmer and that compromises deep sleep. Not a flag, but if it persists past adaptation (4-6 weeks at dose), consider dropping back.", daysAgo: 14, reactions: { USEFUL: 5 } },
      { author: "cautious_ox", body: "This thread is the kind of honest side effect log I needed before starting. Most 'my reta journey' posts pretend everything is fine.", daysAgo: 12, reactions: { LIKE: 5, THANKS: 2 } },
    ],
  },
  {
    title: "Why three receptors matters — GCG arm for lipolysis, not just weight",
    body: "People talk about reta as 'tirze plus.' It's not. The glucagon receptor agonism does something tirze literally cannot do — direct lipolysis and increased resting energy expenditure.\n\nMechanism in brief: GCG receptor activation on adipocytes upregulates HSL and ATGL → releases FFAs → hepatic oxidation. Plus increased thyroid conversion (T4→T3) peripherally. That's why reta runs you warmer and why fat loss composition may differ from pure GLP-1 class.\n\nPractical implications:\n1. Muscle sparing may be *better* than tirze on high-protein intake because the energy deficit is partially pulled from fat oxidation rather than purely from appetite suppression.\n2. Thermogenic response means expect slightly higher kcal baseline — you can eat more and still lose.\n3. HR/BP bump isn't a bug, it's sympathetic activation from GCG. Watch it.\n\nCurious what others' DEXA data says on LBM retention. This is the claim that needs testing.",
    author: "hexaclinic",
    daysAgo: 24,
    views: 2960,
    reactions: { LIKE: 11, USEFUL: 9, AGREE: 7 },
    replies: [
      { author: "dexa_devotee", body: "I have DEXA at 0/8/16 on both tirze (last year) and reta (ongoing, through week 12 so far). Tirze: lost 22lb, ~3.5lb LBM. Reta: lost 18lb through week 12, 1.8lb LBM. Too early to call but the trend matches what you'd predict from GCG-driven fat oxidation.", daysAgo: 23, reactions: { USEFUL: 11, AGREE: 6, LIKE: 3 } },
      { author: "macrosguru", body: "Protein intake across both cycles? LBM retention is downstream of protein + training volume more than compound choice. If your protein was lower on tirze it skews the comparison.", daysAgo: 23, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "dexa_devotee", body: "@macrosguru same macros (2g/kg protein), same training (4x/week upper/lower), same sleep tracking. Not RCT-clean but as controlled as a self-experiment gets.", daysAgo: 22, reactions: { USEFUL: 6, LIKE: 3 } },
      { author: "showmethestudy", body: "The GCG → lipolysis mechanism is solid in rodent and ex vivo data. Human in vivo contribution at therapeutic reta doses is less characterized — some of the thermogenic effect people feel may be central (hypothalamic) rather than peripheral lipolysis. Mechanism is plausible but 'how much' is the open question.", daysAgo: 22, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "igf_curve", body: "Don't forget GCG also bumps hepatic glucose output, which is why reta's HbA1c data looks different from tirze despite the incretin arms being similar. The metabolic profile is genuinely distinct.", daysAgo: 21, reactions: { USEFUL: 8, AGREE: 4 } },
      { author: "retatrutide_r", body: "The thermogenic subjective thing is real — I said it in another thread, I literally sweat more on reta. Sympathetic activation is the most parsimonious explanation.", daysAgo: 21, reactions: { AGREE: 5, LIKE: 3 } },
      { author: "the_stats_guy", body: "The 'muscle sparing may be better' claim needs a lot more n. @dexa_devotee's data is encouraging but one subject. Anyone else with paired DEXA across classes?", daysAgo: 20, reactions: { LIKE: 3 } },
      { author: "recomp_rex", body: "I'll have paired data in ~8 weeks. Finishing tirze DEXA now, starting reta February. Same training, same macros. Will post.", daysAgo: 19, reactions: { LIKE: 5, THANKS: 3 } },
      { author: "citation_required", body: "The T4→T3 conversion bump claim is softer than the lipolysis one. Some signals but human data is thin. Don't want readers walking away thinking reta is a thyroid modulator — that's overreach.", daysAgo: 18, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "hexaclinic", body: "@citation_required fair, I softened it too little. The thyroid angle is hypothesis not established. Peripheral oxidation bump is the durable claim.", daysAgo: 18, reactions: { AGREE: 5 } },
    ],
  },

  // ---------- QUIET (5) ----------
  {
    title: "Sourcing reta — what does the market look like right now",
    body: "Not asking for vendors. Asking about market conditions — has reta supply stabilized in the research chem channel? Six months ago every batch was a guessing game. Has HPLC availability caught up?",
    author: "cautious_ox",
    daysAgo: 12,
    views: 780,
    reactions: { LIKE: 2 },
    replies: [
      { author: "cardinal_rule", body: "Not a sourcing thread. But meta-discussion of market conditions is fine. No vendor names, no DMs, no 'you know where.' That line gets enforced.", daysAgo: 12, reactions: { AGREE: 4, USEFUL: 2 } },
      { author: "retatrutide_r", body: "General read: supply is much better than 6 months ago, HPLC/mass-spec reports are more standard, price has come down ~35% since last summer. That's the market, do with it what you will.", daysAgo: 11, reactions: { USEFUL: 5 } },
      { author: "microdose_glp1", body: "Quality has bifurcated — the top-tier vendors are genuinely clean on third-party testing, the cheap stuff is still a crapshoot. Price is not a perfect signal but it correlates.", daysAgo: 10, reactions: { USEFUL: 3 } },
      { author: "bac_water_noob", body: "Is there a resource for reading third-party HPLC reports? I've seen them posted and I don't know what I'm looking at.", daysAgo: 8, reactions: { LIKE: 1 } },
      { author: "panel_maxer", body: "@bac_water_noob basic read: look for purity % (>97% ideal), absence of peaks at known impurity retention times, and that the mass-spec confirms the molecular weight. Separate thread in lab corner goes deep.", daysAgo: 7, reactions: { USEFUL: 4, THANKS: 2 } },
    ],
  },
  {
    title: "Switching from tirze — 3 week washout or bridge?",
    body: "Running tirze 7.5mg currently. Want to swap to reta in the next month. Question: do I just stop tirze, wait, and start reta? Or is there a bridging protocol?\n\nHalf-life of tirze is ~5 days so at ~3 weeks it's effectively gone. But reta half-life is 6 days and you start at 2mg — is there a risk of the tirze tail overlapping with the reta ramp and causing additive effects?",
    author: "plateau_breaker",
    daysAgo: 16,
    views: 620,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "retatrutide_r", body: "I did a 3-week washout before switching. Minor weight regain (~4lb) but the transition was clean. Tirze tail + reta 2mg ramp would have been GI-miserable in my experience.", daysAgo: 16, reactions: { USEFUL: 5 } },
      { author: "slow_titrate", body: "3 week washout is the right call. You're trading a bit of regain for a clean titration. Worth it.", daysAgo: 15, reactions: { AGREE: 3 } },
      { author: "glp1_doctor_pt", body: "The bridging concept (reducing tirze while ramping reta) has no evidence base. Stick with washout. Simple, predictable kinetics.", daysAgo: 14, reactions: { USEFUL: 4, AGREE: 2 } },
    ],
  },
  {
    title: "Reta for metabolic syndrome — off-label use case",
    body: "46M, T2D marginal (HbA1c 6.2), visceral fat problem (waist 41\"), lipids disaster (triglycerides 240, ApoB 128). Not obese by BMI (27). Endocrinologist is hesitant on GLP-1 because I'm not technically diabetic and 'just' overweight.\n\nReta's metabolic profile — the GCG arm especially — looks ideal for this picture. Visceral fat, triglycerides, hepatic steatosis.\n\nAnyone running reta for metabolic syndrome specifically (not primarily for weight)? What dose range, what markers moved first?",
    author: "apob_reader",
    daysAgo: 20,
    views: 840,
    reactions: { LIKE: 4, USEFUL: 3 },
    replies: [
      { author: "hba1c_watch", body: "Not on reta but on tirze for similar reasons (A1c 5.9, viceral AT, trigs 210). 4 months in: trigs 98, ApoB 78, A1c 5.4, waist -3.5\". I'd expect reta to hit harder on trigs specifically because GCG-driven hepatic fat clearance.", daysAgo: 19, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "hexaclinic", body: "Metabolic syndrome is arguably reta's *best* indication given the three-receptor profile. Hepatic fat in particular responds fast. I'd expect trigs and liver enzymes to move inside 6 weeks at 4mg.", daysAgo: 18, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "apob_reader", body: "Plan: 2mg x 4, 4mg x 6 weeks, draw full panel week 10. If trigs below 150 and ApoB below 100 I'd consider that success at 4mg and hold.", daysAgo: 18, reactions: { USEFUL: 3 } },
      { author: "dr_doubt", body: "For metabolic syndrome specifically, 4-6mg is likely plenty. The 8-12mg range is for weight loss extremism. Don't overshoot.", daysAgo: 17, reactions: { AGREE: 5, USEFUL: 4 } },
    ],
  },
  {
    title: "Training on 10mg — is it realistic",
    body: "Started reta 9 weeks ago. Training intensity is noticeably down at 8mg, worried 10mg will end my lifting window.\n\nLifting 4x/week, mid-to-high volume, avg 75 min sessions. At 8mg I'm hitting sessions but feeling gassed around minute 50 that I wouldn't have felt at baseline. Heart rate is higher at comparable loads. Recovery between sets is longer.\n\nAnyone hold lifting intensity at 10+mg or does it just become impossible?",
    author: "recomp_rex",
    daysAgo: 14,
    views: 580,
    reactions: { LIKE: 2 },
    replies: [
      { author: "retatrutide_r", body: "Hitting sessions at 10mg but I dropped one session per week and cut volume 20%. The cardiovascular cost is real. Intensity (load) is holdable, total work output is not.", daysAgo: 14, reactions: { USEFUL: 4 } },
      { author: "nopain_noreign", body: "Pragmatic answer — periodize. Lifting season runs on 6mg max. Loss-maximization phase runs on 10mg for 8 weeks, training becomes maintenance-only. Don't try to do both at max effort.", daysAgo: 13, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "macrosguru", body: "Intra-workout carbs help more than you'd think on reta. 40g cyclic dextrin starts to bring the gas tank back at minute 40.", daysAgo: 12, reactions: { USEFUL: 3 } },
      { author: "recomp_rex", body: "@macrosguru trying this Friday. Hadn't considered intra-workout because appetite is so blunted but that's separable from substrate availability.", daysAgo: 11, reactions: { THANKS: 2 } },
    ],
  },
  {
    title: "First reta cycle checklist — am I missing anything",
    body: "Starting in 2 weeks. Here's my plan:\n- Baseline bloods drawn this week (CBC, CMP, lipids, A1c, fasting insulin, lipase/amylase, thyroid, cortisol AM).\n- Starting dose 2mg Sunday AM, titrate every 4 weeks if stable.\n- Protein 180g minimum, resistance training 3x/week.\n- Weight + waist weekly, bloods at week 12.\n- Subjective log: mood, sleep, HR trend from Oura.\n- DEXA at week 0 and week 16.\n\nWhat am I not thinking of?",
    author: "first_vial",
    daysAgo: 9,
    views: 430,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "slow_titrate", body: "Add BP cuff. Home measurements, 3x/week. HR from Oura is fine but BP needs a cuff.", daysAgo: 9, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "panel_maxer", body: "Your bloodwork panel is good. Add hs-CRP and homocysteine if you can — reta affects inflammation markers and it's a useful trend.", daysAgo: 8, reactions: { USEFUL: 3 } },
      { author: "cardinal_rule", body: "Plan looks clean. One add: stopping criteria. What would make you stop? HR >80 sustained? BP >135/90? Mood flat for >3 weeks? Write them down before you start so you're not negotiating with yourself under the influence of a weight-loss compound that affects mood.", daysAgo: 7, reactions: { AGREE: 6, USEFUL: 5 } },
      { author: "first_vial", body: "@cardinal_rule this is the advice I needed. Adding stopping criteria today.", daysAgo: 7, reactions: { THANKS: 3 } },
    ],
  },
];

// ============================================================
// GH SECRETAGOGUES — 16 threads
// ============================================================
export const THREADS_GHS: SeedThread[] = [
  // ---------- POPULAR (3) ----------
  {
    title: "CJC-1295 no-DAC + Ipamorelin — the workhorse stack, 3 years of notes",
    body: "Running CJC no-DAC + Ipa in various cycles since 2022. This is the GHS stack for a reason — it's the only one that reliably moves IGF-1, doesn't spike prolactin or cortisol, and you can run it for years without major tachyphylaxis if you cycle properly.\n\nMy current base protocol:\n- CJC-1295 no-DAC: 100 mcg\n- Ipamorelin: 200 mcg\n- Frequency: 3x/day (pre-breakfast empty stomach, post-workout or midafternoon, pre-bed empty stomach)\n- Sub-Q abdomen, 29g 1/2\" insulin pin\n- Route: same syringe, both drawn and injected together\n- 8 weeks on / 4 weeks off, minimum\n\nWhy no-DAC over DAC: I want pulsatile GH release matching natural architecture, not a tonic elevation. DAC is fine for convenience but blunts the pulse and disrupts feedback more. Pre-bed pulse is the one I care about most — that's when natural GH surge happens and stacking there is the sacred slot.\n\nIGF-1 history:\n- Baseline (2021): 168 ng/mL\n- End of first 8-week cycle: 241\n- Off-cycle rebound (4 wk): 172\n- Current (cycle 6, week 6): 258\n\nMarkers watched: prolactin (stable), fasting glucose (up ~6 mg/dL on-cycle, normal off), cortisol AM (no change).\n\nReady for questions. Not answering source questions.",
    author: "stackbuilder",
    daysAgo: 48,
    pinned: false,
    locked: false,
    views: 8620,
    reactions: { LIKE: 22, USEFUL: 18, THANKS: 12, AGREE: 9 },
    replies: [
      { author: "protocolpilot", body: "Bookmarking. The 8/4 cycle cadence is the part people underdo — you cannot run GHS continuously and expect to keep the IGF response. Your rebound data shows exactly why.", daysAgo: 48, reactions: { AGREE: 10, USEFUL: 6 } },
      { author: "igf_curve", body: "Clean data. Your end-of-cycle IGF at 258 is in the sweet spot — high enough to feel effects, not so high you're pushing the cancer-risk conversation. Above 300 I start getting skeptical about long-term safety.", daysAgo: 48, reactions: { AGREE: 8, USEFUL: 7 } },
      { author: "hexaclinic", body: "The 'same syringe' question comes up constantly. Confirming — CJC and Ipa are compatible, no stability issues at room temp for the minutes you'd need to combine and pin. BAC water reconstitution, not saline, for best stability of CJC.", daysAgo: 47, reactions: { USEFUL: 11, AGREE: 5 } },
      { author: "restwise", body: "Pre-bed pulse is everything. I've tested pre-bed only (single dose), 3x daily, and AM-only. Pre-bed single gives ~60% of the subjective effect of full 3x daily for me. If you're going minimalist, that's the dose to keep.", daysAgo: 47, reactions: { USEFUL: 8, LIKE: 4 } },
      { author: "stackbuilder", body: "@restwise agreed. If someone told me 'you can only afford 1 dose/day,' I'd keep pre-bed and ditch the others. The other doses are additive but pre-bed is where the architecture matters.", daysAgo: 47, reactions: { AGREE: 7 } },
      { author: "showmethestudy", body: "Fair question — the 'feels better' subjective stuff is real but what's the evidence that bumping IGF-1 from 168 to 258 translates to anything hard-endpoint (body comp, performance, recovery)? Most of the data on supraphysiologic IGF is from rhGH, not GHS. Want to make sure people aren't extrapolating.", daysAgo: 46, reactions: { AGREE: 7, USEFUL: 5 } },
      { author: "stackbuilder", body: "@showmethestudy honest answer — body comp changes are subtle. Over 3 years with consistent training and diet I'd estimate 2-3 lb leaner at same weight than I'd have been without GHS. That's a guess with a big CI. Subjective sleep and recovery are the durable wins. I wouldn't sell this as a body comp protocol.", daysAgo: 46, reactions: { USEFUL: 9, AGREE: 6, LIKE: 4 } },
      { author: "cyclecraft", body: "Site rotation with 3x daily? You need 18+ usable abdomen spots to avoid lumps over 8 weeks. I went to adding upper thigh and deltoid Sub-Q for the midday dose, keeps abdomen less abused.", daysAgo: 46, reactions: { USEFUL: 6 } },
      { author: "dexa_devotee", body: "Paired DEXA: my GHS cycles show 0.5-1 lb LBM gain over 8 weeks that doesn't show up in off-cycles with same training. Not huge. Reproducible over 4 cycles though.", daysAgo: 45, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "labrat_ish", body: "Question — pre-breakfast timing. How long before eating? I've seen 30 min, 45 min, 'one hour minimum.'", daysAgo: 45, reactions: { LIKE: 2 } },
      { author: "stackbuilder", body: "@labrat_ish 30 min is fine for the IGF pulse. The fasting requirement is because elevated glucose blunts the GH response — you want insulin low. Black coffee OK, caloric anything is not.", daysAgo: 45, reactions: { USEFUL: 8, THANKS: 3 } },
      { author: "taper_time", body: "Exit from 8-week cycle — any taper or just stop? I find cold stops from GHS give me a sleep dip for about a week.", daysAgo: 44, reactions: { LIKE: 2 } },
      { author: "stackbuilder", body: "@taper_time cold stop for me. Sleep dips for 4-6 days then normalizes. Tapering would just extend the dip IMO — you're going to go through feedback recalibration either way.", daysAgo: 44, reactions: { USEFUL: 5 } },
      { author: "new2peptides", body: "Coming in fresh. When you say 'same syringe' — you draw CJC first then Ipa into the same insulin pin?", daysAgo: 43, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@new2peptides yes. Draw from each vial in order, one insulin pin, total volume under 50 units. If you're uncomfortable combining, you can do two separate pins same site within a minute — same bioavailability.", daysAgo: 43, reactions: { USEFUL: 7, THANKS: 3 } },
      { author: "joint_hunter", body: "Any wrist swelling / carpal tunnel symptoms on your cycles? I hear this reported and want to know the dose at which it appears.", daysAgo: 42, reactions: { LIKE: 2 } },
      { author: "stackbuilder", body: "@joint_hunter no. Ipa at 200 mcg is low enough that I haven't seen water retention or CT symptoms. At 300 I get mild morning hand puffiness for the first week, resolves. Hexarelin or MK-677 are the usual culprits for pronounced water retention, not Ipa.", daysAgo: 42, reactions: { USEFUL: 6 } },
      { author: "dr_doubt", body: "Appreciate the honesty on the body comp claim. '2-3 lb leaner over 3 years, big CI' is the kind of calibrated report that makes the community better. Most people overclaim GHS wildly.", daysAgo: 40, reactions: { AGREE: 10, LIKE: 5, USEFUL: 4 } },
      { author: "nopain_noreign", body: "This stack is genuinely a different thing than HGH and the community conflates them constantly. GHS at good cycle cadence is safe and subtly beneficial. Supraphysiologic HGH is a different risk conversation entirely.", daysAgo: 38, reactions: { AGREE: 11, USEFUL: 5 } },
      { author: "first_vial", body: "Saving this entire thread. My GHS reference doc.", daysAgo: 35, reactions: { LIKE: 5, THANKS: 3 } },
    ],
  },
  {
    title: "Sleep on GHRH+GHRP is disproportionate to any other effect — why",
    body: "I've tried every GHS combo. Sermorelin alone, Ipa alone, Hexarelin, CJC+Ipa, MK-677. The single most reproducible effect across all of them is sleep depth. Everything else (body comp, recovery, mood) is subtle to arguably placebo. Sleep is not subtle — Oura deep sleep minutes go from 55-70 baseline to 90-120 within 3 days of starting.\n\nWhat's the mechanism? Is it the GH pulse itself or the slow-wave modulation upstream of the GH pulse? Because if I'm understanding the biology right, slow-wave sleep drives the GH pulse in adults, not the other way around — so why would an exogenous pulse improve the slow-wave architecture?\n\nLooking for someone who actually understands the feedback loop. My intuition is we're catching a secondary effect (ghrelin receptor in the hypothalamus doing something to sleep regulation independent of GH) but I'd like to know the real answer.",
    author: "restwise",
    daysAgo: 33,
    views: 5120,
    reactions: { LIKE: 15, USEFUL: 10, AGREE: 7 },
    replies: [
      { author: "hexaclinic", body: "You're right that slow-wave drives the natural GH pulse. The exogenous effect isn't improving SWS via GH — it's GHRP-class compounds acting on the ghrelin receptor (GHSR) which has independent effects on sleep architecture, likely via hypothalamic-pituitary pathways separate from GH itself.\n\nThis is why Ipa, Hexarelin, GHRP-2/6 all improve sleep subjectively even when the GH pulse is small. And it's why MK-677 (also GHSR agonist, long half-life) hits sleep depth hard. GHRH analogs alone (sermorelin, tesa) have weaker sleep effects because they're not hitting GHSR.", daysAgo: 33, reactions: { USEFUL: 18, AGREE: 11, THANKS: 8 } },
      { author: "restwise", body: "@hexaclinic this is the clearest mechanism answer I've gotten anywhere. So the sleep improvement is primarily ghrelin-receptor-mediated and the GH pulse is almost a side effect of the sleep improvement in some sense.", daysAgo: 33, reactions: { THANKS: 6, USEFUL: 4 } },
      { author: "igf_curve", body: "Co-signing @hexaclinic. The literature on ghrelin and sleep is much bigger than people think — ghrelin itself modulates slow-wave sleep in healthy adults. GHSR agonism is the connecting pathway, not GH release.", daysAgo: 32, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "dreamline", body: "This explains my observation that sermorelin alone barely touches my sleep but the second I add Ipa, deep jumps overnight.", daysAgo: 32, reactions: { AGREE: 5, LIKE: 4 } },
      { author: "humanin_hope", body: "Fits my MK-677 data too. MK is basically GHSR agonism in pill form with long half-life. Sleep depth response is huge, IGF response is secondary.", daysAgo: 31, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "showmethestudy", body: "Subjective Oura deep sleep improvements should be treated with some skepticism — Oura's deep sleep classification is noisy and EEG validation studies show Oura overestimates deep/under-classifies light. That said, the cross-user consistency of this subjective report is strong, so the effect is almost certainly real even if the magnitude isn't 2x.", daysAgo: 30, reactions: { USEFUL: 7, AGREE: 6 } },
      { author: "restwise", body: "@showmethestudy fair and worth flagging. I use Oura because I have 2 years of data on it, not because it's ground truth. Even a 30% Oura improvement is likely a real effect.", daysAgo: 30, reactions: { AGREE: 4 } },
      { author: "protocolpilot", body: "The mechanism post from @hexaclinic is one of the best single replies on this forum. Saving.", daysAgo: 29, reactions: { LIKE: 8, THANKS: 4 } },
      { author: "nad_nightowl", body: "Interesting adjacent data — I run NAD+ + GHS pre-bed and the sleep effect is additive. Different receptor targets but both affect slow-wave architecture.", daysAgo: 27, reactions: { LIKE: 3 } },
      { author: "panel_maxer", body: "If the dominant mechanism is GHSR and not GH, it also explains why pure GHRH protocols (sermorelin-only) don't move IGF-1 as much as they should based on receptor theory — without GHSR augmentation, the pituitary response to GHRH is weaker in anyone over 30 due to somatostatin tone. GHRP 'gates the pulse open.'", daysAgo: 26, reactions: { USEFUL: 10, AGREE: 5 } },
      { author: "silentscroll", body: "Reading this thread was worth my entire forum subscription.", daysAgo: 24, reactions: { LIKE: 7, THANKS: 2 } },
      { author: "dr_doubt", body: "The durable point here: 'sleep depth is the single reliable effect, everything else is subtle.' That's the honest case for GHS. Anyone selling GHS as body composition or youth restoration is overreaching past what the evidence supports. Sleep is the win.", daysAgo: 22, reactions: { AGREE: 13, USEFUL: 7, LIKE: 5 } },
      { author: "citation_required", body: "Any peer-reviewed human studies on GHSR agonism and SWS architecture specifically? I'd like to cite this mechanism but I want the receipts.", daysAgo: 20, reactions: { LIKE: 2 } },
      { author: "hexaclinic", body: "@citation_required Copinschi et al on GHSR analogs and sleep, Weikel on ghrelin/GH/sleep in healthy men, Steiger reviews on sleep endocrinology. Not a thick literature but the ghrelin-sleep link is established.", daysAgo: 19, reactions: { THANKS: 6, USEFUL: 5 } },
    ],
  },
  {
    title: "GHS vs GLP-1 for fat loss — settle this",
    body: "Seeing a lot of 'GHS for recomp' posts and I want to push back because I've done both back to back and the comparison isn't close.\n\n16 weeks GHS (CJC+Ipa 200/100 3x daily, 8wk on/4wk off, then 8 more on): lost 4.2 lb, waist -0.5\".\n16 weeks tirze (2.5 → 7.5mg): lost 22 lb, waist -3\".\n\nSame training, same nutrition intent (didn't hit protein as clean on GHS because appetite was high).\n\nFor fat loss as a primary outcome, GLP-1 class is simply a different order of magnitude. GHS as a fat loss tool is marginal at best.\n\nThe GHS case is sleep, subjective recovery, and probably some lean mass preservation during a GLP-1 cut. Running them together is where the actual recomp case lives — not GHS alone.",
    author: "fat_loss_log",
    daysAgo: 40,
    views: 4880,
    reactions: { LIKE: 12, AGREE: 10, USEFUL: 6 },
    replies: [
      { author: "recomp_rex", body: "This is the take more people need. GHS is framed as a body comp tool by marketing and it's really not — it's a recovery/sleep tool that has small body comp effects as a side benefit.", daysAgo: 40, reactions: { AGREE: 11, USEFUL: 4 } },
      { author: "stackbuilder", body: "Agreed. If someone asks me 'should I run GHS or tirze for weight loss' the answer is always tirze. GHS comes in for the parallel concerns — sleep, LBM preservation during the tirze cut.", daysAgo: 39, reactions: { AGREE: 9, USEFUL: 5 } },
      { author: "macrosguru", body: "The protein-during-cut question is actually where GHS earns its keep. On tirze alone with appetite down you risk losing LBM. Stack GHS and you're more likely to preserve. That's the combined recomp play.", daysAgo: 39, reactions: { USEFUL: 8, AGREE: 6 } },
      { author: "hexaclinic", body: "Mechanism-wise this is exactly right. GLP-1 creates energy deficit via appetite suppression. GHS modulates what the body does in that deficit — preferentially burning fat and preserving muscle via IGF-mediated synthesis.", daysAgo: 38, reactions: { USEFUL: 9, AGREE: 7 } },
      { author: "dexa_devotee", body: "Paired DEXA: tirze alone (last year): -22lb, -3.8 LBM. Tirze + CJC/Ipa (this year): -19lb, -1.4 LBM. The LBM delta is significant. GHS is doing work specifically on composition.", daysAgo: 38, reactions: { USEFUL: 12, AGREE: 7, LIKE: 4 } },
      { author: "plateau_breaker", body: "@dexa_devotee this is the data I was looking for. 2.4 lb LBM swing on a 20lb cut is the difference between 'cut' and 'recomp.'", daysAgo: 37, reactions: { AGREE: 5 } },
      { author: "showmethestudy", body: "Before everyone races to stack — GHS adds injection burden and cost. For someone who isn't lifting hard and isn't getting adequate protein, GHS isn't going to magically preserve LBM. Training and protein intake are the primary LBM drivers. GHS is a secondary lever.", daysAgo: 36, reactions: { AGREE: 9, USEFUL: 6 } },
      { author: "cyclecraft", body: "Correct framing: GHS is an amplifier, not a driver. If the substrate (protein) and the stimulus (training) aren't there, GHS doesn't rescue you.", daysAgo: 35, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "slow_lose", body: "I'm a GHS enjoyer and I'll admit — I got on GLP-1 for weight loss, not GHS, because after 6 months of GHS I was 3 lb lighter and not happy about it. GHS framing shouldn't include 'will make you lean.'", daysAgo: 33, reactions: { AGREE: 6, LIKE: 3 } },
      { author: "fat_loss_log", body: "Point of this post wasn't to diss GHS. It was to set accurate expectations. Running CJC+Ipa right now with tirze and it's the best protocol I've done. Just don't start GHS expecting fat loss.", daysAgo: 30, reactions: { AGREE: 8, THANKS: 3 } },
      { author: "dr_doubt", body: "The stack beats either alone. Running them together is probably the single most evidence-justified peptide protocol going right now in terms of expected outcome vs. risk profile.", daysAgo: 28, reactions: { AGREE: 10, USEFUL: 6, LIKE: 3 } },
      { author: "protocolwonk", body: "Saving this for every newbie who asks 'GHS for cutting?'", daysAgo: 25, reactions: { LIKE: 4, THANKS: 2 } },
    ],
  },

  // ---------- ACTIVE (6) ----------
  {
    title: "Sermorelin vs Ipamorelin — which actually feels like something",
    body: "Ran sermorelin 300 mcg pre-bed for 8 weeks. Barely noticed anything. IGF-1 went from 154 to 178. Subjective effects: maybe slightly better sleep, maybe slightly warmer hands. Vague.\n\nSwapped to Ipa 200 mcg pre-bed for 8 weeks. Night one I slept like a dead person. IGF-1 went from 178 to 239. Subjective: clearly better sleep, clearly better recovery, clearly something happening.\n\nAre these two even in the same conversation? Feels like comparing aspirin to morphine.",
    author: "new2peptides",
    daysAgo: 26,
    views: 1840,
    reactions: { LIKE: 7, USEFUL: 4 },
    replies: [
      { author: "hexaclinic", body: "They're not the same compound class. Sermorelin is a GHRH analog — binds the GHRH receptor, releases GH only as much as the pituitary is ready to release. Weaker pulse, fewer side effects, very dependent on somatostatin tone.\n\nIpamorelin is a GHRP — ghrelin receptor agonist. Independent pathway. Actively 'gates open' the GH pulse past somatostatin, which is why the subjective effect is much stronger.\n\nStacking them is synergistic because you hit both receptors. Sermorelin alone is the weakest GHS compound for this reason.", daysAgo: 26, reactions: { USEFUL: 13, AGREE: 9, THANKS: 5 } },
      { author: "protocolpilot", body: "Sermorelin standalone is really an 'entry drug' that shouldn't have been sold as a real GH protocol. The comparison to Ipa standalone is not close.", daysAgo: 25, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "igf_curve", body: "Your IGF delta confirms the mechanism. Sermorelin moved IGF 24 points in 8 weeks, Ipa moved it 61 points. Ipa is doing 2.5x the work at comparable dosing.", daysAgo: 25, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "stackbuilder", body: "If you run them together — sermorelin + Ipa 300/200 3x daily — the IGF bump is bigger than either alone, often 80-100 points from baseline. The synergy is real, that's why CJC+Ipa (same mechanism pair) is the workhorse.", daysAgo: 24, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "showmethestudy", body: "Fair but worth noting — sermorelin has a shorter half-life (~12 min) than CJC no-DAC (~30 min). Some of the weakness is kinetics, not just receptor selection. At matched pulse-profile sermorelin underperforms CJC but not by as much.", daysAgo: 23, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "new2peptides", body: "So next cycle I should be running CJC no-DAC + Ipa together rather than either alone. That's the consensus?", daysAgo: 22, reactions: { LIKE: 2 } },
      { author: "stackbuilder", body: "@new2peptides yes. CJC no-DAC 100 mcg + Ipa 200 mcg, 2-3x daily, pre-bed always. That's the standard newbie-appropriate GHS stack.", daysAgo: 22, reactions: { USEFUL: 5, AGREE: 3 } },
    ],
  },
  {
    title: "Tesamorelin for visceral fat — off-label protocols and what actually works",
    body: "Tesamorelin is the only GHRH analog with a real human trial indication (HIV-associated lipodystrophy). 1-2 mg daily, FDA-approved for reducing visceral adipose tissue. The efficacy in that population is strong.\n\nOff-label for non-HIV visceral fat: some people swear by it, some think it's no better than CJC no-DAC. I'm running it for the first time and want to hear from people who've done direct comparisons or have before/after imaging.\n\nMy protocol: Tesa 1.4 mg pre-bed, Sub-Q abdomen, 12 weeks planned. Starting waist 39.5\", DEXA at week 0 and week 12 for visceral AT measurement specifically.",
    author: "apob_reader",
    daysAgo: 21,
    views: 2240,
    reactions: { LIKE: 6, USEFUL: 5 },
    replies: [
      { author: "hexaclinic", body: "Tesamorelin has unique affinity and pharmacokinetics that CJC no-DAC doesn't match. It's not just 'another GHRH analog.' The visceral AT reduction in Egrifta trials was 15-20% in 26 weeks, which is not a placebo-sized effect.\n\nThe off-label case outside HIV is less characterized but the mechanism is the same — tesa drives stronger and more sustained IGF-1 elevation than sermorelin/CJC. You'd expect similar visceral effects in non-HIV populations with visceral adiposity.", daysAgo: 21, reactions: { USEFUL: 11, AGREE: 7 } },
      { author: "dexa_devotee", body: "Ran tesa 1.4 mg 14 weeks, paired DEXA. Visceral AT: -18.2%. Subcutaneous abdominal: -6%. Total body fat: -3.8%. Waist: -1.4\". That's the ratio people should understand — tesa hits visceral disproportionately.", daysAgo: 20, reactions: { USEFUL: 12, AGREE: 6, LIKE: 4 } },
      { author: "apob_reader", body: "@dexa_devotee that delta is encouraging. Did your IGF run high on it? I'm watching that because 1.4 mg feels like it should push IGF harder than what I see people report.", daysAgo: 20, reactions: { LIKE: 2 } },
      { author: "dexa_devotee", body: "@apob_reader IGF went from 192 to 298 at week 8, held 280s through end. That's higher than CJC+Ipa would typically get me. Tesa pushes harder at the pituitary.", daysAgo: 19, reactions: { USEFUL: 6 } },
      { author: "hba1c_watch", body: "Tesa tends to transiently worsen insulin sensitivity more than CJC/Ipa. Watch fasting glucose. It usually normalizes after discontinuation but can be uncomfortable mid-cycle.", daysAgo: 19, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "igf_curve", body: "The trade-off matrix: tesa stronger effect, slightly worse glucose profile, more expensive. For visceral fat specifically it's worth the trade. For general GHS use (sleep, recovery) CJC+Ipa is better value.", daysAgo: 18, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "showmethestudy", body: "Non-HIV off-label tesa doesn't have the RCT backing of the on-label use. Mechanism-wise it should work but expect the effect size to be different in different populations. Non-HIV visceral fat has different drivers than HIV lipodystrophy.", daysAgo: 17, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "apob_reader", body: "Factoring in the glucose warning. Adding fasting glucose weekly and A1c at week 6 and 12.", daysAgo: 16, reactions: { USEFUL: 4 } },
      { author: "protocolpilot", body: "Tesa + CJC/Ipa at the same time is overkill and often degrades outcomes because you're overdriving GHRH receptor. Pick one GHRH — either tesa OR CJC, not both. Ipa can stack with either.", daysAgo: 15, reactions: { USEFUL: 5, AGREE: 4 } },
    ],
  },
  {
    title: "Hexarelin — the one nobody talks about honestly",
    body: "Hexarelin is a GHRP like Ipamorelin but it hits harder and bundles more side effects. Specifically:\n- Strongest GH pulse of the GHRP class\n- Also bumps prolactin and cortisol noticeably (unlike Ipa which is clean on both)\n- Tachyphylaxis develops fast — within 2-3 weeks the GH response attenuates significantly\n- Cardiac effects in rodent data are actually *positive* at low doses (cardioprotective) but this is not well-characterized in humans\n\nAt low dose (100 mcg or less) and in short cycles (2-3 weeks max) I think hexarelin has a niche — for people who've plateaued on Ipa and want a brief 'peak pulse' intervention. As a daily-driver GHRP it's a bad choice.\n\nAnyone running it currently? What dose and cycle length?",
    author: "hexaclinic",
    daysAgo: 31,
    views: 2180,
    reactions: { LIKE: 8, USEFUL: 7, AGREE: 4 },
    replies: [
      { author: "cyclecraft", body: "Ran hexarelin 100 mcg 3x daily for 3 weeks as a finisher to an 8-week CJC+Ipa cycle. GH pulse was noticeably bigger (subjective, no venous sampling obviously) and then by week 3 was clearly dropping. Tachyphylaxis is real and fast. Quit and did 6 weeks off.", daysAgo: 31, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "stackbuilder", body: "Hexarelin as a 'finisher' for 2 weeks makes sense. As a main compound it's a mistake. The prolactin creep alone should disqualify it for most users.", daysAgo: 30, reactions: { AGREE: 7, USEFUL: 4 } },
      { author: "panel_maxer", body: "Baseline prolactin at start of hex cycle, week 2, and week 4 in healthy males tends to go: 8 → 14 → 22 ng/mL. Not catastrophic but well into 'why is this on a GHS protocol' territory. Ipa does not do this.", daysAgo: 30, reactions: { USEFUL: 9, AGREE: 5 } },
      { author: "reggae_fiend", body: "I ran hexarelin as my first GHRP back in 2019 because it was cheap. Gyno flare at week 4 that took 2 months to resolve. Not doing that again. Newbies should start with Ipa, not Hex.", daysAgo: 29, reactions: { AGREE: 8, LIKE: 3 } },
      { author: "igf_curve", body: "The cortisol bump is the other reason. Mild but measurable — AM cortisol goes up 15-25% on hex. On Ipa it does not. If you have any HPA axis concerns, Hex is a bad pick.", daysAgo: 28, reactions: { USEFUL: 6, AGREE: 4 } },
      { author: "hexaclinic", body: "All confirming what I expected. Hex is basically in the 'interesting tool, wrong default choice' bucket. For 99% of users the right GHRP is Ipamorelin. Hex has a small niche for peak-pulse chasers running it 2 weeks at a time.", daysAgo: 28, reactions: { AGREE: 7, USEFUL: 3 } },
      { author: "showmethestudy", body: "The cardioprotective rodent data people cite for hex is at doses that don't translate meaningfully to human protocols. Don't use 'it might be good for the heart' as a justification for hex — that evidence doesn't exist in humans.", daysAgo: 26, reactions: { AGREE: 8, USEFUL: 5 } },
    ],
  },
  {
    title: "GHRP-2 vs GHRP-6 — and when appetite stimulation is a feature",
    body: "GHRP-6 is infamous for ravenous hunger. GHRP-2 has some appetite effect but way less. Both are older GHRP compounds that have been partially displaced by Ipa and Hexarelin.\n\nWhere GHRP-6 actually wins: underweight populations or people trying to bulk who can't eat enough. The hunger isn't a side effect, it's the point. Lean gainers who get full at 2800 kcal will find GHRP-6 turns them into 4000 kcal eaters effortlessly.\n\nGHRP-2 is a middle ground — decent pulse, mild appetite bump, slightly more prolactin than Ipa.\n\nWhen does this matter in 2026? Almost never because Ipa is better for most people. But if you're a skinny lifter trying to reach caloric targets, GHRP-6 has a role Ipa literally can't fill.",
    author: "protocolpilot",
    daysAgo: 23,
    views: 1320,
    reactions: { LIKE: 5, USEFUL: 4 },
    replies: [
      { author: "macrosguru", body: "GHRP-6 for the underweight lifter is underrated. I had a client (natural, lifelong skinny) go from 147 to 162 in 14 weeks on GHRP-6 100 mcg 3x daily because he finally could eat enough. Ipa wouldn't have done that.", daysAgo: 23, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "hexaclinic", body: "Correct take. GHRP-6 is niche, not obsolete. The feature is appetite. If that's what you need, use it. If not, Ipa is better.", daysAgo: 22, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "stackbuilder", body: "GHRP-2's prolactin bump is smaller than hex but bigger than Ipa. For comparable GH pulse it's still worse than Ipa in 2026 in almost every scenario.", daysAgo: 21, reactions: { USEFUL: 4 } },
      { author: "taper_time", body: "Cost consideration — GHRP-2 and GHRP-6 are cheaper than Ipa still. For someone budget-constrained, GHRP-2 at moderate dose is a reasonable entry point.", daysAgo: 19, reactions: { LIKE: 3 } },
      { author: "late_bloomer_m", body: "I've been on GHRP-6 + CJC no-DAC for bulk. Appetite is the whole game at 45. This is working where Ipa didn't.", daysAgo: 17, reactions: { LIKE: 2 } },
    ],
  },
  {
    title: "MK-677 — the one pill option, and its baggage",
    body: "MK-677 (ibutamoren) is the only GHS that works orally. Long half-life, GHSR agonist like Ipa but with very different kinetics — tonic elevation instead of pulsatile.\n\nPros:\n- One pill, once daily\n- Strong IGF-1 response (often 50-80% increase at 25 mg)\n- Good sleep effect (GHSR agonism, same mechanism as Ipa)\n\nCons:\n- Water retention at 25 mg is pronounced. Wrist puffiness, morning bloat.\n- Hunger increase is real and persistent — not a short-term side effect\n- Insulin resistance and fasting glucose bump, significant in some people\n- Tonic elevation disrupts natural pulsatile GH architecture more than injectable GHS\n\nMy take: great for someone who will never stick to injection schedule. Not ideal for people who can inject — CJC+Ipa gives most of the benefit without the water/hunger/glucose problems. What's the panel think?",
    author: "protocolwonk",
    daysAgo: 19,
    views: 2980,
    reactions: { LIKE: 9, USEFUL: 6, AGREE: 4 },
    replies: [
      { author: "hexaclinic", body: "Solid summary. The tonic vs pulsatile point is the most important — MK-677 at continuous agonism downregulates the GHSR partially over time, which is why people report 'it stops working after 8 weeks.' Injectable GHRP pulses preserve receptor sensitivity much better.", daysAgo: 19, reactions: { AGREE: 8, USEFUL: 7 } },
      { author: "hba1c_watch", body: "The glucose response is a real concern. I ran MK 25 mg for 10 weeks, fasting glucose went from 84 to 104, HOMA-IR from 1.1 to 2.3. Not prediabetic but clearly worse. Reversed within 4 weeks off.", daysAgo: 18, reactions: { USEFUL: 9, AGREE: 5 } },
      { author: "macrosguru", body: "The hunger is the disqualifier for cutting. People put MK in their cut stack and then wonder why they can't hit macros. MK is a bulk-only compound for most.", daysAgo: 17, reactions: { AGREE: 6, LIKE: 3 } },
      { author: "igf_curve", body: "IGF-1 response on MK is genuinely strong — I've seen bumps from 160 to 280 on 20-25 mg. Higher than any injectable GHS stack I've tracked. If IGF-1 elevation is the goal, MK is actually the strongest lever.", daysAgo: 16, reactions: { USEFUL: 7, AGREE: 4 } },
      { author: "restwise", body: "Sleep effect on MK is real and durable. Deep sleep goes up and stays up for as long as I run it. That's the part I can't replicate on injectable at the same intensity.", daysAgo: 15, reactions: { LIKE: 4 } },
      { author: "cyclecraft", body: "Dose-dependence on side effects is steep. MK at 10 mg is mostly tolerable. At 25 mg the water retention becomes real. A lot of people who hate MK ran it too high.", daysAgo: 13, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "dr_doubt", body: "MK-677 is the compound most likely to make a novice overestimate what GHS can do — IGF-1 bump looks great on paper, weight goes up, appetite is up, 'I must be growing.' Actually mostly water, some LBM maybe, mostly not what they think. Needs careful expectation management.", daysAgo: 11, reactions: { AGREE: 9, USEFUL: 5, LIKE: 3 } },
    ],
  },
  {
    title: "Timing — pre-bed vs AM fasted vs pre-workout",
    body: "For a 3x/day CJC+Ipa protocol, what's the consensus on timing?\n\nPre-bed is sacred, everyone agrees. But for the other two doses:\n- AM fasted pre-breakfast (30-45 min before first meal)\n- Midafternoon (3+ hr after lunch, 2+ hr before dinner)\n- Pre-workout (30-45 min before training)\n\nI've been doing AM fasted + midafternoon + pre-bed. Seeing people advocate AM + pre-workout + pre-bed. Which is better and why?",
    author: "cycle_wrangler",
    daysAgo: 17,
    views: 1080,
    reactions: { LIKE: 4, USEFUL: 3 },
    replies: [
      { author: "stackbuilder", body: "Pre-workout is mechanistically suspect because intra-workout glucose/insulin is about to spike anyway from sympathetic drive and any pre-workout carbs. If you're training fasted and pinning 45 min before, it works. If you have anything caloric in the pre-workout window, the pulse is blunted.", daysAgo: 17, reactions: { USEFUL: 7, AGREE: 5 } },
      { author: "hexaclinic", body: "The dose you want protected is pre-bed. The other two matter less than people think. Do whatever is logistically easy — AM fasted and midafternoon tend to be easier to keep fasted than pre-workout windows for most people.", daysAgo: 16, reactions: { AGREE: 6, USEFUL: 4 } },
      { author: "protocolpilot", body: "I do AM fasted + pre-bed only, 2x/day. The third dose is marginal for me. Feels equivalent to 3x for subjective effect. Cost/convenience win.", daysAgo: 15, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "cycle_wrangler", body: "Sounds like consensus is: AM fasted + midafternoon fasted + pre-bed is the default. Pre-workout only if genuinely fasted. And 2x/day may be enough for most.", daysAgo: 14, reactions: { LIKE: 3, USEFUL: 2 } },
      { author: "igf_curve", body: "The frequency question is genuinely under-studied in humans. Rodent data suggests 2x vs 3x is small delta on IGF. Stick with what's sustainable.", daysAgo: 12, reactions: { USEFUL: 3 } },
    ],
  },

  // ---------- QUIET (7) ----------
  {
    title: "CJC-1295 WITH DAC — who's still running it",
    body: "DAC (Drug Affinity Complex) extends CJC half-life to 6-8 days. Weekly injection, tonic GH elevation, much easier compliance.\n\nWith Ipa on DAC protocol, the GHRP is still pulsatile but the GHRH background is tonic. Is this better or worse than no-DAC pulsatile on both?\n\nMy read: worse for healthy-adult optimization because you disrupt natural pulse architecture. But maybe better for someone who can't pin 3x/day and would otherwise skip doses.",
    author: "taper_time",
    daysAgo: 15,
    views: 640,
    reactions: { LIKE: 3 },
    replies: [
      { author: "hexaclinic", body: "DAC blunts pulse amplitude and can suppress natural GHRH signaling more than no-DAC. Biologically suboptimal but not catastrophic. If the choice is DAC compliance vs no-DAC skipped doses, DAC wins. If the choice is DAC vs 3x/day no-DAC consistently, no-DAC wins.", daysAgo: 15, reactions: { AGREE: 5, USEFUL: 4 } },
      { author: "stackbuilder", body: "DAC + Ipa pre-bed only is a reasonable minimalist protocol. One weekly CJC-DAC, one daily pre-bed Ipa. Compliance is easy.", daysAgo: 14, reactions: { USEFUL: 4 } },
      { author: "showmethestudy", body: "Literature on CJC-DAC in humans is thinner than no-DAC. Be aware you're running the less-characterized variant.", daysAgo: 13, reactions: { USEFUL: 3 } },
    ],
  },
  {
    title: "IGF-1 test timing — when to draw",
    body: "Running CJC+Ipa 3x daily. Planning IGF-1 draw at week 8. When in the cycle (time of day, relation to last dose, fasted or not) gives the most meaningful number?",
    author: "bac_water_noob",
    daysAgo: 13,
    views: 480,
    reactions: { LIKE: 2 },
    replies: [
      { author: "panel_maxer", body: "Morning fasted, 8-12 hours after last dose. IGF-1 doesn't spike with each pulse — it integrates over days — so draw timing within a day matters less than people think, but consistency between draws matters a lot.", daysAgo: 13, reactions: { USEFUL: 7, AGREE: 3 } },
      { author: "igf_curve", body: "Agree. Keep your draw conditions identical every time — same lab, same time of day, same fasted state, same days post-dose. Trend is the data, not any single number.", daysAgo: 12, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "bac_water_noob", body: "So: Tuesday 8am, fasted, after Monday pre-bed dose + Tuesday AM dose skipped. Repeat conditions next draw. Got it.", daysAgo: 11, reactions: { THANKS: 2 } },
    ],
  },
  {
    title: "Carb cutoff before GHRH injection — how strict",
    body: "Protocol says no calories 2-3 hours pre-injection for GHRH compounds because elevated insulin blunts GH response. How strict does this have to be? Is 30 grams of carbs 90 min before going to kill my pulse?",
    author: "curious_catL",
    daysAgo: 10,
    views: 410,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Not kill, but meaningfully reduce. 30g carbs 90 min before pre-bed Ipa/CJC will cut your GH pulse roughly 30-50%. Protein/fat only are much less disruptive. The 2-3 hour rule is conservative — 90 min post-meal is acceptable if the meal wasn't carb-heavy.", daysAgo: 10, reactions: { USEFUL: 6, AGREE: 3 } },
      { author: "stackbuilder", body: "The pre-bed dose is the one where you protect the window hardest. AM fasted is easier to get right. If midday dose is post-meal, that's the one to 'relax' on — still do it, just know it's weaker.", daysAgo: 9, reactions: { USEFUL: 4 } },
      { author: "curious_catL", body: "OK so dinner by 7:30, snack only if protein, pre-bed Ipa at 10. That works for my schedule.", daysAgo: 8, reactions: { LIKE: 2 } },
    ],
  },
  {
    title: "GH axis suppression fear — will GHS tank my natural production",
    body: "Worry that's been sitting in my head: if I run GHS for 8 weeks, does my pituitary 'forget how' to pulse GH on its own and I'm stuck needing exogenous support to feel right?\n\nSeeing mixed things online. Some people say GHS is HPTA-neutral, others say long-term use suppresses endogenous production.\n\nWhat's the real picture?",
    author: "syringe_shy",
    daysAgo: 18,
    views: 920,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "hexaclinic", body: "Real picture: GHS does not cause durable HPG-axis-style shutdown the way exogenous rhGH can. GHS works via native pathways — you're stimulating your own pituitary to pulse, not replacing pituitary output.\n\nShort-term (weeks post-cycle) there's some somatostatin rebound and reduced pulse amplitude for 2-4 weeks. That resolves. Long-term, no durable suppression has been shown in the GHS literature at the doses and cycles this community runs.", daysAgo: 18, reactions: { USEFUL: 12, AGREE: 7, THANKS: 4 } },
      { author: "igf_curve", body: "The rhGH case is different — exogenous GH feedback-inhibits pituitary output and that suppression can take months to recover. GHS is not in that category.", daysAgo: 17, reactions: { USEFUL: 5, AGREE: 3 } },
      { author: "showmethestudy", body: "Long-term human data (>2 years continuous) on GHS is limited. 'No durable suppression shown' is accurate but partially because the studies aren't long enough. The cycle-on/cycle-off model is the risk-managed approach.", daysAgo: 15, reactions: { AGREE: 4, USEFUL: 3 } },
      { author: "syringe_shy", body: "This is what I needed to hear. 8wk on/4wk off and I'm probably fine. Thanks @hexaclinic.", daysAgo: 14, reactions: { THANKS: 3 } },
    ],
  },
  {
    title: "Ipa 200 → 300 mcg dose plateau, diminishing returns",
    body: "Ran Ipa 200 mcg 3x daily for 10 weeks, great response. Bumped to 300 mcg for the last 4 weeks thinking more = more. IGF-1 at end of 200 mcg phase was 246. IGF-1 at end of 300 mcg phase was 254. Subjectively no difference.\n\nSo the pulse is basically maxing out at 200 mcg at this dose cadence and 300 is waste. Is that consistent with what others see?",
    author: "stack_nerd",
    daysAgo: 11,
    views: 580,
    reactions: { LIKE: 3, USEFUL: 2 },
    replies: [
      { author: "hexaclinic", body: "Yes. Ipa saturates the GHSR at around 200-250 mcg per pulse in most healthy adults. Going higher just increases cost without increasing GH output. The dose-response curve flattens hard above 250.", daysAgo: 11, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "stackbuilder", body: "200 mcg is the number. I've seen this pattern repeatedly. People 'optimize' to 300-400 and get no signal delta. Stick with 200 and save the peptide.", daysAgo: 10, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "igf_curve", body: "The way to push past the plateau is frequency, not dose. 200 mcg 4x daily would likely push IGF higher than 300 mcg 3x daily. Pulses matter more than peak pulse amplitude past saturation.", daysAgo: 9, reactions: { USEFUL: 5, AGREE: 4 } },
    ],
  },
  {
    title: "Cycle structure — 8 on / 4 off vs 4 on / 2 off",
    body: "Standard GHS cycle advice is 8 weeks on, 4 weeks off. But I've seen some protocols running 4 on / 2 off on rotation. Is the 8/4 cadence evidence-based or just community convention?",
    author: "cycle_wrangler",
    daysAgo: 8,
    views: 390,
    reactions: { LIKE: 2 },
    replies: [
      { author: "cyclecraft", body: "Convention more than evidence. 8/4 is a reasonable default but 4/2 achieves similar IGF average with less time blunted off-cycle. The 'right' answer depends on goal and receptor sensitivity over time.", daysAgo: 8, reactions: { USEFUL: 4, AGREE: 3 } },
      { author: "hexaclinic", body: "For GHSR compounds (GHRPs), shorter on-phases preserve receptor sensitivity better — 4/2 is arguably better than 8/4 for pure pulse preservation. For GHRH analogs, it matters less. Most people run mixed stacks so 8/4 or 6/3 are sane compromises.", daysAgo: 7, reactions: { USEFUL: 5, AGREE: 4 } },
      { author: "protocolwonk", body: "I ran 4/2 for a year and my IGF trend was more stable than the 8/4 years. Fewer peak/trough swings, more consistent sleep effect.", daysAgo: 5, reactions: { LIKE: 3, USEFUL: 2 } },
    ],
  },
  {
    title: "Prolactin on hexarelin-heavy stack — when to panic",
    body: "Ran hex 150 mcg 3x daily + CJC no-DAC for 5 weeks. Prolactin at baseline was 9 ng/mL, at week 4 is 31. Reference range top is 20. Not getting gyno symptoms but the number is concerning.\n\nDrop hex? Add a dopamine agonist? Wait it out?",
    author: "labrat_ish",
    daysAgo: 6,
    views: 350,
    reactions: { LIKE: 2 },
    replies: [
      { author: "hexaclinic", body: "Drop hex now. 31 is over range and climbing is the bad pattern. You don't wait out prolactin creep from a known prolactin-bumping compound. Swap to Ipa, recheck in 4 weeks.", daysAgo: 6, reactions: { USEFUL: 8, AGREE: 5 } },
      { author: "reggae_fiend", body: "Adding a dopamine agonist is not the move. The fix is removing the cause. DA agonists for prolactin management in a non-clinical context is chasing a side effect rather than addressing the protocol mistake.", daysAgo: 5, reactions: { AGREE: 6, USEFUL: 3 } },
      { author: "panel_maxer", body: "150 mcg hex 3x daily is a high dose. Hex is a short-cycle low-dose compound. This was always going to happen on that protocol.", daysAgo: 5, reactions: { AGREE: 4, USEFUL: 2 } },
      { author: "labrat_ish", body: "Dropping hex tonight. Staying on CJC, adding Ipa 200 3x. Will retest prolactin in 4 weeks. Thanks.", daysAgo: 4, reactions: { THANKS: 3 } },
    ],
  },
];
