import type { SeedThread } from "../types";

export const THREADS_GENERAL: SeedThread[] = [
  // ============================================================
  // PINNED WELCOME THREAD
  // ============================================================
  {
    title: "Welcome to PepAtlas — read this first",
    body: "Hey everyone, welcome to PepAtlas.\n\nThis is the general category — off-topic, news, supplier chat, gear questions, community stuff. Lighter than the protocol threads, but the same rules apply: no source sharing in open threads, be decent to each other, and if you're brand new, please introduce yourself below.\n\nA few things to know:\n- Use categories correctly. Bloodwork goes in bloodwork-metrics. Protocols go in protocol-discussions. Beginner questions go in beginner-questions. General is for everything else.\n- Lurk as long as you want. We have more lurkers than posters and that's fine.\n- Don't ask for sources in open threads. Ever.\n- If someone's being a jerk, report — don't fight them in public.\n- The FUNNY reaction exists for a reason. Use it.\n\nDrop a reply with your name (or handle), roughly what you're running or interested in, and one thing you've learned that you wish you'd known earlier. Keep it short. This thread is the permanent welcome post.\n\nGlad you're here.",
    author: "cardinal_rule",
    daysAgo: 145,
    pinned: true,
    views: 8420,
    reactions: { LIKE: 89, THANKS: 34, USEFUL: 22 },
    replies: [
      { author: "lucidverse", body: "Pinning my own cosign on this. The 'don't ask for sources' rule is the one that gets new people banned the fastest, so internalize it early. Otherwise — welcome.", daysAgo: 145, reactions: { LIKE: 41, AGREE: 18 } },
      { author: "wanderlite", body: "Hi — wanderlite. New, haven't pinned yet. Mostly here to read. Thing I've learned: don't buy anything until you've read a category front to back.", daysAgo: 143, reactions: { LIKE: 22, USEFUL: 6 } },
      { author: "first_vial", body: "first_vial, running my first BPC-157 cycle for a shoulder thing. Wish I'd known that bac water isn't the same as sterile water and I definitely made that mistake.", daysAgo: 142, reactions: { LIKE: 18, FUNNY: 11 } },
      { author: "hexaclinic", body: "hexaclinic. Been around peptides for ~8 years. Wish I'd known that bloodwork beats bro-science every single time. Welcome new folks.", daysAgo: 141, reactions: { LIKE: 34, AGREE: 12 } },
      { author: "petal_push", body: "petal_push, hi! GLP-1 user, sema for about 5 months. Thing I wish I'd known: titration is not optional. Don't skip steps.", daysAgo: 140, reactions: { LIKE: 19, USEFUL: 8 } },
      { author: "reggae_fiend", body: "reggae_fiend, old head. Running nothing wild right now, just maintenance TB-500 for a bad shoulder. Wish I knew: 90% of 'magic' compounds are just sleep and protein in disguise.", daysAgo: 139, reactions: { LIKE: 28, AGREE: 19, FUNNY: 7 } },
      { author: "bpc_baby", body: "bpc_baby. The name is literal — BPC is the only thing I've run. Wish I'd known subq is way less scary than I thought.", daysAgo: 138, reactions: { LIKE: 14 } },
      { author: "theoretic", body: "theoretic. Interested in GH secretagogues and longevity protocols. Wish I'd known that half-life matters more than dose for most of these.", daysAgo: 137, reactions: { LIKE: 22, USEFUL: 15 } },
      { author: "curious_catL", body: "curious_catL — hi, still lurking mostly but posting here to say hi. Thing I've learned: ask dumb questions early, not after you've already ordered something.", daysAgo: 136, reactions: { LIKE: 17, AGREE: 9 } },
      { author: "tirzepatide_tim", body: "tim, tirz for ~14 months, down 68lb. Wish I'd known that the side effects fade and the 'is this even working' weeks are normal.", daysAgo: 135, reactions: { LIKE: 26, USEFUL: 11 } },
      { author: "stackbuilder", body: "stackbuilder, I like stacks (shocking). Wish I'd known that single compounds with clean logs beat 5-compound stacks 90% of the time.", daysAgo: 134, reactions: { LIKE: 21, AGREE: 14 } },
      { author: "quietstorm", body: "quietstorm. Mostly lurk. Here 3 years. Wish I'd known how many people in this space are just guessing confidently.", daysAgo: 133, reactions: { LIKE: 31, FUNNY: 18, AGREE: 12 } },
      { author: "acl_again", body: "acl_again — second ACL, hence the handle. Recovery peptides saved my knee. Wish I'd known TB-500 takes a full 4 weeks before you feel it.", daysAgo: 132, reactions: { LIKE: 16, USEFUL: 9 } },
      { author: "dr_doubt", body: "dr_doubt. I'm the guy who asks for citations. Wish I'd known how much of this field is case reports dressed up as consensus.", daysAgo: 131, reactions: { LIKE: 18, AGREE: 14 } },
      { author: "reads_more_posts", body: "reads_more_posts. I read a lot, post rarely. Hi.", daysAgo: 130, reactions: { LIKE: 22, FUNNY: 8 } },
      { author: "semax_mornings", body: "semax_mornings. Mostly cognitive stuff. Wish I'd known that sleep is still the best nootropic by a wide margin.", daysAgo: 128, reactions: { LIKE: 14, AGREE: 11 } },
      { author: "silentscroll", body: "silentscroll. Second post ever on this forum. First was a typo I deleted. Hi.", daysAgo: 127, reactions: { FUNNY: 19, LIKE: 11 } },
      { author: "new2peptides", body: "new2peptides, literally just signed up. Wish I'd known... well I don't know anything yet, that's why I'm here.", daysAgo: 124, reactions: { LIKE: 13, FUNNY: 6 } },
      { author: "nad_nightowl", body: "nad_nightowl, NAD+ and sleep stuff. Wish I'd known that NAD IV drip is mostly theater unless you have a specific deficiency.", daysAgo: 120, reactions: { LIKE: 15, AGREE: 9 } },
      { author: "polite_guest", body: "Hi everyone, polite_guest. Reading more than posting. Appreciate the community.", daysAgo: 118, reactions: { LIKE: 19, THANKS: 6 } },
    ],
  },

  // ============================================================
  // LOCKED THREAD (heated supplier trash-talk)
  // ============================================================
  {
    title: "[LOCKED] Anyone else getting screwed by [supplier]? Third bad vial this month",
    body: "Cannot believe this is still happening. Third vial from the same place in six weeks that came with a cracked seal and no desiccant. Customer service is a joke, they keep telling me to 'return it at my expense' which — why would I do that on a reship?\n\nI know we can't name names in open threads but if you know, you know. Avoid.",
    author: "fresh_cycle",
    daysAgo: 42,
    locked: true,
    views: 4210,
    reactions: { AGREE: 38, LIKE: 19 },
    replies: [
      { author: "frontloader", body: "Had the same issue twice. Got a reship the third time only because I threatened a chargeback. Don't just accept 'return at your expense' — push back.", daysAgo: 42, reactions: { AGREE: 22, USEFUL: 8 } },
      { author: "loading_phase", body: "Everyone here knows who you're talking about and the answer is yes, their QC has been dogshit since November. I switched in December and haven't looked back.", daysAgo: 42, reactions: { AGREE: 31, LIKE: 9 } },
      { author: "cyclecraft", body: "Chargeback works. I did it. Money back in 4 days.", daysAgo: 42, reactions: { USEFUL: 14 } },
      { author: "nullhypothesis", body: "This is the third 'vague complaint' supplier thread this month. Can we please not do this in open — it always spirals.", daysAgo: 41, reactions: { AGREE: 18 } },
      { author: "placebo_possible", body: "Agreed with nullhypothesis. No names, no screenshots of invoices, nothing useful to anyone but drama.", daysAgo: 41, reactions: { AGREE: 14 } },
      { author: "goal_driven", body: "I get the frustration but yeah this is going to get locked, just save your fight for the DM.", daysAgo: 41, reactions: { AGREE: 9 } },
      { author: "protocolpilot", body: "Anyone pretending they don't know which vendor is being discussed is being cute. That said — yeah, locking vibes incoming.", daysAgo: 41, reactions: { FUNNY: 17, AGREE: 8 } },
      { author: "panel_maxer", body: "If your desiccant is missing and the seal is cracked, that's a sterility issue, not a vibes issue. Do not reconstitute that vial. Full stop.", daysAgo: 41, reactions: { USEFUL: 24, AGREE: 15 } },
      { author: "fresh_cycle", body: "To be clear — I threw the cracked ones out. I'm not stupid. Just venting.", daysAgo: 41, reactions: { LIKE: 12 } },
      { author: "lucidverse", body: "Locking this. @fresh_cycle your frustration is legit, and everyone knows which vendor is being discussed, but open supplier drama threads are against the rules. DM me if you want to file a complaint pattern and we'll track it internally. Thread closed.", daysAgo: 40, reactions: { AGREE: 22, THANKS: 11, LIKE: 8 } },
    ],
  },

  // ============================================================
  // POPULAR THREADS (15-22 replies)
  // ============================================================
  {
    title: "What does everyone do IRL? Curious about the community",
    body: "Been here a couple months and I'm genuinely curious who I'm posting next to. You don't have to be specific — industry/general area is fine.\n\nI'll start: software, fully remote, mid-30s. Got into peptides because my joints started making noises I didn't approve of.",
    author: "recomp_rex",
    daysAgo: 89,
    views: 5120,
    reactions: { LIKE: 47, FUNNY: 12 },
    replies: [
      { author: "hexaclinic", body: "Physician. Outpatient internal med. Which makes the 'research chemicals' angle extra funny at dinner parties.", daysAgo: 89, reactions: { FUNNY: 48, LIKE: 22 } },
      { author: "dr_doubt", body: "Also physician (different specialty). We are more common in this space than you'd think. We're also the ones asking for citations.", daysAgo: 89, reactions: { LIKE: 31, FUNNY: 18 } },
      { author: "pallet_jack", body: "Warehouse logistics, as the handle suggests. 12-hour shifts. Peptides are what's keeping my lower back intact at 44.", daysAgo: 89, reactions: { LIKE: 29, AGREE: 8 } },
      { author: "cbc_cmp", body: "Lab tech in a clinical setting. That's why I'm annoying about panels.", daysAgo: 89, reactions: { LIKE: 22, FUNNY: 14 } },
      { author: "reggae_fiend", body: "Retired. Used to be a carpenter. Now I garden and inject small things into my belly fat.", daysAgo: 88, reactions: { FUNNY: 62, LIKE: 24 } },
      { author: "tirzepatide_tim", body: "Accountant. Sedentary job was half the reason I needed GLP-1 in the first place.", daysAgo: 88, reactions: { LIKE: 18, AGREE: 11 } },
      { author: "acl_again", body: "Physical therapist, which is both convenient and embarrassing when I tear my ACL again.", daysAgo: 88, reactions: { FUNNY: 44, LIKE: 19 } },
      { author: "the_architect_p", body: "Architect. Hence the handle. I like structure in my protocols too.", daysAgo: 87, reactions: { LIKE: 15, FUNNY: 9 } },
      { author: "selank_silence", body: "Academic — neuroscience-adjacent. Cognitive stuff is both my job and my hobby, which is unhealthy.", daysAgo: 87, reactions: { LIKE: 17, FUNNY: 6 } },
      { author: "mothra", body: "Airline pilot. Peptides help me recover from the schedule.", daysAgo: 86, reactions: { LIKE: 24, USEFUL: 5 } },
      { author: "fridge_protein", body: "Food scientist. I think about protein all day and then come home and inject more of it.", daysAgo: 86, reactions: { FUNNY: 31, LIKE: 12 } },
      { author: "glp1_doctor_pt", body: "Pharmacist. It is wild being on the dispensing side of GLP-1s and also being a user.", daysAgo: 85, reactions: { LIKE: 28, FUNNY: 14 } },
      { author: "weekendwarrior_p", body: "Finance, NYC. Not proud of the schedule. Peptides are partly a sleep-debt repair mechanism.", daysAgo: 84, reactions: { LIKE: 12, AGREE: 8 } },
      { author: "quietstorm", body: "I will keep mine to myself but I'll say there's a surprising number of lawyers here if you pay attention.", daysAgo: 84, reactions: { FUNNY: 29, LIKE: 11 } },
      { author: "dexa_devotee", body: "Researcher, adjacent to sports science. That's why I pay for a DEXA every 90 days like a weirdo.", daysAgo: 83, reactions: { LIKE: 16, FUNNY: 7 } },
      { author: "notes_taker", body: "Teacher. Middle school. If I tried to explain any of this to my coworkers they would file a report.", daysAgo: 82, reactions: { FUNNY: 41, LIKE: 14 } },
      { author: "reads_more_posts", body: "Librarian-adjacent. Hence the handle.", daysAgo: 81, reactions: { LIKE: 18, FUNNY: 9 } },
      { author: "nopain_noreign", body: "Former pro athlete (small sport, you haven't heard of it). Currently just a guy with a lot of surgeries.", daysAgo: 79, reactions: { LIKE: 27, AGREE: 6 } },
    ],
  },
  {
    title: "Favorite supplier / where are people buying these days",
    body: "Obviously no names in the open. More curious about what people look for — do you prioritize COAs, turnaround time, shipping, customer service? What's non-negotiable for you and what's a nice-to-have?\n\nI'm mostly trying to upgrade my mental checklist. Been burned twice and I'd like to not make it three.",
    author: "stack_nerd",
    daysAgo: 67,
    views: 4890,
    reactions: { LIKE: 34, USEFUL: 21 },
    replies: [
      { author: "hexaclinic", body: "COA is non-negotiable. Third-party COA specifically. Any vendor that runs their own 'internal' testing is not a serious vendor.", daysAgo: 67, reactions: { AGREE: 38, USEFUL: 19 } },
      { author: "dr_doubt", body: "Third-party COA, recent batch, readable HPLC trace. Everything else is secondary. Fast shipping with no COA is nothing.", daysAgo: 67, reactions: { AGREE: 29, LIKE: 11 } },
      { author: "protocolwonk", body: "For me: reliable reship policy. Stuff happens in shipping. How they handle it tells you everything.", daysAgo: 66, reactions: { AGREE: 24, USEFUL: 8 } },
      { author: "panel_maxer", body: "COA + proper lyo (you can tell from photos if you know what to look for) + consistent batch quality over time. I don't switch vendors unless I have to.", daysAgo: 66, reactions: { USEFUL: 21, AGREE: 11 } },
      { author: "loading_phase", body: "Customer service is underrated. When something goes wrong — and it will — you want a human who responds in 24hrs, not a chatbot that takes 3 business days.", daysAgo: 66, reactions: { AGREE: 18, LIKE: 7 } },
      { author: "cyclecraft", body: "I rank them by: COA, then consistency, then price. Fast shipping is nice but I've gotten garbage from fast shippers and gold from slow ones.", daysAgo: 65, reactions: { AGREE: 14 } },
      { author: "frontloader", body: "Discreet packaging is actually on my list. I have a nosy mail person.", daysAgo: 65, reactions: { FUNNY: 28, LIKE: 9 } },
      { author: "the_stats_guy", body: "Request multiple COAs from different batches. If they only have one they keep sending you, that's a flag.", daysAgo: 64, reactions: { USEFUL: 22, AGREE: 8 } },
      { author: "homocystein_x", body: "Also: does the COA have identity testing (mass spec) or just purity? 'Purity 99%' of the wrong molecule is still zero useful to you.", daysAgo: 64, reactions: { USEFUL: 31, AGREE: 14 } },
      { author: "apob_reader", body: "^ this is the question nobody asks. Mass spec identity or don't bother.", daysAgo: 63, reactions: { AGREE: 16 } },
      { author: "slow_titrate", body: "For GLP-1s specifically: clean lyo, correct vial labeling, and no weird discoloration. I've had two vendors send me yellow-tinged tirz. Not running that.", daysAgo: 62, reactions: { USEFUL: 14, AGREE: 9 } },
      { author: "cycle_wrangler", body: "People forget: a good vendor might have a bad batch. A bad vendor is consistently bad. Don't judge on one order.", daysAgo: 61, reactions: { AGREE: 19, LIKE: 6 } },
      { author: "kineticdrift", body: "Nice-to-have for me: international vs domestic. Domestic costs more but it's what I pay for when I actually need something fast.", daysAgo: 60, reactions: { AGREE: 11 } },
      { author: "polite_guest", body: "Lurker here — this whole thread is the checklist I wish existed when I started. Thanks.", daysAgo: 58, reactions: { THANKS: 22, LIKE: 14 } },
      { author: "once_per_month", body: "+1 to polite_guest. Saving this thread.", daysAgo: 57, reactions: { LIKE: 11, THANKS: 6 } },
      { author: "showmethestudy", body: "One more: how do they handle custody of the vial between manufacturer and customer? Reputable vendors answer this; shady ones get defensive.", daysAgo: 55, reactions: { USEFUL: 18, AGREE: 9 } },
      { author: "stack_nerd", body: "OP — this is exactly the thread I needed, thanks everyone. Updated my checklist: 1) third-party COA with mass spec ID, 2) multi-batch transparency, 3) reship policy, 4) human CS, 5) discreet packaging. In that order.", daysAgo: 54, reactions: { THANKS: 24, USEFUL: 18, LIKE: 14 } },
      { author: "citation_required", body: "Bookmarking this post as the only acceptable answer to the 'best vendor' question going forward.", daysAgo: 52, reactions: { AGREE: 22, FUNNY: 11, LIKE: 7 } },
    ],
  },
  {
    title: "Peptide myths that won't die",
    body: "Every week I see someone in beginner-questions repeat a thing that I'd thought we collectively debunked six times over. Let's gather them in one place so we can link here.\n\nI'll kick it off: 'BPC-157 can heal literally anything.' No. It helps tendons, connective tissue, and GI. It is not magic. It's a tool.",
    author: "showmethestudy",
    daysAgo: 58,
    views: 5340,
    reactions: { LIKE: 52, AGREE: 38, USEFUL: 19 },
    replies: [
      { author: "nullhypothesis", body: "'GH peptides increase GH naturally so there are no side effects.' False. Elevated IGF-1, water retention, insulin resistance are all real. Natural ≠ consequence-free.", daysAgo: 58, reactions: { AGREE: 34, USEFUL: 16 } },
      { author: "dr_doubt", body: "'Subq dose is the same as IM dose.' The pharmacokinetics differ. For a lot of compounds it matters.", daysAgo: 58, reactions: { AGREE: 21, USEFUL: 11 } },
      { author: "hexaclinic", body: "'You need to cycle BPC.' No actual evidence for this. The cycle-everything mindset gets copy-pasted from AAS culture and doesn't always apply.", daysAgo: 57, reactions: { AGREE: 31, USEFUL: 14 } },
      { author: "panel_maxer", body: "'Bloodwork doesn't matter if you feel fine.' This one kills me. You can feel fine with ApoB at 140. Feeling fine is not a diagnostic.", daysAgo: 57, reactions: { AGREE: 29, USEFUL: 18 } },
      { author: "apob_reader", body: "^ preach.", daysAgo: 57, reactions: { AGREE: 11 } },
      { author: "igf_curve", body: "'IGF-1 at the top of the range is optimal.' Top of range in a 25-year-old reference is not the same as optimal for a 45-year-old. Context collapses under a single number.", daysAgo: 56, reactions: { USEFUL: 24, AGREE: 15 } },
      { author: "theoretic", body: "'More is better because the receptor desensitizes anyway.' That's a lazy read of pharmacology and it's getting people dosed into oblivion.", daysAgo: 56, reactions: { AGREE: 19, USEFUL: 9 } },
      { author: "microdose_glp1", body: "'GLP-1 microdosing gives you all the benefits with none of the side effects.' It gives you fewer side effects and correspondingly less of the benefit. The math still has to math.", daysAgo: 55, reactions: { AGREE: 28, USEFUL: 12 } },
      { author: "placebo_possible", body: "'I know it's working because I feel it immediately.' Most peptides have a delayed mechanism. If you feel something in 20 minutes, that's pharmacology or placebo — usually the latter.", daysAgo: 55, reactions: { AGREE: 22, FUNNY: 11 } },
      { author: "citation_required", body: "'Every rat study translates to humans 1:1.' No. Rat half-life, rat dose-response, rat endocrine system — not yours.", daysAgo: 54, reactions: { AGREE: 19, USEFUL: 8 } },
      { author: "lucidverse", body: "'GH fasting is required or it won't work.' Mild insulin blunting is real, but 'required' is too strong. The data is thinner than the forum consensus suggests.", daysAgo: 53, reactions: { AGREE: 24, USEFUL: 11 } },
      { author: "cardinal_rule", body: "'If it's not FDA-approved it's unsafe.' Also 'if it's not FDA-approved it doesn't work.' Both are wrong for opposite reasons.", daysAgo: 52, reactions: { AGREE: 22, LIKE: 14 } },
      { author: "reggae_fiend", body: "'Reconstitute with bac water and it lasts forever.' Bac is stable for ~28 days and a peptide in solution degrades on its own schedule. Forever is generous.", daysAgo: 51, reactions: { AGREE: 19, USEFUL: 9 } },
      { author: "homocystein_x", body: "'Natural test production is protected on peptide-only cycles.' Depends what you're running and how hard. CJC+ipa low dose, sure. Heavy GHRP daily for a year, less sure.", daysAgo: 50, reactions: { AGREE: 14, USEFUL: 6 } },
      { author: "protocolpilot", body: "'You can just copy any protocol from a podcast.' The protocol was designed for the guy telling the story. Not for you.", daysAgo: 49, reactions: { AGREE: 31, FUNNY: 11 } },
      { author: "the_stats_guy", body: "'Anecdotes from 4 people = consensus.' Sample size of 4 isn't a trend, it's a coincidence.", daysAgo: 48, reactions: { AGREE: 22, LIKE: 8 } },
      { author: "showmethestudy", body: "OP edit — keeping a running list. Thanks all. This is a good reference thread to link the next time someone asks 'but I read on Reddit...'", daysAgo: 46, reactions: { THANKS: 18, LIKE: 14 } },
    ],
  },
  {
    title: "What I wish I knew 2 years ago",
    body: "Two years in the peptide rabbit hole today. Feeling reflective. Drop one thing you'd tell 2-years-ago-you if you could.\n\nMine: I wish I knew that the first 6 months of results aren't the peptide — they're the novelty of finally caring about recovery and sleep and protein. The peptide is maybe 30% of what you felt. Don't anchor your expectations on that window.",
    author: "protocolwonk",
    daysAgo: 72,
    views: 4230,
    reactions: { LIKE: 58, AGREE: 32, USEFUL: 18 },
    replies: [
      { author: "reggae_fiend", body: "That the honeymoon phase fools you into thinking 10 compounds all work. Strip it down and retest.", daysAgo: 72, reactions: { AGREE: 28, USEFUL: 11 } },
      { author: "hexaclinic", body: "That most of what I attributed to a compound was actually better sleep hygiene and a coincidentally good training block.", daysAgo: 71, reactions: { AGREE: 31, USEFUL: 14 } },
      { author: "quietstorm", body: "That I should have tracked ONE metric consistently for a year rather than eight metrics for three weeks each.", daysAgo: 71, reactions: { AGREE: 22, USEFUL: 17 } },
      { author: "theoretic", body: "That lower doses with longer duration nearly always beat higher doses over short windows. Nearly always.", daysAgo: 70, reactions: { AGREE: 29, USEFUL: 13 } },
      { author: "acl_again", body: "That recovery peptides don't replace rehab. They make rehab more productive. Skipping PT and running TB-500 is a fast road to re-injury.", daysAgo: 70, reactions: { USEFUL: 24, AGREE: 15 } },
      { author: "recomp_rex", body: "That body recomp is 80% kitchen. The peptides don't override the macros.", daysAgo: 69, reactions: { AGREE: 21, LIKE: 9 } },
      { author: "dexa_devotee", body: "That feelings aren't data. DEXA twice a year is the best lie-detector money can buy.", daysAgo: 68, reactions: { AGREE: 19, USEFUL: 14 } },
      { author: "igf_curve", body: "That IGF-1 trends matter more than single IGF-1 readings. Single numbers are just noise.", daysAgo: 67, reactions: { AGREE: 17, USEFUL: 11 } },
      { author: "semax_mornings", body: "That nootropic stacking is 90% placebo layered on one actually active compound. Isolate first.", daysAgo: 66, reactions: { AGREE: 22, FUNNY: 8 } },
      { author: "fat_loss_log", body: "That rebound is real and starting GLP-1 without an exit plan is how you end up back where you started plus 8 pounds.", daysAgo: 65, reactions: { USEFUL: 19, AGREE: 14 } },
      { author: "tb500_train", body: "That if you feel something on day 2, it's probably bac water placebo. Real TB-500 takes weeks.", daysAgo: 64, reactions: { AGREE: 16, LIKE: 7 } },
      { author: "stack_nerd", body: "That chasing the newest compound is almost always worse than optimizing the basics you already run.", daysAgo: 62, reactions: { AGREE: 28, USEFUL: 11 } },
      { author: "reads_more_posts", body: "That reading more and posting less is a fine way to use this place for a long time.", daysAgo: 60, reactions: { LIKE: 34, AGREE: 11 } },
      { author: "dr_doubt", body: "That my internal medicine training didn't prepare me for the actual day-to-day of this stuff. The forums did.", daysAgo: 58, reactions: { LIKE: 22, FUNNY: 14 } },
      { author: "protocolwonk", body: "This thread is exactly what I hoped. Bookmarking.", daysAgo: 55, reactions: { THANKS: 18, LIKE: 9 } },
    ],
  },

  // ============================================================
  // ACTIVE THREADS (5-10 replies)
  // ============================================================
  {
    title: "Fridge organization setups — show me your vial drawer",
    body: "Getting embarrassing over here. Vials in a cardboard box in the butter compartment. Lids mixed with cap-covers. I know there are people here with labeled bins and little trays and I need inspiration before my partner stages an intervention.",
    author: "petal_push",
    daysAgo: 34,
    views: 1820,
    reactions: { LIKE: 24, FUNNY: 18 },
    replies: [
      { author: "the_architect_p", body: "I use clear acrylic tiered shelves meant for nail polish. Stackable, washable, and each tier holds ~18 10mL vials. Total lifesaver.", daysAgo: 34, reactions: { USEFUL: 19, LIKE: 11 } },
      { author: "frontloader", body: "Small plastic bento boxes from Daiso. $2 each. Label maker for the lids. Don't overthink it.", daysAgo: 34, reactions: { USEFUL: 14, LIKE: 8 } },
      { author: "fridge_protein", body: "Butter compartment is too warm and the temperature swings. Move them to the back middle shelf. Peptides want stable cold, not coldest cold.", daysAgo: 33, reactions: { USEFUL: 22, AGREE: 9 } },
      { author: "cycle_wrangler", body: "Mini fridge. Dedicated. Separate from food. Not worth the stress.", daysAgo: 33, reactions: { LIKE: 18, AGREE: 11 } },
      { author: "bpc_baby", body: "Wait — butter compartment really is warmer? I've been doing this wrong for months.", daysAgo: 32, reactions: { LIKE: 9 } },
      { author: "hexaclinic", body: "Yes. Butter compartment is designed to keep butter soft-spreadable. That's the opposite of what you want.", daysAgo: 32, reactions: { USEFUL: 22, LIKE: 8 } },
      { author: "petal_push", body: "This thread has saved my marriage and possibly my peptides. Thank you.", daysAgo: 31, reactions: { FUNNY: 28, THANKS: 11 } },
      { author: "notes_taker", body: "Photos would be great. Can someone drop a pic of their setup?", daysAgo: 30, reactions: { AGREE: 14 } },
    ],
  },
  {
    title: "Best insulin syringes (brand comparison)",
    body: "I've been using BD 0.5cc 29g 1/2\" for ~2 years. No complaints. But I'm hearing good things about EasyTouch and also seeing people on here use Nipro. Before I buy a box of 100 of something new, what's the actual honest take?",
    author: "syringe_shy",
    daysAgo: 41,
    views: 2110,
    reactions: { LIKE: 18 },
    replies: [
      { author: "nopain_noreign", body: "BD Ultra-Fine is the gold standard for a reason. Sharp, smooth plunger, consistent gauge. Pay the extra for them.", daysAgo: 41, reactions: { AGREE: 22, USEFUL: 11 } },
      { author: "loading_phase", body: "EasyTouch are fine for the price — maybe 80% of a BD. Plunger occasionally sticks. Good backup when BD is backordered.", daysAgo: 41, reactions: { USEFUL: 14 } },
      { author: "pallet_jack", body: "Nipro — I like them. Slightly longer needle on some sizes. Go-to for IM.", daysAgo: 40, reactions: { LIKE: 9 } },
      { author: "cyclecraft", body: "Anything but ReliOn. Too stiff plunger, I've had two needles bend on me.", daysAgo: 40, reactions: { AGREE: 14 } },
      { author: "glp1_doctor_pt", body: "From a pharmacy perspective: BD, EasyTouch, Nipro are the three that consistently pass QC. Anything else is a coin flip. Gauge accuracy matters.", daysAgo: 39, reactions: { USEFUL: 22, AGREE: 9 } },
      { author: "acl_again", body: "For subq on GLP-1: 31g. You won't feel it. 29g is overkill for 0.25mL of tirz.", daysAgo: 38, reactions: { USEFUL: 11, AGREE: 6 } },
      { author: "syringe_shy", body: "Great, sticking with BD and maybe picking up EasyTouch as backup. Thanks all.", daysAgo: 37, reactions: { THANKS: 9 } },
    ],
  },
  {
    title: "Accidentally injected air — it's fine right?",
    body: "Subq. Drew a tiny bubble I didn't see. Injected. Was mostly done before I noticed. About to panic but also I'm pretty sure this is fine for subq because it's not going into a vein. Someone tell me I'm not dying.",
    author: "bac_water_noob",
    daysAgo: 28,
    views: 3410,
    reactions: { FUNNY: 38, LIKE: 11 },
    replies: [
      { author: "hexaclinic", body: "You're fine. Subq air is almost entirely benign. You'd need a lot more air than a bubble, and it'd need to go into a vein, to be dangerous. Stop googling.", daysAgo: 28, reactions: { USEFUL: 34, THANKS: 19, LIKE: 11 } },
      { author: "dr_doubt", body: "Co-signing hexaclinic. We're talking hundreds of mL of air IV before things get dicey. A bubble subq is not even on the radar.", daysAgo: 28, reactions: { USEFUL: 21, AGREE: 14 } },
      { author: "first_vial", body: "I did this on my very first injection and spiraled for an hour. It was fine. You're fine.", daysAgo: 28, reactions: { LIKE: 18, FUNNY: 14 } },
      { author: "bac_water_noob", body: "Okay. Heart rate returning to normal. Thanks team.", daysAgo: 28, reactions: { FUNNY: 31, LIKE: 11 } },
      { author: "reggae_fiend", body: "Sequel to this thread will be 'accidentally dosed 2x' which is the next right of passage.", daysAgo: 27, reactions: { FUNNY: 44, LIKE: 14 } },
      { author: "syringe_shy", body: "I lurk these threads specifically to remind myself I'm not the only one who panics. Solidarity.", daysAgo: 26, reactions: { LIKE: 22, FUNNY: 11 } },
      { author: "cardinal_rule", body: "Locking-adjacent reminder: if you ever truly think something's medically wrong, call a doctor or urgent care, don't post on the internet first. We're happy to talk you down from a bubble but we're not your ER.", daysAgo: 25, reactions: { USEFUL: 22, AGREE: 14, LIKE: 8 } },
    ],
  },
  {
    title: "Traveling with peptides — TSA story time",
    body: "Just got back from a two-week trip and my fridge-to-carry-on setup actually worked. Ice packs, soft cooler, commercial medication labels (I printed some with my compound names on them). TSA didn't say a word.\n\nWhat's everyone else's travel experience? Worst moment? Best workaround?",
    author: "mothra",
    daysAgo: 37,
    views: 2340,
    reactions: { LIKE: 22, USEFUL: 11 },
    replies: [
      { author: "tirzepatide_tim", body: "Flown with tirz four times domestic, twice international. Never a problem. The compounded GLP-1s look enough like 'normal' pharmacy meds that nobody blinks.", daysAgo: 37, reactions: { USEFUL: 14 } },
      { author: "hexaclinic", body: "Domestic US is basically a non-issue. International — check the country's list. Some jurisdictions have weird laws about specific peptides (Korea, UAE come to mind) even for personal use.", daysAgo: 37, reactions: { USEFUL: 24, AGREE: 11 } },
      { author: "frontloader", body: "Worst moment: had a vial leak in my toiletry bag on a 12-hour flight. Arrived to a sticky cooler and no BPC. Learned to triple-bag everything.", daysAgo: 36, reactions: { FUNNY: 21, USEFUL: 14 } },
      { author: "pallet_jack", body: "I drive everywhere. Problem solved.", daysAgo: 36, reactions: { FUNNY: 29, LIKE: 11 } },
      { author: "cycle_wrangler", body: "Pro tip: carry syringes separately in a labeled pharmacy bag with a printed dose schedule. Nobody has ever asked me a follow-up question.", daysAgo: 35, reactions: { USEFUL: 22, LIKE: 9 } },
      { author: "weekendwarrior_p", body: "I just skip peptides when I travel. Not worth the anxiety for a 4-day trip.", daysAgo: 34, reactions: { AGREE: 14, LIKE: 7 } },
      { author: "achilles_love", body: "I've had TSA swab the outside of a vial but never open anything. The swab thing is normal; don't let it rattle you.", daysAgo: 32, reactions: { USEFUL: 11 } },
    ],
  },
  {
    title: "Music for the gym while on a cycle?",
    body: "Semi-serious question. Anytime I start a new compound I also inevitably end up updating my gym playlist because the old one feels wrong. Anyone else? What's on rotation for you right now?",
    author: "recomp_rex",
    daysAgo: 25,
    views: 1610,
    reactions: { LIKE: 18, FUNNY: 14 },
    replies: [
      { author: "reggae_fiend", body: "Dub. Always dub. You're all wrong and I'm right.", daysAgo: 25, reactions: { FUNNY: 34, LIKE: 18 } },
      { author: "pallet_jack", body: "Dying Fetus and Gojira. I am 44 years old and deeply unserious.", daysAgo: 25, reactions: { FUNNY: 41, LIKE: 14 } },
      { author: "selank_silence", body: "Classical. Specifically Shostakovich for heavy pulls. Works.", daysAgo: 24, reactions: { FUNNY: 28, LIKE: 11 } },
      { author: "nopain_noreign", body: "Hip-hop instrumentals. No lyrics means my brain doesn't wander between sets.", daysAgo: 23, reactions: { AGREE: 14, LIKE: 9 } },
      { author: "weekendwarrior_p", body: "Podcasts for cardio, hip-hop for lifting, silence for stretching. I've optimized this too much.", daysAgo: 22, reactions: { FUNNY: 19, LIKE: 11 } },
      { author: "fresh_cycle", body: "Whatever Spotify's 'Power Hour' algorithm serves. I've given up.", daysAgo: 20, reactions: { FUNNY: 14 } },
      { author: "fat_loss_log", body: "This thread is the least peptide-related thing all week and I love it.", daysAgo: 18, reactions: { LIKE: 22, FUNNY: 18 } },
    ],
  },
  {
    title: "What peptides DON'T do anything for you?",
    body: "We're surrounded by success stories. I want to hear about the compounds you ran faithfully and felt absolutely nothing from. Not every peptide works for every person and pretending otherwise helps no one.\n\nMine: Semax. Ran it for 3 months intranasal, correct dose, fresh product. Felt nothing. My wife felt nothing on her cycle either.",
    author: "citation_required",
    daysAgo: 48,
    views: 2840,
    reactions: { LIKE: 34, AGREE: 22 },
    replies: [
      { author: "dr_doubt", body: "Selank for me. 6 weeks. Absolutely nothing, not a bad nothing, just zero signal. Some people swear by it. I am not one of those people.", daysAgo: 48, reactions: { AGREE: 18 } },
      { author: "quietstorm", body: "Epitalon. Multiple cycles. I remain skeptical it does anything at any dose anyone actually uses, but I don't have a DEXA of my telomeres so who knows.", daysAgo: 48, reactions: { FUNNY: 22, AGREE: 14 } },
      { author: "acl_again", body: "GHK-Cu. Every friend claims glowing skin. I got a rash.", daysAgo: 47, reactions: { FUNNY: 31, AGREE: 9 } },
      { author: "theoretic", body: "Ipamorelin at low dose. I know this is controversial but 100mcg did nothing for me. Needed 300+ to feel anything. Your mileage will vary.", daysAgo: 46, reactions: { AGREE: 14, USEFUL: 8 } },
      { author: "stackbuilder", body: "CJC-1295 without DAC. I only feel DAC versions. Non-DAC feels like saline to me.", daysAgo: 45, reactions: { AGREE: 11 } },
      { author: "nad_nightowl", body: "NAD+ subq. Ran it 8 weeks. Nothing. The IV felt like something at least (probably placebo).", daysAgo: 43, reactions: { AGREE: 9, FUNNY: 7 } },
      { author: "dihexa_doubter", body: "Dihexa. Hence the name.", daysAgo: 40, reactions: { FUNNY: 41, LIKE: 14 } },
      { author: "citation_required", body: "Love this thread. 'Null results' are underweighted in online peptide discourse. Thanks for being honest everyone.", daysAgo: 38, reactions: { THANKS: 14, LIKE: 11 } },
    ],
  },
  {
    title: "Caloric surplus debate while on GH stack",
    body: "Reading a lot of conflicting stuff. Some say you have to be in a surplus to see gains from a GH/IGF stack. Others say it partitions even in deficit. I've been trying to recomp at maintenance and I don't know if that's the right call.\n\nCurrently: 5-day-on 2-off ipa/CJC, decent but not great gains. Am I leaving meat on the table by not bulking?",
    author: "recomp_rex",
    daysAgo: 44,
    views: 2380,
    reactions: { LIKE: 14, USEFUL: 9 },
    replies: [
      { author: "protocolwonk", body: "Partitioning is real but it's not magic. You'll still gain faster in a 200-cal surplus than at true maintenance. Peptides tilt the ratio, they don't overturn thermodynamics.", daysAgo: 44, reactions: { USEFUL: 22, AGREE: 11 } },
      { author: "hexaclinic", body: "Context matters — how lean are you, how trained are you, how old. Lean-and-trained at 40 can recomp at maintenance. Untrained or already fluffy, you won't.", daysAgo: 44, reactions: { USEFUL: 19, AGREE: 8 } },
      { author: "macrosguru", body: "Protein at 1g/lb minimum, carbs around training, fat fills the rest. If you're not hitting those basics the stack is doing half the work it could.", daysAgo: 43, reactions: { AGREE: 14, USEFUL: 9 } },
      { author: "igf_curve", body: "Also: check IGF-1. If you're not elevating IGF-1 to a meaningful degree the 'stack' is just ipa daydreaming. Numbers first.", daysAgo: 42, reactions: { USEFUL: 18, AGREE: 11 } },
      { author: "nopain_noreign", body: "100-150 above maintenance, slow, patient. Bulking hard while on GH just gets you fluff and insulin resistance.", daysAgo: 40, reactions: { AGREE: 19, LIKE: 6 } },
      { author: "recomp_rex", body: "Makes sense. Going to try 150 surplus for 8 weeks and re-panel. Thanks all.", daysAgo: 38, reactions: { LIKE: 9, THANKS: 6 } },
      { author: "dexa_devotee", body: "Re-DEXA at 8 weeks not just re-panel. Scale weight is noise on a small surplus.", daysAgo: 37, reactions: { USEFUL: 14, AGREE: 9 } },
    ],
  },
  {
    title: "Training style thread — strength vs hypertrophy on peptides",
    body: "Feel like most peptide users train hypertrophy style (bodybuilding-ish splits). Curious how many strength-focused lifters we have and whether your peptide stack changes by training focus.\n\nMe: powerlifting-adjacent, run BPC + TB-500 mostly for joint stuff, don't touch GH stacks. Curious who else is in that lane.",
    author: "pallet_jack",
    daysAgo: 51,
    views: 1940,
    reactions: { LIKE: 22 },
    replies: [
      { author: "nopain_noreign", body: "Strongman-adjacent here. BPC is non-negotiable. TB-500 for my rotator cuff. No GH. Not interested in weight-class problems.", daysAgo: 51, reactions: { AGREE: 14, LIKE: 9 } },
      { author: "mothra", body: "Powerlifting. BPC + low-dose GHK. GH stacks make my joints ache at my age, which is the opposite of what I want for maxes.", daysAgo: 50, reactions: { AGREE: 11, USEFUL: 6 } },
      { author: "hexaclinic", body: "Hybrid — strength base with hypertrophy accessories. Peptides are mostly recovery (BPC, TB-500). GH stack low-dose in the offseason only.", daysAgo: 49, reactions: { LIKE: 9 } },
      { author: "back_on_the_mat", body: "Combat sports. Recovery-focused stack is the only thing that lets me roll 5 days a week at 38. No GH — it slows my weight cut.", daysAgo: 48, reactions: { USEFUL: 11, AGREE: 7 } },
      { author: "recomp_rex", body: "Hypertrophy style here. Heavy on CJC/ipa, BPC as needed. Opposite protocol to you guys and that's fine — different goals.", daysAgo: 46, reactions: { LIKE: 8 } },
      { author: "acl_again", body: "Endurance athletes almost never show up in these threads. Curious if any are lurking.", daysAgo: 44, reactions: { LIKE: 11 } },
    ],
  },
  {
    title: "New compound name drops — heard about X?",
    body: "Every couple months there's a new 'you haven't heard of it yet' compound making rounds. Right now I'm seeing 'SLU-PP-332' and a few others pop up in chats I'm in.\n\nWhat's everyone actually seen real data on vs what's still vaporware? Let's separate signal from noise.",
    author: "the_stats_guy",
    daysAgo: 39,
    views: 2410,
    reactions: { LIKE: 14, USEFUL: 11 },
    replies: [
      { author: "dr_doubt", body: "SLU-PP-332 is a real ERR agonist with real animal data. Zero human data. Being marketed like there's human data. Tread carefully.", daysAgo: 39, reactions: { USEFUL: 22, AGREE: 14 } },
      { author: "showmethestudy", body: "Most 'new' compounds are either (a) repurposed research chemicals with 2 papers, (b) isomers of existing peptides, or (c) marketing.", daysAgo: 39, reactions: { AGREE: 19, USEFUL: 11 } },
      { author: "retatrutide_r", body: "Reta is the only 'new' one I'd say is genuinely worth paying attention to right now and the trial data is actually solid. Everything else is secondary.", daysAgo: 38, reactions: { AGREE: 14, USEFUL: 9 } },
      { author: "theoretic", body: "Humanin analogs have been 'about to break out' for 5 years and still haven't. I've stopped buying the hype cycle.", daysAgo: 37, reactions: { FUNNY: 22, AGREE: 11 } },
      { author: "nullhypothesis", body: "If the compound name sounds cool (3-4 letters and a number), that's the first red flag it's being marketed to you.", daysAgo: 36, reactions: { FUNNY: 28, AGREE: 14 } },
      { author: "cagrisema", body: "CagriSema is legit and the data is out there if you look. But it's a GLP-1/amylin combo not a 'new class' exactly.", daysAgo: 34, reactions: { USEFUL: 11 } },
    ],
  },
  {
    title: "Peptide documentaries / content recs",
    body: "Long flight next week. Looking for decent video content about peptides, anti-aging, GLP-1s, whatever that isn't 20-minute-youtuber-trying-to-sell-you-his-course energy. Netflix has one GLP-1 doc, I've seen it. What else?",
    author: "theoretic",
    daysAgo: 32,
    views: 1480,
    reactions: { LIKE: 14 },
    replies: [
      { author: "semax_mornings", body: "Peter Attia interviews on the Huberman channel are uneven but the ones with Lustig and with Sinclair are genuinely good. Avoid the 'stack' episodes.", daysAgo: 32, reactions: { USEFUL: 14, AGREE: 8 } },
      { author: "hexaclinic", body: "For GLP-1 specifically: Dr. Zubin Damania (ZDoggMD) did a few balanced breakdowns on YouTube. Not a doc but better than most docs.", daysAgo: 31, reactions: { USEFUL: 11 } },
      { author: "dr_doubt", body: "Honest answer: the best 'content' about peptides is the primary literature. No documentary will be as good as one hour on PubMed with a coffee.", daysAgo: 30, reactions: { AGREE: 14, FUNNY: 9 } },
      { author: "showmethestudy", body: "Sign of respect from dr_doubt right there.", daysAgo: 30, reactions: { FUNNY: 22, LIKE: 11 } },
      { author: "notes_taker", body: "The 'Bigger Stronger Faster' documentary is old but still relevant for the mindset piece even though it's about AAS. Peptides have the same culture dynamics.", daysAgo: 28, reactions: { USEFUL: 14, LIKE: 6 } },
      { author: "theoretic", body: "Great recs, thanks all. Will report back on which holds up for a 9-hour flight.", daysAgo: 26, reactions: { THANKS: 8 } },
    ],
  },
  {
    title: "Kitchen scale recommendations",
    body: "For measuring bac water + accurately dosing — I've been using a jewelry scale off Amazon that reads to 0.01g. Drifting on readings lately. Anyone have a specific scale they trust for the 0.01-0.1g range?",
    author: "labrat_ish",
    daysAgo: 29,
    views: 1340,
    reactions: { LIKE: 9 },
    replies: [
      { author: "panel_maxer", body: "American Weigh Scales AWS-100. 0.01g. Cheap, consistent, comes with calibration weights. I've had two last 5 years.", daysAgo: 29, reactions: { USEFUL: 18, AGREE: 9 } },
      { author: "stackbuilder", body: "AWS-100 second. The 'Gemini-20' model is the upgrade if you want 0.001g. Probably overkill for peptides.", daysAgo: 28, reactions: { USEFUL: 11 } },
      { author: "hexaclinic", body: "Honestly for peptide dosing a decent insulin syringe and tick marks is more precise than weighing. Are you sure you need a scale?", daysAgo: 27, reactions: { USEFUL: 14, AGREE: 7 } },
      { author: "labrat_ish", body: "Fair point. I use it more for food macros and it doubles for bac water math. Will grab the AWS-100. Thanks.", daysAgo: 26, reactions: { LIKE: 6 } },
    ],
  },
  {
    title: "How do you explain this hobby to friends/partner?",
    body: "Wife finally asked about the vials in the fridge last night and I realized I've been quietly building a pharmacy while telling her it's 'just supplements.' The look on her face was not favorable.\n\nHow do people actually talk about this IRL without sounding like a weird biohacker?",
    author: "goal_driven",
    daysAgo: 33,
    views: 2210,
    reactions: { LIKE: 28, FUNNY: 22 },
    replies: [
      { author: "reggae_fiend", body: "I tell my wife they're 'doctor-prescribed recovery injections' and technically that's not a lie because my buddy is a doctor and he prescribed them in a group chat.", daysAgo: 33, reactions: { FUNNY: 62, LIKE: 19 } },
      { author: "hexaclinic", body: "I'm a doctor and I still get the eyebrow from my partner. The truth is the healthiest option — 'these are peptides, they're legal research chemicals, here's the benefit I'm targeting.' Short and boring is best.", daysAgo: 33, reactions: { USEFUL: 24, AGREE: 11 } },
      { author: "acl_again", body: "I showed my wife the MRI before and after my ACL. That settled it.", daysAgo: 32, reactions: { LIKE: 22, USEFUL: 9 } },
      { author: "fat_loss_log", body: "My wife started on GLP-1s six months after I did. Problem solved.", daysAgo: 31, reactions: { FUNNY: 34, LIKE: 14 } },
      { author: "late_bloomer_m", body: "Mine just says 'you and your little injections' in the same tone she uses for my plants. I'll take it.", daysAgo: 30, reactions: { FUNNY: 38, LIKE: 11 } },
      { author: "quietstorm", body: "I don't explain it. I keep one mini fridge in the garage. Problem doesn't arise.", daysAgo: 28, reactions: { FUNNY: 28, LIKE: 14 } },
      { author: "notes_taker", body: "I just lie. I'm not proud of it but it's working.", daysAgo: 27, reactions: { FUNNY: 41, LIKE: 11 } },
      { author: "goal_driven", body: "This thread is the most useful non-useful thread I've read in months. Thanks team.", daysAgo: 25, reactions: { THANKS: 11, FUNNY: 8 } },
    ],
  },

  // ============================================================
  // QUIET THREADS (2-5 replies)
  // ============================================================
  {
    title: "Coffee while fasted on AM GHRH — still works?",
    body: "I've seen contradictory takes. Black coffee fasted before AM ipa/CJC — does it blunt GH pulse or not? I can't give up my morning coffee and I need to know whether I'm sabotaging my injection or not.",
    author: "slow_titrate",
    daysAgo: 22,
    views: 980,
    reactions: { LIKE: 9 },
    replies: [
      { author: "hexaclinic", body: "Black coffee alone doesn't meaningfully spike insulin for most people. You're fine. It's protein and carbs that blunt the pulse, not caffeine.", daysAgo: 22, reactions: { USEFUL: 22, AGREE: 11 } },
      { author: "protocolwonk", body: "Cosigning hexaclinic. Bulletproof coffee with MCT + butter is a different story — that one does blunt. Black is fine.", daysAgo: 21, reactions: { USEFUL: 14 } },
      { author: "slow_titrate", body: "Perfect, morning routine saved. Thanks.", daysAgo: 20, reactions: { THANKS: 6 } },
    ],
  },
  {
    title: "Birthday wishes for @cardinal_rule",
    body: "Pretty sure it's our favorite moderator's birthday today (I looked at the 'joined' date math and the age comment in another thread, sorry cardinal). Send him cake-shaped peptides.",
    author: "reggae_fiend",
    daysAgo: 18,
    views: 740,
    reactions: { FUNNY: 28, LIKE: 14 },
    replies: [
      { author: "petal_push", body: "Happy birthday cardinal! Thanks for keeping this place sane.", daysAgo: 18, reactions: { LIKE: 18 } },
      { author: "lucidverse", body: "Happy birthday brother. Next round of mod-work beers is on me.", daysAgo: 18, reactions: { LIKE: 14, FUNNY: 6 } },
      { author: "cardinal_rule", body: "Appreciate it all. Not saying it's my birthday but also not saying it isn't. Thread can stay up, 24 hours only.", daysAgo: 17, reactions: { FUNNY: 34, LIKE: 19 } },
      { author: "quietstorm", body: "HBD cardinal. Lurker solidarity.", daysAgo: 17, reactions: { LIKE: 11 } },
    ],
  },
  {
    title: "Podcasts worth listening to",
    body: "Beyond the obvious Huberman/Attia names, what lesser-known podcasts are actually worth listening to for peptide/longevity/metabolic content? Bonus points for hosts who actually read studies instead of vibes.",
    author: "the_stats_guy",
    daysAgo: 26,
    views: 1180,
    reactions: { LIKE: 14 },
    replies: [
      { author: "dr_doubt", body: "Simon Hill's 'The Proof' is underrated. He actually reads papers. The Rhonda Patrick episodes are a mixed bag but when they're good they're great.", daysAgo: 26, reactions: { USEFUL: 11, AGREE: 7 } },
      { author: "hexaclinic", body: "Danny Lennon's 'Sigma Nutrition Radio' — dense, science-y, no hype. Perfect long drive material.", daysAgo: 25, reactions: { USEFUL: 14, AGREE: 8 } },
      { author: "selank_silence", body: "For cognitive/neuro side: Stuart Ritchie's 'Studies Show' podcast is excellent at calling out bad science.", daysAgo: 24, reactions: { USEFUL: 9 } },
    ],
  },
  {
    title: "Frustrated with shipping times — anyone else",
    body: "Ordered 3 weeks ago. Still processing. Not a trash-talk thread, I get that things happen, but curious if everyone's seeing the same slowdown or if it's just my bad luck.",
    author: "cautious_ox",
    daysAgo: 24,
    views: 870,
    reactions: { AGREE: 11 },
    replies: [
      { author: "frontloader", body: "Same here, 12 days on one order. Seems to be a general slowdown this month. Customs or QC, not sure.", daysAgo: 24, reactions: { AGREE: 9 } },
      { author: "loading_phase", body: "Any international order right now is 2-3 weeks minimum. Domestic still fine in my experience.", daysAgo: 23, reactions: { USEFUL: 8, AGREE: 6 } },
      { author: "cardinal_rule", body: "Reminder that if this becomes a trash-talk thread I'll lock it. So far it's not — thanks for keeping it productive.", daysAgo: 22, reactions: { AGREE: 11, LIKE: 6 } },
    ],
  },
  {
    title: "News: new GLP-1 class trial results",
    body: "Saw a headline this morning about a Phase 3 readout for a new dual-action GLP-1/GIP. 22% weight loss at 48 weeks. Not quite tirz numbers but close, and allegedly cleaner side effect profile.\n\nPosting for discussion. Is this actually meaningful or is it the same compound with a new coat of paint?",
    author: "retatrutide_r",
    daysAgo: 12,
    views: 1420,
    reactions: { LIKE: 14, USEFUL: 8 },
    replies: [
      { author: "tirzepatide_tim", body: "22% at 48 weeks isn't quite matching reta's 24.2% at 48 but it's in the same ballpark. If the side effect claim holds up this could matter.", daysAgo: 12, reactions: { USEFUL: 14 } },
      { author: "glp1_doctor_pt", body: "Read the whole paper, not the press release. 'Cleaner side effects' in pharma press releases usually means 'we excluded the people who dropped out.'", daysAgo: 11, reactions: { AGREE: 22, USEFUL: 14, FUNNY: 9 } },
      { author: "showmethestudy", body: "Exactly what glp1_doctor_pt said. The completer analysis always looks cleaner than the ITT. Wait for the full paper.", daysAgo: 10, reactions: { AGREE: 11 } },
      { author: "fat_loss_log", body: "Watching closely. If this ends up cheaper than tirz it matters a lot for the people who still can't afford name-brand.", daysAgo: 8, reactions: { AGREE: 14, USEFUL: 6 } },
    ],
  },
  {
    title: "Community rule suggestions",
    body: "Had a thought in the shower. Would it be useful to have a 'low effort post' sub-rule that pushes brand new users to read the pinned FAQ before their first thread? Not gatekeeping — just reducing 'is this legit' threads we see 4x/week.\n\nMods, thoughts? Community, thoughts?",
    author: "protocolpilot",
    daysAgo: 19,
    views: 910,
    reactions: { LIKE: 11, AGREE: 9 },
    replies: [
      { author: "lucidverse", body: "We've discussed this internally. The tension is: we want new users to feel welcome, not gated. A soft nudge like 'hey, check the FAQ first' is fair. A hard block isn't.", daysAgo: 19, reactions: { AGREE: 14, USEFUL: 8 } },
      { author: "cardinal_rule", body: "Open to ideas. If someone wants to propose specific wording DM me and I'll take it to the mod team.", daysAgo: 18, reactions: { LIKE: 11, THANKS: 6 } },
      { author: "quietstorm", body: "As a heavy lurker: I'd rather see soft nudges than hard blocks. The FAQ isn't that readable right now — fixing the FAQ might help more than a rule change.", daysAgo: 17, reactions: { AGREE: 19, USEFUL: 11 } },
    ],
  },
  {
    title: "Lurker appreciation thread",
    body: "Shoutout to everyone who's here reading and rarely posting. You are the majority of this forum and you keep threads useful by not cluttering them. We see you.\n\n(Mostly posting this because I realized I am also mostly a lurker and I appreciate being appreciated.)",
    author: "reads_more_posts",
    daysAgo: 16,
    views: 1240,
    reactions: { LIKE: 38, FUNNY: 22 },
    replies: [
      { author: "silentscroll", body: "Felt seen. Returning to the shadows.", daysAgo: 16, reactions: { FUNNY: 41, LIKE: 19 } },
      { author: "once_per_month", body: "Once a month poster. This is my month. Hello.", daysAgo: 15, reactions: { LIKE: 22, FUNNY: 14 } },
      { author: "just_observing", body: "Rare post for me. Lurker solidarity.", daysAgo: 14, reactions: { LIKE: 14, FUNNY: 6 } },
      { author: "thread_saver", body: "I bookmark more than I post. I've saved ~400 threads since I joined. This one's now on the pile.", daysAgo: 13, reactions: { LIKE: 18, FUNNY: 9 } },
      { author: "reclusive_rn", body: "RN here, reclusive by nature and by username. Hi.", daysAgo: 12, reactions: { LIKE: 11 } },
    ],
  },
  {
    title: "Thread quality has been really good lately",
    body: "Meta observation — the last month of posts here has been unusually high signal. Fewer 'is BPC safe' posts, more 'here's my 12-week log with panels' type threads. Props to whoever's been quietly helping new folks land in the right category.",
    author: "hexaclinic",
    daysAgo: 11,
    views: 820,
    reactions: { LIKE: 24, AGREE: 18 },
    replies: [
      { author: "lucidverse", body: "Thank you. It has been a deliberate push from the mod team — better pinned posts, more gentle category redirects. Glad it's landing.", daysAgo: 11, reactions: { THANKS: 14, LIKE: 8 } },
      { author: "protocolpilot", body: "Agreed. Also noticing more people actually linking their sources, even in general. That was rare six months ago.", daysAgo: 10, reactions: { AGREE: 14 } },
      { author: "dr_doubt", body: "I'm finding fewer things to be annoyed about. This is concerning.", daysAgo: 8, reactions: { FUNNY: 38, LIKE: 14 } },
    ],
  },
  {
    title: "Friday check-in / how's your cycle going",
    body: "Low-stakes weekly check-in. No protocol questions, no debates. How's your week? Any wins, setbacks, silly moments? I'll start: dropped a full vial of BPC on my kitchen floor this morning and spent 10 minutes on my knees like a raccoon trying to save it. Rest in peace, little guy.",
    author: "recomp_rex",
    daysAgo: 9,
    views: 1120,
    reactions: { FUNNY: 38, LIKE: 14 },
    replies: [
      { author: "petal_push", body: "Lost 3lb on tirz this week, also lost my voice to allergies. Net neutral.", daysAgo: 9, reactions: { FUNNY: 22, LIKE: 11 } },
      { author: "acl_again", body: "First pain-free squat day in 4 months. Filed it under 'w' even though it's probably a fluke.", daysAgo: 8, reactions: { LIKE: 24, AGREE: 9 } },
      { author: "quietstorm", body: "Drew up my subq, sneezed, lost half the syringe into the air. Peptide mist for the kitchen.", daysAgo: 8, reactions: { FUNNY: 41, LIKE: 14 } },
      { author: "fat_loss_log", body: "Down another pound, sleeping better, only weird side effect is sulfur burps that could kill a horse.", daysAgo: 7, reactions: { FUNNY: 34, AGREE: 11 } },
      { author: "syringe_shy", body: "Successfully injected without flinching. First time. I'll take the W.", daysAgo: 6, reactions: { LIKE: 22, THANKS: 8 } },
    ],
  },
  {
    title: "Does anyone else feel dumb reading the bloodwork threads",
    body: "Genuine question. I read the bloodwork-metrics category for an hour last night and my eyes glazed over at 'allele-corrected Lp(a) in nmol/L.' Is this stuff learnable or should I just pay a clinician?",
    author: "new2peptides",
    daysAgo: 8,
    views: 880,
    reactions: { FUNNY: 22, LIKE: 14 },
    replies: [
      { author: "panel_maxer", body: "It's learnable. Start with the five numbers that actually matter (ApoB, HbA1c, fasting insulin, Lp(a), hsCRP) and ignore the rest for 6 months. Build from there.", daysAgo: 8, reactions: { USEFUL: 24, THANKS: 11 } },
      { author: "apob_reader", body: "Nobody was born understanding this. I read Attia's outlive cover to cover before I could follow the threads here. Worth the investment.", daysAgo: 7, reactions: { AGREE: 14, LIKE: 8 } },
      { author: "polite_guest", body: "Same boat as OP. This thread helped. Thanks everyone.", daysAgo: 6, reactions: { THANKS: 9, LIKE: 6 } },
    ],
  },
];
